### ISSUE TITLE
我该如何将声音输出到蓝牙音箱？

### ISSUE THREAD

**Issue by Nyxondra** [darknessomi/musicbox#105]
mpg321 -a bluetooth xxx.mp3 在我的蓝牙上运行良好
musicbox上该如何操作，或者能支持mpg321参数吗？

**Comment by Catofes** [comment]
1、 mpg123 吧

请尝试在 player.py 56行 
            self.popen_handler = subprocess.Popen(['mpg123', '-R', ], stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                                                  stderr=subprocess.PIPE)

改为 
            self.popen_handler = subprocess.Popen(['mpg123', '-a','bluetooth','-R', ], stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                                                  stderr=subprocess.PIPE)

试试看。并不知道能不能成功

**Comment by Nyxondra** [comment]
已成功，非常感谢

**Comment by Catofes** [comment]
成功的话close这个issue吧～  

你这种需求可以fork一份然后叫做 musicbox-bluetooth～ 感觉用的人不多～

**Comment by darknessomi** [comment]
@Catofes 其实和使用的系统也有很大的关系，有些系统会直接分配音频输出

**Comment by Nyxondra** [comment]
fork没什么必要，一行代码解决的事，能否增加一个变量，在启动时能接受mpg123的(部分)参数

**Comment by darknessomi** [comment]
可以

发自我的 iPhone

**Comment by Catofes** [comment]
我倒觉得给个配置文件更好一些？

**Comment by Catofes** [comment]
新版本已经支持配置文件，可以去更新一下，支持mpg123的额外参数。

**Comment by zhousmq** [comment]
> 已成功，非常感谢



> 我倒觉得给个配置文件更好一些？
> 
> On Fri, Aug 14, 2015, 19:41 ZHANG RT [notifications@github.com](mailto:notifications@github.com) wrote:
> 
> > 可以
> > 发自我的 iPhone
> > > 在 2015年8月14日，下午5:02，Nyxondra [notifications@github.com](mailto:notifications@github.com) 写道：
> > > fork没什么必要，一行代码解决的事，能否增加一个变量，在启动时能接受mpg123的(部分)参数
> > > ―
> > > Reply to this email directly or view it on GitHub.
> > 
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > [#105 (comment)](https://github.com/darknessomi/musicbox/issues/105#issuecomment-131084490)
> > .
vim /usr/local/lib/python2.7/dist-packages/NEMbox/config.py
将以下参数加上 -a bluetooth即可
    'mpg123_parameters': {
                'value': ['-a','bluetooth'],
                'default': ['-a','bluetooth'],
   }
