### ISSUE TITLE
终端模拟器下正常，纯命令行下不按键盘会闪烁，树莓派2官方系统

### ISSUE THREAD

**Issue by Nyxondra** [darknessomi/musicbox#108]
不能播放的问题已解决，我的失误

没有安装MPG123，系统自带MPG123命令，以为不用再装了

但是界面依然闪烁不知道为什么

**Comment by Catofes** [comment]
安装MPG123之后还是闪烁嘛？

**Comment by Nyxondra** [comment]
依然闪烁，感觉不是MPG123的锅，启动后无论有没有操作都闪，左侧边缘有个光标在跳动

HDMI闪，手机SSH闪，XSHELL也闪

**Comment by Catofes** [comment]
我怀疑  是性能问题。 设定的是100ms刷新一次屏幕，也就是重绘，可能性能不足所以闪烁？  不确定。

**Comment by Nyxondra** [comment]
我的是树莓派2，性能应该还过得去

装好几个ncurses界面的播放器，都没这种情况，不过看了代码musicbox用的是curses

自己尝试改代码，看看有没有解决办法

**Comment by Nyxondra** [comment]
menu.py：

     elf.screen.timeout(500)
     key = self.screen.getch()
     self.ui.screen.refresh()

     if key == -1:
             #self.ui.update_size()
             #self.player.update_size()
             #注释掉上面两行就不闪了
             pass

**Comment by Nyxondra** [comment]
代码里没有区分Terminal Emulator和command line而进行屏幕刷新

拙略的解决办法是注释掉ui.py的435行：self.screen.clear()

自己水平不济，还是等版本更新吧，感谢辛勤的开发者

**Comment by PiraHzq** [comment]
xterm 下也是不按键盘就闪烁。。。

**Comment by Saddam0523** [comment]
同 tmux 下面闪烁，而且 guake + tmux 比 gnome-terminal + tmux 闪烁更厉害

**Comment by PiraHzq** [comment]
用 export TERM="xterm" && musicbox启动，就不会闪烁了:P

**Comment by lianxiangru** [comment]
urxvt遇到同样问题

**Comment by huangya90** [comment]
同样遇到tmux下会闪烁.

**Comment by taizilongxu** [comment]
貌似是curses的锅 http://stackoverflow.com/questions/24964940/python-curses-tty-screen-blink
