### ISSUE TITLE
关于用管理员安装程序的问题 sudo pip install NetEase-MusicBox

### ISSUE THREAD

**Issue by hiapk** [darknessomi/musicbox#110]
帖子教程了里面 指定了用root来安装程序,在部分发行版上容易出现问题,(好吧,就是我遇到问题了,o(╯□╰)o)
本人使用的是gentoo系统,当用pip更新以pip安装的程序时,导致系统原来的包管理器portage失效
所以为了安全,推荐

pip install --user   NetEase-MusicBox

然后只要将 .local/bin 添加到PATH即可

**Comment by hiapk** [comment]
个人见解

**Comment by darknessomi** [comment]
其实 Mac 也会有类似的问题，所以对于有洁癖的同学来说，推荐自行安装依赖包，然后```python __init__.py```即可
