### ISSUE TITLE
经常会播放到一半卡住,怀疑是网络问题,该如何检查?

### ISSUE THREAD

**Issue by seyrenhe** [darknessomi/musicbox#111]
另外是否可以自定义设置码率,比如我连接到网易的网络不好,想设置成低码率的,反下我的木耳也听不出来高低码率的区别=.=

**Comment by Catofes** [comment]
如果网页访问不怎么卡的话，就不是网络问题。  

高低码率切换需要 @chaserhkj

**Comment by seyrenhe** [comment]
网页也卡,不过很奇怪,不是每首歌都卡.反正移动网络很坑.  
我以前都是在客户端上用中低码率听的.

**Comment by Catofes** [comment]
手机上网啊～  果然厉害。 不过还是建议更换网络。

新版本有缓存功能，可以试试看。需要aria2c，更新后启动一次并退出。然后去配置文件夹里的database中 cache设置为true 。

不过我觉的会使你第一次放某首歌的时候更卡

**Comment by seyrenhe** [comment]
不是手机上网，是移动的宽带。

我去试试缓存哈



—

**Comment by darknessomi** [comment]
手动修改码率，你需要在 api.py 中的第128行
```
def geturl(song):
    if song['hMusic']:
        music = song['hMusic']
        quality = 'HD'
    elif song['mMusic']:
        music = song['mMusic']
        quality = 'MD'
    elif song['lMusic']:
        music = song['lMusic']
        quality = 'LD'
```
改为
```
def geturl(song):
    if song['mMusic']:
        music = song['mMusic']
        quality = 'MD'
    elif song['lMusic']:
        music = song['lMusic']
        quality = 'LD'
```

**Comment by seyrenhe** [comment]
我改成96K才不会卡 +_+
```
def geturl(song):
       if song['lMusic']:
        music = song['lMusic']
        quality = 'LD'
```

**Comment by darknessomi** [comment]
@Catofes 感觉有必要搞个配置文件的东西了

**Comment by Catofes** [comment]
@darknessomi  嗯，感觉挺有必要。

**Comment by Catofes** [comment]
新版本已经支持配置文件，可以去更新一下，可以设置默认获取曲子的质量。

**Comment by seyrenhe** [comment]
赞!

**Comment by GoGoogle** [comment]
话说这个api.py文件在哪儿呢？我系统里面没搜索到啊。

**Comment by darknessomi** [comment]
@GoGoogle 可以直接 vim ~/netease-musicbox/config.json
修改"music_quality"

**Comment by GoGoogle** [comment]
@darknessomi 好像根本就没有~/netease-musicbox/这个目录啊

**Comment by darknessomi** [comment]
@GoGoogle 忘记加点了

**Comment by GoGoogle** [comment]
@darknessomi 果然……Goodidea
Thank you

**Comment by GoGoogle** [comment]
@darknessomi 为啥我改成2之后，默认还是HD 320K？

#我这破网也是醉了

**Comment by darknessomi** [comment]
@GoGoogle 你改的是value值么？

**Comment by GoGoogle** [comment]
@darknessomi 

看看，我改成了这样：

cat ~/.netease-musicbox/config.json
{
  "cache": {
    "default": false,
    "describe": "A toggle to enable cache function or not. Set value to true to enable it.",
    "value": true
  },
  "music_quality": {
    "default": 0,
    "describe": "Select the quality of the music. May be useful at the terrible network connection. 0 for high quality, 1 for medium and 2 for low.",
    "value": 2
  },
  "version": 1,
  "mpg123_parameters": {
    "default": [],
    "describe": "The additional parameters when mpg123 start.",
    "value": []
  },
  "aria2c_parameters": {
    "default": [],
    "describe": "The additional parameters when aria2c start to download something.",
    "value": []
  }
}

**Comment by Catofes** [comment]
你刷新一下你的列表试试看。 就是打开一首不在播放列表里面的曲子试试看。

**Comment by GoGoogle** [comment]
@Catofes 果然好神

那么，我该怎么处理一下听过的曲子？

**Comment by Catofes** [comment]
不用 切过去应该就是好的

**Comment by GoGoogle** [comment]
@Catofes 好吧，静观其变

现在不显示中文歌曲名
全是方块儿

**Comment by Catofes** [comment]
。。。 这是terminal 字体的问题吧。

**Comment by GoGoogle** [comment]
@Catofes 好吧，那我去放狗搜索一下怎么变terminal 字体……

**Comment by chaserhkj** [comment]
tty怎么显示中文……讲道理嘛，只有点阵英文字体可以用不是
非要显示中文的话可以用[kmscon](https://wiki.freedesktop.org/www/Software/kmscon/)

**Comment by GoGoogle** [comment]
@chaserhkj CentOS7能安装kmscon？如何安装？
