### ISSUE TITLE
不在Gnome界面里面就不能播放出声音？

### ISSUE THREAD

**Issue by GoGoogle** [darknessomi/musicbox#115]
这是版本吧？（第一次用CentOS7）
[root@off Music]# uname -a
Linux off.man 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

我直接本机登录控制台（纯命令）

执行musicbox是正常的， 但就是不出声音（我当然按下了空格键）

测试mpg123 5848302348252295.mp3报错：

[root@off Music]# mpg123 5848302348252295.mp3
[module.c:144] error: Failed to open module jack: file not found
[module.c:144] error: Failed to open module portaudio: file not found
[module.c:144] error: Failed to open module pulse: file not found
[module.c:144] error: Failed to open module sdl: file not found
[module.c:144] error: Failed to open module nas: file not found
[module.c:144] error: Failed to open module openal: file not found
[audio.c:180] error: Unable to find a working output module in this list: alsa,oss,jack,portaudio,pulse,sdl,nas,openal
[audio.c:532] error: Failed to open audio output module
[mpg123.c:902] error: Failed to initialize output, goodbye.

哪个大神帮我看看这是什么问题？该怎么解决？

**Comment by darknessomi** [comment]
你是如何安装mpg123的？不要编译安装
用这个试试 ```ftp://ftp.pbone.net/mirror/atrpms.net/el7-x86_64/atrpms/stable/mpg123-1.18.1-1.el7.x86_64.rpm```

**Comment by GoGoogle** [comment]
首先感谢一下楼上的神速回复。

在这14分钟里面，我做了几件事……

yum clean all
yum erase mpg123
yum erase musicbox

yum -y install mpg123
yum -y install musicbox

当然，我也看了一下版本，跟以前没什么不一样的

然而，神奇的事情来了，竟然好了

至于是什么原因导致的，我还真不知道，要回我怎么修好的，我就是干了这些个事情。

**Comment by GoGoogle** [comment]
然而，我重启之后又坏了。

弱弱的问一句，不要编译安装是怎么安装？




报错信息：


  File "/usr/bin/musicbox", line 9, in <module>
                                        load_entry_point('musicbox==0.1.3', 'console_scripts', 'musicbox')()
                                                                                                              File "/usr/lib/python2.7/site-packages/musicbox/__init__.py", line 12, in start
                                                                       Menu().start()
                                                                                       File "/usr/lib/python2.7/site-packages/musicbox/menu.py", line 232, in start
                                             self.player.shuffle()
                                                                    File "/usr/lib/python2.7/site-packages/musicbox/player.py", line 152, in shuffle
                              self.stop()
                                           File "/usr/lib/python2.7/site-packages/musicbox/player.py", line 124, in stop
                                                                                                                            self.popen_handler.stdin.write("Q\n")
                                       IOError: [Errno 32] 断开的管道

**Comment by GoGoogle** [comment]
[root@off ~]# rpm -ivh mpg123-1.18.1-1.el7.x86_64.rpm
警告：mpg123-1.18.1-1.el7.x86_64.rpm: 头V4 DSA/SHA1 Signature, 密钥 ID 66534c2b: NOKEY
错误：依赖检测失败：
        libartsc.so.0()(64bit) 被 mpg123-1.18.1-1.el7.x86_64 需要
        libaudio.so.2()(64bit) 被 mpg123-1.18.1-1.el7.x86_64 需要
        libesd.so.0()(64bit) 被 mpg123-1.18.1-1.el7.x86_64 需要
        libjack.so.0()(64bit) 被 mpg123-1.18.1-1.el7.x86_64 需要
        libportaudio.so.2()(64bit) 被 mpg123-1.18.1-1.el7.x86_64 需要

**Comment by darknessomi** [comment]
不要编译安装 == 不要去官网自己下载源码编译安装
至于报错，请安装最新版本

**Comment by GoGoogle** [comment]
/usr/bin/pulseaudio
好像是用这个启动了声卡……
然后就好了....
