### ISSUE TITLE
能否加入离线功能

### ISSUE THREAD

**Issue by ajaxsys** [darknessomi/musicbox#122]
很赞的播放器！
一个小建议。

本地收藏貌似仅把URL等信息添加到database.json
既然是“本地”，应该把歌曲也缓存一下吧。(或提供这个功能选项？)

（最近官方客户端都下架的，屏蔽的，以后就靠musicbox了！谢谢）

**Comment by darknessomi** [comment]
```vim .netease-musicbox/config.json```
"cache"."value" = true

**Comment by lxf1992521** [comment]
ilinunix@notebook:~/.netease-musicbox/cached$ ls
131239.mp3

能否命名为“名称-作者”这种形式、或者类似的命名，而不是纯数字？

谢谢啦。

**Comment by ajaxsys** [comment]
@darknessomi  
多谢。可是不知道为何出错了。

FWs-iMac:.netease-musicbox fw$ tail musicbox.log
################################################################################
################################################################################
################################################################################
################################################################################
2015-09-18 20:55:48,600 - DEBUG - NEMbox.cache:67: 34614557 Cache Error
################################################################################
2015-09-18 20:57:16,274 - DEBUG - NEMbox.cache:67: 108143 Cache Error
################################################################################
2015-09-18 21:07:49,876 - DEBUG - NEMbox.menu:407: 。。。
2015-09-18 21:07:52,284 - DEBUG - NEMbox.cache:67: 34003633 Cache Error

**Comment by darknessomi** [comment]
@ajaxsys 缓存功能需要安装 aria2

**Comment by darknessomi** [comment]
@lxf1992521 已经修改，请检查更新

**Comment by ajaxsys** [comment]
@darknessomi 

非常感谢，顺利解决了。

相当于总结一下吧：

	$ brew install aria2
	$ tail -n 1 musicbox.log
	2015-09-18 23:13:51,461 - DEBUG - NEMbox.cache:69: 34040693 Cache OK
	$ ls cached/
	34040693.mp3

最新版0.1.7.9解决了上面的数字问题

	$ sudo pip install NetEase-MusicBox -U
	$ ls cached/
	少女时代 - You Think.mp3
