### ISSUE TITLE
运行音乐盒时，我有这些错误......我对我的opensuse tumbleweed .. 

### ISSUE THREAD

**Issue by jedr93** [darknessomi/musicbox#123]
I have installed python-pip (python2) and mpg123
The version of  few days ago running correct, but now I have reinstalled the day today I no longer works package.

我已经安装了Python-PIP（python2）和mpg123的
的几天版本之前运行正确的，但现在我已经一天重新安装今天我不再工作包。

File "/usr/bin/musicbox", line 9, in <module>
    load_entry_point('NetEase-MusicBox==0.1.7.9', 'console_scripts', 'musicbox')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/NEMbox/__init__.py", line 8, in <module>
    import curses, traceback
ImportError: No module named curses

**Comment by darknessomi** [comment]
```No module named curses```
You need install curses or fix curses

**Comment by yutouyes** [comment]
The same problem.
----------------------------------------------------------------------------------------------------------------------------------
sudo pip install curses
Collecting curses
  Could not find a version that satisfies the requirement curses (from versions: )
No matching distribution found for curses
----------------------------------------------------------------------------------------------------------------------------------
Python3-curses has been installed but it doesn't work. While Failed to install python-curses and it reported “Failed to provide libpanelw.so.6(NCURSESTW6_5.7.20081102)(64bit)”. Nothing called libpanel or libpanelw in YaST. Can the box use python3-curses instead? thx

**Comment by abbycin** [comment]
@yutouyes 大鱼头你好．
```
zypper in python-pip python-curses python-devel
pip2 install NetEase-MusicBox
```
Leap42上只会提示pip版本低而已，晚上回去在Tumbleweed上装一个.
