### ISSUE TITLE
能够加入“云音乐电台”功能，期待ing！

### ISSUE THREAD

**Issue by lxf1992521** [darknessomi/musicbox#126]
作者现有的功能基本上很不错了，但如果能够加入私人FM（也就是云音乐电台）就更好了。

平时基本上都是打开 http://music.163.com/demo/fm 来一边工作，一般听歌，碰到喜欢的就点个红心。

如果能加个“私人FM”功能，并能都设置全局键，来设置红心、讨厌、下一曲，就基本上完胜网易官方的APP了。

期待！

**Comment by darknessomi** [comment]
简陋的 FM 功能出炉了，可以试试

**Comment by lxf1992521** [comment]
进入私人FM之后，能够获取歌曲列表，但是无法播放。

按空格键后屏幕闪过一些python代码，但无法看清。

查看日志，只出现了一行等号。

请修复一下。

**Comment by darknessomi** [comment]
@lxf1992521 我这边没有问题，缓存有没有开？

**Comment by lxf1992521** [comment]
刚在 ubuntu 11.04(Python 2.7.1+) 上面安装了最新版之后，不论开启缓存与否，都可以播放。

但是在载入歌单时，会短暂出现下面的代码
——————————————————————————————
享受高品质音乐，loading...
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
InsecurePlatformWarning
 /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connection.py:251: SecurityWarning: Certificate has no `subjectAltName`, falling back to check for a `commonName` for now.
 This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
SecurityWarning
——————————————————————————————

另外，当在播放FM的时候，按一下空格键想暂停，但没想到直接跳到当前第一首歌并开始播放，即不能够正常的暂停当前歌曲。

**Comment by lxf1992521** [comment]
当开启缓存的时候，播放FM时，发现缓存的歌曲不完整，用 mplayer打开检查时，有的播放到一半就退出了；

希望能够修改为：当发现当前歌曲播放5s之后，就开始缓存；且不论之后切到其他歌曲或者下一曲之后，都能够正常的缓存刚才的那个歌曲。

**Comment by lxf1992521** [comment]
还发现，FM只获取了 36 首歌曲，当播放完最后一曲的时候，就不再获取新的歌曲列表，而是什么也不做了。

希望能够在播放到最后一曲的时候，自动获取新的歌曲列表。

**Comment by darknessomi** [comment]
ssl 报错是因为 登陆接口 https 证书问题
缓存问题，缓存功能只是个测试，有待完善，敬请期待
FM 的话，后期会加上自动获取新的歌曲列表问题，现有的 api 一次仅能获取3首歌曲，鉴于频繁获取会被临时封IP ，我限制了一次性获取的数量并添加了间隔时间

**Comment by Catofes** [comment]
@lxf1992521  缓存功能是我写的，现在的确只是在测试阶段，所以有bug正常。

不过缓存的逻辑是这样的，当一首歌从未被缓存的时候且被播放的时候，额外开一个aria2c开始下载，此时还是在线播放。当下载正常完成后回调更新内部数据库记录本地数据，然后 *下次* 播放这首歌的时候会直接从本地播放。

所以 当使用musicbox播放的时候，如果遇到缓存过的曲子，曲子一定是完整的。卡顿一定是在线播放。

这也是缓存文件夹是隐藏文件夹，名字一开始是纯数字的原因，因为这里面下载的曲子并不是都是完整的，需要配合database.json来知道哪些是下载完成，哪些并没有下载完成。

**Comment by darknessomi** [comment]
@lxf1992521 请更新最新版本 0.1.9.0

**Comment by lxf1992521** [comment]
更新了新版本，体验很棒，谢谢啦！

另外在说一下自己新遇到的问题：
1. 当退出FM的歌单界面(H键)，而后又重新进入之后，歌单变成了新的获取的歌单，而当前播放的音乐就成了无水之源，不能暂停(空格键)，暂停的话就变成了开始新的歌单的第一曲歌了。
    建议能不能在退出FM界面的时候保存一下歌单，再次进入FM界面的时候，又读入保存的歌单。
2. 能不能加上系统的快捷键，比如很多时候都是在 tmux 中打开，然后就做其他事情去了；听到自己喜欢或者不喜欢的歌，直接就能够添加红心或者抛弃，或者跳过继续听下一曲。

**Comment by darknessomi** [comment]
@lxf1992521 P 键 可以载入现有列表，至于系统快捷键，我看看

**Comment by darknessomi** [comment]
@lxf1992521 系统快捷键我昨天看了下，必须依赖于 Linux - Xlib 或 Mac - Quartz, AppKit ，不是很理想，略臃肿啊

**Comment by darknessomi** [comment]
@lxf1992521 pyobjc-framework-Quartz 这个库依赖太多了
