### ISSUE TITLE
我播放音乐的时候是快进的

### ISSUE THREAD

**Issue by oubl23** [darknessomi/musicbox#139]
我播放音乐的时候是快进的，这是怎么回事，不能正常听音乐了。

**Comment by darknessomi** [comment]
``` rm -rf ~/.netease-musicbox ``` 试试

**Comment by oubl23** [comment]
还是不行，我旧版本是这样，我安装了最新版也是这种情况。

**Comment by darknessomi** [comment]
什么系统？尝试重装mpg123?

**Comment by lipop** [comment]
我也有类似的问题。系统是Archlinux, python2版本2.7.10.

**Comment by darknessomi** [comment]
二位直接使用 mpg123 播放歌曲正常么

**Comment by lipop** [comment]
Good catch! 确实mpg123 本身播放出现了问题。。。

**Comment by darknessomi** [comment]
可以尝试加参数让 mpg123 按正确速率播放，``` vim ~/.netease-musicbox/config.json ``` mpg123_parameters 这里可以添加参数

**Comment by oubl23** [comment]
我应该怎么修改啊？我也是mpg123的问题。

**Comment by darknessomi** [comment]
mpg123 有个调整播放速度的参数，你可以查下，然后添加到配置文件中

发自我的 iPhone

**Comment by Yuan-Hang** [comment]
这个问题解决了吗？应该怎样设置呢

**Comment by lipop** [comment]
​我发现mpg123在改变参数之后依然经常出现快进的问题。我把player修改成为mpv就好了。​

**Comment by diggerdu** [comment]
@lipop  请问如何把player修改为mpv

**Comment by lipop** [comment]
set player mpv
