### ISSUE TITLE
Mac 10.8.5 , Python 2.7.3 , 成功安装后，播放没有声音， 已经安装mpg

### ISSUE THREAD

**Issue by wensonsmith** [darknessomi/musicbox#140]
费劲千辛万苦终于安装好了，可是。。万万没想到，没有声音 

哭

**Comment by Catofes** [comment]
直接用mpg123 播放一首mp3看看有声音没

**Comment by darknessomi** [comment]
好老的版本！

**Comment by wensonsmith** [comment]
![image](https://cloud.githubusercontent.com/assets/2544185/10266772/26e61322-6aa8-11e5-9ba4-191bbfad118d.png)

安装的时候，有这个黄色的警告，难道跟这个有关？？

我用mpg123 直接播放音乐是没有问题的，
![image](https://cloud.githubusercontent.com/assets/2544185/10266773/4614a70e-6aa8-11e5-85e4-b707a001af0a.png)

@darknessomi  我是死守 10.8.5 了， 感觉后面系统太丑了····
 
10.9 的safari ，没有曲面墙，不喜欢··哈哈

**Comment by zhendongguan** [comment]
是mog123的问题，下载源码安装一下就好
