### ISSUE TITLE
使用新浪微博注册并且之后绑定了网易邮箱，但是不能用网易邮箱登录

### ISSUE THREAD

**Issue by ethanyoung** [darknessomi/musicbox#145]
目前支持此功能吗？

**Comment by darknessomi** [comment]
如果需要Oath登录的话，目前是不支持的

**Comment by ethanyoung** [comment]
并没有使用微博登录，没有用到Oauth。只是在最开始的时候注册使用了新浪微博，后来绑定了网易126邮箱。

我后来登录使用的是126网易邮箱。可以使用126邮箱和密码在网页版登录。
