### ISSUE TITLE
血崩，r键会删除当前条目

### ISSUE THREAD

**Issue by Karia-algo** [darknessomi/musicbox#146]
比如进帮助，然后rrrrrrrrr
不退出程序重来，删掉的东西就没。。。有。。。了
让我乐了半天2333333333

环境Gentoo+Systemd+Xfce4+python3.4

**Comment by Karia-algo** [comment]
呃，主要是歌曲和歌手条目会被删。
帮助被删掉其实是小事

**Comment by darknessomi** [comment]
是的，会删除的，不过也无大碍，下个版本会修正的

可以玩一下，不会对数据有影响 :-D

**Comment by chaserhkj** [comment]
我会说当初我写上移下移条目的代码的时候就发现了这个问题么…
主要觉得很有趣所以就当成一个奇怪的Feature（或者算彩蛋？）留下来了23333

**Comment by Karia-algo** [comment]
帮助里居然有写R键删除。。。才发现，原来是彩蛋嘛XD
