### ISSUE TITLE
网易云API问题，歌单只显示100条

### ISSUE THREAD

**Issue by LER0ever** [darknessomi/musicbox#148]
“创建的歌单”+“收藏的歌单”只能显示100条。。我表示我创建了56个，收藏了125个。
上图。左边是MusicBox有标号的到100没了，右边FeelUOwn到同样的歌单也没了
![image](https://cloud.githubusercontent.com/assets/10568668/10447305/00d457ba-71b6-11e5-875b-fbd7a7d7a251.png)

**Comment by darknessomi** [comment]
好多的歌单！
这个 bug 同样存在于其他列表.....唯一的办法就是换 API

**Comment by SudoToEat** [comment]
api.py 257行改一下limit
