### ISSUE TITLE
通过桌面环境通知显示歌词

### ISSUE THREAD

**Issue by chaserhkj** [darknessomi/musicbox#152]
在实现了全局快捷键绑定之后，经常还是吧musicbox放在后台听音乐然后在前台干别的事情的，但是这样做的时候有时想一起看一看歌词，就像传统的音乐软件有个悬浮窗歌词神马的……

但是我们这个程序要是涉及到悬浮窗歌词的话就得做gui，这和轻量化的初衷有所违背，于是就想到了通过`notify-send`之类的指令直接显示歌词……

现在试了一下直接在`Ui.build_process_bar`的更新歌词显示代码后面加了调用`notify-send`的代码……
效果基本上是这样的……

![screen](https://cloud.githubusercontent.com/assets/1768423/10484947/a7c3e7fc-72ba-11e5-9f41-13b4dea88fa7.png)

但是发现这样做略蠢……因为这段代码会在每次进度条更新的时候就被调用一次，虽然`notify-send`被设计成了重复通知不会重复显示……但是歌词走太快了有时会显示好几个弹窗，就和上面截图显示的一样……然后走太慢了之后又这一句没有唱完通知窗口就timeout消失了……而且没有歌词时会不停弹窗“暂无歌词”……

最理想的做法是用`notfiy-send`的`-t`选项控制通知的显示时间，来与歌词的显示时间同步，这样总只会有一个弹窗而且弹窗总是显示当前的这句歌词，但是这样的话可能原来的歌词显示部分的代码框架得整个改改……我觉得还是有点麻烦的……大家有什么想法，觉得这个功能值得加么？ = =

**Comment by darknessomi** [comment]
用 GTK ？
看看 http://imtx.me/archives/1098.html

**Comment by chaserhkj** [comment]
然而这哥们并没有给出源码 = =||||

**Comment by darknessomi** [comment]
我舔着脸，发邮件去要了Orz

**Comment by darknessomi** [comment]
@chaserhkj https://github.com/osdlyrics/osdlyrics 这个方案如何？

**Comment by ruizhipeng** [comment]
记得feeluown里面有个桌面歌词 https://github.com/cosven/FeelUOwn ，你看下能拿来用么，还有douban.fm里面有个命令行滚动的歌词 https://github.com/taizilongxu/douban.fm ，也可以参考下

**Comment by ruizhipeng** [comment]
@darknessomi 然而不@你果然看不到

**Comment by ruizhipeng** [comment]
而且对方同意了

**Comment by chaserhkj** [comment]
这俩项目都是MIT授权……也并不需要额外向作者征求同意啊 = =

问题的核心还是Feeluown的方案是用Qt实现的，要是真要用Qt画的话整个musicbox的依赖会麻烦很多很多……

**Comment by darknessomi** [comment]
今天出去玩了，才看见呢

发自我的 iPhone

**Comment by darknessomi** [comment]
这样搞真的对么，越来越多的功能有必要么？一直向官方客户端靠拢的话，似乎失去当初做这个软件的初衷了呢。

**Comment by ruizhipeng** [comment]
额 douban,fm里面有一个命令行的歌词滚动，可以参考那个来设计，不过确实，太多的功能会让原本精简的愿望变得越来越扯。。。

**Comment by ruizhipeng** [comment]
不过我觉得到是可以向模块化开发，分成播放器部分，歌词部分，等等

**Comment by ruizhipeng** [comment]
把每一部分做的专而精
