### ISSUE TITLE
关于歌曲播放提醒

### ISSUE THREAD

**Issue by kccai** [darknessomi/musicbox#158]
能提供一个关闭歌曲播放提醒的选项吗? 

Gnome 3的notification每次从顶部弹出来, 感觉比较烦. 这个功能对大部分人来说感觉是可以关掉的..

**Comment by darknessomi** [comment]
更新最新版本，修改配置文件即可关闭

**Comment by kccai** [comment]
@darknessomi 谢谢。贴一下修改办法：

修改配置配置文件 ~/.netease-musicbox/config.json 的 notifier 的部分如下
```
  "notifier": {
    "default": true, 
    "describe": "Notifier when switching songs.", 
    "value": false 
  }, 
```
不过现在的版本似乎又多了 signin success 的 notify 提示而且没法关掉 :joy_cat: ...
