### ISSUE TITLE
为什么播放的时候有的歌曲会快进播放

### ISSUE THREAD

**Issue by ayanamimcy** [darknessomi/musicbox#160]
为什么播放的时候有的歌曲会快进播放

**Comment by darknessomi** [comment]
请举栗

**Comment by ayanamimcy** [comment]
不清楚 我最近更新后有这个问题 不知道是不是我系统的问题

**Comment by zodiacg** [comment]
+1
我觉得应该是mpg123的问题，但是不好诊断。
具体症状是在播放的时候会带着刺啦刺啦的杂音不停的向前跳跃着播放，有时在播放一段时间后会恢复正常。

**Comment by ayanamimcy** [comment]
@zodiacg 就是这个样子的  我的也是archlinux

**Comment by zodiacg** [comment]
@ayanamimcy 自己编译了一遍跑了下，发现快进阶段alsa报告有underrun出现。问mpg123作者也没有特别针对性的方案。
目前解决的办法是：
1.用-a和-o参数启动mpg123（比如-o alsa -a hw:0,0），但是会导致声卡被mpg123独占，其它应用程序不能发出声音。
2.用-T参数启动mpg123，需要root权限。无root权限的时候也有所改善但是不能完全剔除。
3.用-b参数启动mpg123（比如-b150，最低144），但是播放开始前会有一小段空白（填缓冲区的时间，数字越大时间越长）。我现在就用这种。

**Comment by ayanamimcy** [comment]
@zodiacg 降级mpg123可不可以呢

**Comment by zodiacg** [comment]
@ayanamimcy 没有尝试，我不太习惯修改系统的包，尤其是Arch这种滚滚滚……

**Comment by ayanamimcy** [comment]
@zodiacg 试了下你的方法确实解决了 谢啦
