### ISSUE TITLE
需不需要签到功能呢？虽然我也不造签到有什么用。

### ISSUE THREAD

**Issue by darknessomi** [darknessomi/musicbox#161]
虽然有[现成的代码](https://gist.github.com/abrasumente233/a67e4b3b59990589600f)可以参考，但是这个功能是否有意义呢？

**Comment by dyis** [comment]
很有必要，查看快捷键在哪没找到

**Comment by hansnow** [comment]
要不然设置成每次打开自动签到吧？

**Comment by Saddam0523** [comment]
自动签到+1

**Comment by darknessomi** [comment]
#201 76e8aa0902e515dd87f9fe4dc5761f57a07e9f13
