### ISSUE TITLE
歌曲数据库变动

### ISSUE THREAD

**Issue by Catofes** [darknessomi/musicbox#162]
当时我以为曲子信息不会变，然后我发现自己太navie了

"527782": {"song_id": 527782, "artist": "\u539f\u7530\u3072\u3068\u307f", "song_name": "eternal f    eather", "mp3_url": "http://m1.music.126.net/q1m6qS5DDAePK6G9RJoETw==/3429376767578703.mp3", "album_name": "Alato \"ef -a fairy tale of the two.\" ORIGINAL SOUNDTRACK", "quality": "HD 320    k"}

这个曲子的url就变了。。。。所以估计要改把曲子信息储存的部分。

**Comment by Catofes** [comment]
这是不是最近网易下架的那一堆曲子啊。。。

**Comment by darknessomi** [comment]
网易现在新上架的曲目都统一被抹去了ID3-Tag和封面，是不是现有曲目也要修改了？

**Comment by Catofes** [comment]
。。。 所以曲子长久化储存到底好不好？ 虽然判断信息改变没有也挺简单的。

**Comment by darknessomi** [comment]
这个功能更多的不是被用来当做下载功能了吗😂

**Comment by Catofes** [comment]
对呀～  。

话说现在网易丧心病狂。 貌似为了防止版权问题，cdn就不给日本解析。

~ ❯ dig m2.music.126.net.wscdns.com @ns2.wscdns.com

; <<>> DiG 9.10.3 <<>> m2.music.126.net.wscdns.com @ns2.wscdns.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38492
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 5, ADDITIONAL: 6
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;m2.music.126.net.wscdns.com.	IN	A

;; ANSWER SECTION:
m2.music.126.net.wscdns.com. 300 IN	A	1.1.1.1

;; AUTHORITY SECTION:
wscdns.com.		172800	IN	NS	ns3.wscdns.com.
wscdns.com.		172800	IN	NS	ns4.wscdns.com.
wscdns.com.		172800	IN	NS	ns5.wscdns.com.
wscdns.com.		172800	IN	NS	ns1.wscdns.com.
wscdns.com.		172800	IN	NS	ns2.wscdns.com.

;; ADDITIONAL SECTION:
ns3.wscdns.com.		3600	IN	A	115.231.84.171
ns4.wscdns.com.		7200	IN	A	220.194.200.69
ns5.wscdns.com.		7200	IN	A	115.231.87.111
ns1.wscdns.com.		7200	IN	A	58.216.22.130
ns2.wscdns.com.		7200	IN	A	222.163.201.13

;; Query time: 406 msec
;; SERVER: 222.163.201.13#53(222.163.201.13)
;; WHEN: Wed Oct 28 15:00:36 CST 2015
;; MSG SIZE  rcvd: 242

~ ❯ dig m2.music.126.net.wscdns.com @ns2.wscdns.com

; <<>> DiG 9.10.3 <<>> m2.music.126.net.wscdns.com @ns2.wscdns.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61120
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;m2.music.126.net.wscdns.com.	IN	A

;; ANSWER SECTION:
m2.music.126.net.wscdns.com. 10800 IN	CNAME	netease.video.ourdvs.com.

;; Query time: 216 msec
;; SERVER: 222.163.201.13#53(222.163.201.13)
;; WHEN: Wed Oct 28 15:00:42 CST 2015
;; MSG SIZE  rcvd: 91

**Comment by Catofes** [comment]
好像不针对日本，香港也是。。。。

**Comment by Catofes** [comment]
不知道是bug 还是故意的。。 我去看看数据库部分吧。
