### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by lianxiangru** [darknessomi/musicbox#165]
I believe it will be much better for abroad users if there is a built-in proxy selection support. Thanks!

**Comment by Catofes** [comment]
You can edit mpg123's parameter in config.json to support http_proxy.

**Comment by lianxiangru** [comment]
@Catofes Do you mean the "config.py"?

**Comment by darknessomi** [comment]
``` ~/.netease-musicbox/config.json ```

**Comment by lianxiangru** [comment]
the @darknessomi  Oh, ic. Should the configuration be in the "value" entry or "default" entry?

That is to say, should it look like the following?

~~~
"mpg123_parameters": {
    "default": [], 
    "describe": "The additional parameters when mpg123 start.", 
    "value": ["-p", "http://127.0.0.1:7070"]
}
~~~

**Comment by Catofes** [comment]
@darknessomi  话说api接受系统级别代理吗？

**Comment by darknessomi** [comment]
@lianxiangru you can use  the ```http_proxy=0.0.0.0:8118 https_proxy=0.0.0.0:8118 musicbox```

**Comment by lianxiangru** [comment]
@darknessomi I have successfully set the proxy through the `config.json`. Thanks!!
