### ISSUE TITLE
下载脚本。

### ISSUE THREAD

**Issue by Catofes** [darknessomi/musicbox#166]
RT
我受不了啦！ 坑爹的网易云音乐下架了太多曲子啦
逼我dump 一份上传啦。。

https://gist.github.com/Catofes/d578a2ff63ef61761e6d

**Comment by darknessomi** [comment]
传说中的批量下载么😂

**Comment by Catofes** [comment]
ype。下載所有你聽過的曲子

**Comment by Catofes** [comment]
![2015-10-31 13-20-00](https://cloud.githubusercontent.com/assets/3324513/10862004/1c96000a-7fd2-11e5-9810-77d55c165295.png)

**Comment by Catofes** [comment]
然后发现如果歌曲里面有  / 就会在复制的时候出错。

23333

**Comment by sk1418** [comment]
@Catofes  看这个脚本是不是有帮助: https://github.com/sk1418/zhuaxia

**Comment by Catofes** [comment]
下载脚本我已经写好啦。 放在最上面啦。。
