### ISSUE TITLE
[Discussion] 关于params参数

### ISSUE THREAD

**Issue by sk1418** [darknessomi/musicbox#168]
你好, 通过google发现的你的项目. 很精致全面. 对于网易音乐应该了解比较深入.有个问题想请教一下

我写了一个多线程抓歌的脚本: https://github.com/sk1418/zhuaxia 然而命运多舛...因为人在国外先是xiami屏蔽海外ip, 现在网易也如此了.... :(

目前通过requests挂中国代理服务器可以实现下载. 但我公司已经有一个公司代理,再挂中国代理行不通了. 本以为只有在家用它了, 可我发现我的android应用以海外IP是可以下载的, 于是抓包发现了一个post请求:

	POST /eapi/song/enhance/download/url?br=128000&id=35403523_0 HTTP/1.1
	User-Agent: android
	Accept-Encoding: gzip
	Content-Length: 1063
	Content-Type: application/x-www-form-urlencoded; charset=UTF-8
	Host: music.163.com

这个返回的json包含MP3的真地址, 虽然和老api返回的地址不同了. 我测试不挂代理用wget下载没问题.

Querystring 很直观, 看来就是码率和id, 虽然不知道id后面的`_0`起什么作用.

但是让人挠头的是那个加密了的`params` 参数. 我通过google找到你的 

https://github.com/darknessomi/musicbox/wiki/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E6%96%B0%E7%99%BB%E5%BD%95API%E5%88%86%E6%9E%90

大概明白了这个复杂的加密过程. 

现在问题是, 我想解密这个串, 看post过去带了什么参数, 才好封装好payload,实现加密...  你知道这个post的参数信息吗? 或者怎么解密? 这个可能难点儿, 毕竟没有它的私钥...

谢谢.

**Comment by Catofes** [comment]
目测， 你找一个中国的缓存dns后，网易就可以用了。

**Comment by sk1418** [comment]
@Catofes 

谢谢你的DNS建议
我查到过,  用某些国内的DNS可以骗过163. 但是对于xiami, 有人说不好用. 这个我没测试. 主要我没采用这个的原因是

- 修改系统的DNS需要root权限.
- 我用了requests 库, 好像它不支持用customized DNS server, 通过读它代码,我找到了怎么修改, 但这需要patch它, 发布起来也不方便

所以我目前就使用proxy, 把proxy写在配置文件里, 可以随时改.

发现我上面写的那个POST链接后, 发现国外ip也可以直接下载. 只是params这个参数不明.才问一下. 

如果你以后从某些途径得知这个参数的内容, 请你记得来这个issue里comment 告知一下. 谢谢.

**Comment by sk1418** [comment]
btw, 基于我的测试,只用国内dns(114.114.114.114)好像对xiami, 163的歌曲都没法播放了. 还得代理呀..

**Comment by gao-lex** [comment]
post加密前的参数信息，没有它的私钥，真的是解不出来啊。
但是这个项目却有一些api
amzing！！
