### ISSUE TITLE
修改了一下搜索界面

### ISSUE THREAD

**Issue by chenai** [darknessomi/musicbox#17]
把搜索的界面和主界面作成统一的了，还打算修复几个bug,问一下作者是否要接受这些改动，需要的话我pull 个request ，不需要的话，我就自己切个分支，自己开发自己的版本了。
![image](https://cloud.githubusercontent.com/assets/6284003/5852188/b22ede56-a24d-11e4-971e-12f006177e62.png)

**Comment by darknessomi** [comment]
可以，你先提交 PR 看看呗
