### ISSUE TITLE
单曲添加到本地Cache

### ISSUE THREAD

**Issue by miuc** [darknessomi/musicbox#171]
有时候遇到喜欢的歌，会倾向于缓存到本地保存起来。

现有的cache逻辑要么全部缓存，要么全部不缓存，所以我forked了一个分支，添加了单曲添加到本地cache的功能。

https://github.com/miuc/musicbox/commit/db811de079d6a43ab96fa22d749f72090a68754c

如果可以的话希望能commit回source，没花多少时间，可能写的比较粗糙，请见谅哈，

盼回

**Comment by darknessomi** [comment]
你可以提交个 pr 啊😊
