### ISSUE TITLE
在Guake下拉终端中无法响应按键操作

### ISSUE THREAD

**Issue by VDerGoW** [darknessomi/musicbox#188]
在Guake终端中只有启动时能响应按键操作，按F12收起Guake之后（没有退出），再次打开Guake，经常会出现musicbox无法响应按键操作的情况，按键后终端里会打出按下的键的字符，然后自动清空。

系统：LinuxMint 17.2 Cinnamon 64 bit

**Comment by Catofes** [comment]
我这边没啥问题 guake+arch

**Comment by Saddam0523** [comment]
我之前也遇到过这个问题（openSUSE tumbleweed，GNOME3），但是我注意到当这个问题出现的时候终端本身的行为也不正常，比如提示符本来在屏幕底端，收起 Guake 再下拉之后变到屏幕中间去了（莫名其妙的滚屏？），而且其他 ncurses‎ 程序显示也不正常。所以我猜测这个问题是 Guake 引起的，而不是 musicbox 的 bug 。                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Qiuyu ZHANGSent: 2015年11月25日星期三 18:30To: darknessomi/musicboxReply To: darknessomi/musicboxSubject: [musicbox] 在Guake下拉终端中无法响应按键操作 (#188)在Guake终端中只有启动时能响应按键操作，按F12收起Guake之后（没有退出），再次打开Guake，经常会出现musicbox无法响应按键操作的情况，按键后终端里会打出按下的键的字符，然后自动清空。

系统：LinuxMint 17.2 Cinnamon 64 bit

—Reply to this email directly or view it on GitHub.

**Comment by VDerGoW** [comment]
今天在Ubuntu 14.04.3 64位系统自带的终端里也遇到了这个问题，但是试了几次都没发重现，还没搞清楚是什么导致的问题。
