### ISSUE TITLE
云音乐签到功能

### ISSUE THREAD

**Issue by lylh** [darknessomi/musicbox#201]
想实现网易云音乐签到功能，发现http://music.163.com/eapi/point/dailyTask 签到请求的params参数与登录的params是不一样，这个有研究下不，貌似也是一个固定的值

**Comment by zhuping** [comment]
看了前端js代码，发现签到传的参数是个type
`bH.cR("/api/point/dailyTask",{type:"json",method:"get",query:{type:1}`，试了把还是签到失败，返回301

**Comment by SatanSec** [comment]
http://music.163.com/weapi/point/dailyTask?csrf_token=
应该是这个地址吧

**Comment by zhuping** [comment]
我搞了个node版本的签到

**Comment by SatanSec** [comment]
@zhuping type为1表示手机为0表示pc？还是倒过来？今天在原作者的版本上加了自动签到，还没测试

**Comment by darknessomi** [comment]
@SatanSec 看源码 各跑了一次

**Comment by darknessomi** [comment]
网易是把移动端和Pc分开积分的

**Comment by SatanSec** [comment]
@darknessomi 道理我都懂，所以0还是1代表移动端

**Comment by darknessomi** [comment]
你就跑一个 然后去积分商城看log

**Comment by zhuping** [comment]
@SatanSec 1代表PC，0代表手机

**Comment by darknessomi** [comment]
76e8aa0902e515dd87f9fe4dc5761f57a07e9f13
