### ISSUE TITLE
可否告知一下播放音乐文件的流程？我想用php写一个

### ISSUE THREAD

**Issue by JellyBool** [darknessomi/musicbox#202]
看了下文档和源码，貌似音乐播放使用的是mpg123。不过我在尝试的时候貌似不支持直接使用音乐文件地址(`url方式`)播放。那音乐播放是怎么实现的呢？缓存么？

**Comment by taizilongxu** [comment]
可以用mplayer 直接播放url

**Comment by JellyBool** [comment]
@taizilongxu mac上有这货？

**Comment by JellyBool** [comment]
nice @taizilongxu 我看一下

**Comment by kigawas** [comment]
`mpg123 -R`打开remote模式，然后输入`L url\n`即可播放
