### ISSUE TITLE
请问有计划支持Python3吗？

### ISSUE THREAD

**Issue by gapplef** [darknessomi/musicbox#217]
刚发现这个软件，非常喜欢！
我日常的Python使用都已经转向了Python3，请问是否有计划支持Python3？

**Comment by darknessomi** [comment]
坐等 Python 4.0
http://www.curiousefficiency.org/posts/2014/08/python-4000.html

**Comment by gapplef** [comment]
文章不是在解释Python 4会平稳过度吗？虽然不保证-_-! Python 3的不兼容关键在于对文本的处理方式，Python 4则没有那么多问题。再说了还有7年的时间........
“I can't see any kind of change coming up that would require a Python 3 style backwards compatibility break and parallel support period.”
"At the current rate of language feature releases (roughly every 18 months), that means we would likely see Python 4.0 some time in 2023, ....."

而且主流的Linux发行版都已经在切换了：Fedora、Ubuntu、Debian的下一个版本都会默认Python3
https://wiki.openstack.org/wiki/Python3#Status_of_Python_3_in_Linux_distributions
真心希望能有Python 3版本！

p.s. 语言中不好的部分直接剔除干净，感觉很好呀，管他兼容不兼容(误，哈哈

**Comment by yangwe1** [comment]
:grin:期待支持Python3（其实是因为当初不小心把默认环境替换为python3了，现在要用python2总是要先`workon musicbox`...惨）
