### ISSUE TITLE
登录返回502

### ISSUE THREAD

**Issue by ltype** [darknessomi/musicbox#220]
from NEMbox import api
n = api.NetEase()

r = n.login('my email', 'my password')
print(r)

>{u'code': 502}

r = n.phone_login('my phone', 'my password')
print(json.dumps(r, ensure_ascii=False))

>{"message": "密码错误", "code": 502}

**Comment by ltype** [comment]
{"username":"my email","password":"my password","rememberLogin":"true","csrf_token":"ef97e91d4d90c97406ba9063099cf81f
99*****"}
网易新加了个参数

**Comment by xiaoming200990** [comment]
我的返回的是 501，一直登陆不了。
