### ISSUE TITLE
音乐URL失效

### ISSUE THREAD

**Issue by DickyT** [darknessomi/musicbox#225]
`http://m2.music.126.net/DC_k26q052UOSjhkZJANqA==/3405187515057853.mp3`
这种格式的音乐url看来都不能用了 抓了一下官方URL 下载地址都是这种形式的
`http://m10.music.126.net/20160116010005/c77eca5492cec710605e7fd65d6fe5ca/ymusic/MTEyMzc3NTI4/83b1f1d89bbf2016bddb4bde5b91d51c.mp3`
签名把时间都签进去了

**Comment by DickyT** [comment]
never mind...拼接的链接现在测试过了, 国内能打开, 国外就是无限菊花

**Comment by Tabjy** [comment]
国外 ```ping m*.music.126.net```永远返回```1.1.1.1``` 之前我的解决方法是用 ```p*.music.126.net```
然而最近发现通过[这个算法](https://github.com/darknessomi/musicbox/wiki/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90API%E5%88%86%E6%9E%90#user-content-5-下载音乐文件)得到的url 只有320kbps的能用（也就是```hMusic```） 剩下的```mMusic```和```lMusic```全部返回403 
然而偏偏就有这么多音乐没有高音质版的...

**Comment by DickyT** [comment]
网易云为了避版权煞费苦心啊...

**Comment by Tabjy** [comment]
所以说还是乖乖挂代理吧 【泪目

**Comment by DickyT** [comment]
本地自己用的话其实可以改host文件, 用ip138把几个常见的m*.music.126.net的IP拿出来之后改host文件就能用了. 新的API完全没有人琢磨怎么拼接链接,太惨了

**Comment by Tabjy** [comment]
雾草还能这么玩！我现在就去试试！

**Comment by dev-techmoe** [comment]
这部分更新进api.py了吗？
