### ISSUE TITLE
新版API相关

### ISSUE THREAD

**Issue by Catofes** [darknessomi/musicbox#227]
@darknessomi 

研究了一下午，感觉新版的api略坑。（新版api为当前网页版api， 旧版为我们正在使用的这一套）

新版api的 获取playerlist 和旧版一样。
新版api  获取 playerlist detail 不一样，返回的信息变了很多。
新版api 歌曲url 需要http://music.163.com/weapi/song/enhance/player/url获取

新败api 获取歌曲url的过期时间目测不知道有多久。有一个叫做expi的1200的参数，不过过了20分钟之后还是能用的。

新版api 无法获取灰色歌曲（版权问题下架）的url。
新版api 可以获取你音乐云盘中的歌曲。

大概就是这样了。。  _新版api无法获取版权歌曲_ 这一点好tmd坑

**Comment by Catofes** [comment]
详情： https://github.com/Catofes/musicbox/tree/new_api 

本来能听云盘里的曲子蛮有动力，然后发现听不了版权曲子瞬间就蔫了。

**Comment by darknessomi** [comment]
虽然新 API 挺坑的，但是也算是有一个后备方案了，辛苦辛苦

**Comment by liudangyi** [comment]
现在 iOS 和 Mac 版的网易云音乐用的都是 music.163.com/eapi 的 API，里边只有 params 没有 encSecKey。我尝试反编译 Mac 客户端结果发现代码都被加密了。。

另外，旧的 API 里可以使用 api/search/pc，这样获取到的信息比 api/search/get 多一些。

**Comment by Catofes** [comment]
嗯。 加密了好烦。。 只要能dump出公钥和参数就好。

**Comment by freeyoung** [comment]
可以通过在新版返回版权歌曲 404 时用旧版 API 尝试解析么？
