### ISSUE TITLE
Can't work in emacs

### ISSUE THREAD

**Issue by Sn0rt** [darknessomi/musicbox#229]
M+!
musicbox
![_2016-02-01_15-54-24](https://cloud.githubusercontent.com/assets/2706161/12711587/16b6e46a-c8fc-11e5-9728-5302d81eb099.png)

**Comment by lianxiangru** [comment]
emacs 的 shell应该不支持clear的 所以不行。

**Comment by Sn0rt** [comment]
好的  且不打算支持么？
那么close吧
