### ISSUE TITLE
不知道有没有计划支持debian

### ISSUE THREAD

**Issue by ysdlm** [darknessomi/musicbox#239]
如题所示，是不是有支持Debian的计划？

**Comment by darknessomi** [comment]
kali 能跑的话……

**Comment by ysdlm** [comment]
因为我现在用的Deepin是基于Debian的，但是在Deepin无法使用。

**Comment by darknessomi** [comment]
具体？

**Comment by ysdlm** [comment]
`x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.7 -c src/MD2.c -o build/temp.linux-x86_64-2.7/src/MD2.o

src/MD2.c:31:20: fatal error: Python.h: 没有那个文件或目录

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-6_ehd_/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-0F0_d5-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-6_ehd_/pycrypto
Traceback (most recent call last):
  File "/usr/bin/pip2", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip2')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 44: ordinal not in range(128)`

**Comment by claire2015** [comment]
Debian testing 用户，和上面一样的问题

**Comment by claire2015** [comment]
@ysdlm sudo apt-get install python-dev

**Comment by woailuoli993** [comment]
deepin 使可以使用的
