### ISSUE TITLE
修改了一下login界面

### ISSUE THREAD

**Issue by chenai** [darknessomi/musicbox#24]
![image](https://cloud.githubusercontent.com/assets/6284003/5972755/b057fec6-a899-11e4-9693-d4f79cd8af5c.png)

密码是无回显 输入
并且 每次读入账号密码 后 不做验证直接丢给 网易去做验证
这样更符合 浏览器网页的输入模式，提高用户体验，只要输错就会有报错

**Comment by chenai** [comment]
给你个PR ?

**Comment by darknessomi** [comment]
好，提交 PR 吧，thanks

**Comment by darknessomi** [comment]
可以e.g 删除了

**Comment by chenai** [comment]
我的qq号:57642903 方便交流？

**Comment by darknessomi** [comment]
好
