### ISSUE TITLE
Cygwin 无法登录

### ISSUE THREAD

**Issue by LER0ever** [darknessomi/musicbox#247]
今天在Cygwin下尝试了MusicBox，手动编译mpg123，除了无法登录外其他一切正常。
尝试用手机号和邮箱登录的时候出现python的InsecurePlatformWarning 和 SNIMissingWarning，然后提示用户信息不对。按照官方文档解决，安装pyopenssl ndg-httpsclient pyasn1了以后，错误信息没了，还是无法登录。

两个错误的详细信息
`SNIMissingWarning SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures.

InsecurePlatformWarning InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail.`

Cygwin: CYGWIN_NT-10.0-WOW 1.7.35
Python 2.7.10

**Comment by zinechant** [comment]
为何在windows下不用官方客户端？ 喜欢折腾？
