### ISSUE TITLE
缓存音乐到本地时，能否指定缓存文件夹

### ISSUE THREAD

**Issue by XiaoxiangLi** [darknessomi/musicbox#251]
现在都缓存到了 ~/.netease-musicbox/cached 文件夹下面，能不能通过 config.json 配置一个其他的缓存文件夹。
缓存音乐时，能不能在缓存文件夹里按歌单创建子文件夹，并且将歌单里的文件缓存其中。
还有，能不能一次性缓存整个歌单。

**Comment by Catofes** [comment]
缓存是加快load以及离线使用的，并不是下载，缓存文件的完整性都没有做保证。 因而不会有你说的这些功能。

如果你想下载，请自行写代码。  可以看我gist上的粒子。

**Comment by kmahyyg** [comment]
其实可以有另一个简单trick，不过就像作者说，并没有文件完整性保证。直接 ln -s 一个软链接过去就行了。
