### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by wenLiangcan** [darknessomi/musicbox#252]
另外两个相关的项目 [FeelUOwn](https://github.com/cosven/FeelUOwn) 和 [dmusic-plugin-NeteaseCloudMusic](https://github.com/wu-nerd/dmusic-plugin-NeteaseCloudMusic) 也用不了。

网页是可以登录的，所以不知是不是 API 发生了变动？

**Comment by darknessomi** [comment]
我这边登录正常~

**Comment by wenLiangcan** [comment]
@darknessomi 好像是用了 Comodo 的 DNS 的问题。。。，换了个 DNS 就可以登录了
