### ISSUE TITLE
能「上传」音乐吗？

### ISSUE THREAD

**Issue by kashu** [darknessomi/musicbox#255]
### 能否支持「上传」音乐到网易云音乐？

**Comment by hlx98007** [comment]
网易云音乐是网易把自己买来版权的音乐放上去给大众听的。
又不是你个人网盘，怎么传。。。

**Comment by kashu** [comment]
@hlx98007 
呵呵，你难道不知道可以上传？
http://www.xz7.com/article/67871_1.html
http://www.kafan.cn/edu/84011152.html

**Comment by kashu** [comment]
### 能否考虑增加「上传功能」？  谢谢！

### 网易云音乐推出「音乐云盘」功能，可以用于存储自己的音乐文件。
### 你只要将自己的 MP3 音乐上传到云盘去，就可以在手机、电脑端随时收听！

**Comment by hlx98007** [comment]
网页版有吗？musicbox用的都是网页版的api。

**Comment by kashu** [comment]
### 没有。开发，不就是 从无到有 吗？

**Comment by kashu** [comment]
### 开发不能想想办法？

**Comment by darknessomi** [comment]
楼主这语气真是像极了我们 PM 。。。。。。

**Comment by kashu** [comment]
@darknessomi 
什么PM ?
抱歉，已发往到邮箱里的那句话，我觉得好像有点不太妥当……
所以当时马上删了，换成了“开发能想想办法？”

**Comment by lianxiangru** [comment]
你想写自己写呗。开源社区又不拿你工资，凭什么听你的。
求人家给你开发新功能，就客气点。

**Comment by kashu** [comment]
@lianxiangru 
好吧，就当是我放了个屁吧……

**Comment by kashu** [comment]
@darknessomi
把这个 close 了吧，谢谢！

**Comment by lianxiangru** [comment]
@kashu 用大字不显得你有理。你的口气也毫无尊重。
你自己可以关 issue 的。

**Comment by mritd** [comment]
好吊的样子。。。

**Comment by lidashuang** [comment]
@kashu  好吊的样子。。。

**Comment by darknessomi** [comment]
提需求也要按照基本法啊~

**Comment by kashu** [comment]
@darknessomi  @lianxiangru @mritd  @lidashuang 
OK，莫名其妙，我感觉我好像被围攻了似的……

上面一共有我的7段comments，你们可以全部去看一遍。
**1）**当@darknessomi 第一次引用
邮件里的内容进行回复时，我在他下面马上作解释和回复：
>抱歉，已发往到邮箱里的那句话，我觉得好像有点不太妥当……
所以当时马上删了，换成了“开发能不能想想办法？”

因为github已经自动发到你们邮箱里的邮件，我怎么可能改得了、删得了？

**2）**而且当时我发出那句话后，我是立即把它修改成了
>开发不能想想办法？

**3）**为什么我当时就立即把那句个comments给修改了
因为当时我就知道，会有一些人在看这句话时可能会带着一些奇怪的语气或想法来看待这句话……

4）好吧，现在回过来看，这到底是句什么话：
>没有。开发，不就是 从无到有 吗？

这是我回复给5楼@hlx98007 的
这句话：“开发，不就是 从无到有 吗？”；
或者“开发，不就是一个从无到有的过程吗？”；
或者“开发，不就是把无变成有的吗？”
我在想，这句话真的有那么不尊重你们这些参与这个项目开发的人吗？
那抱歉，我是用一种相当平和的语气说出来的，没有其它过多的意思，而不是用那种“吼”出来的口气对你们说的。但你们非要强行把它用后面那种口气来理解或读出来，那是你们的自由。

5）那你们再看我的第6段comments
我是特别@lianxiangru 的，为什么我会说了这些话。因为在这些话上面有@lianxiangru回复给我的，无论用什么语气来看，我都不得不给予回复了！那我就不管了，撕开来说呗，那就是我第6段的内容。

6）@lianxiangru，为什么用加粗的大字体？因为我的显示器屏幕比较大，我有时会比较喜欢把字体弄大一点，阅读浏览时眼睛更舒适。
在发这个问题的时候，我也在同一时间在cosven的FeelUOwn项目里复制粘贴了这个问题，也是用的加粗大字体：https://github.com/cosven/FeelUOwn/issues/116

**Comment by kashu** [comment]
说实话，我并没有安装和用过**musicbox**，所以我不清楚这软件到底能不能支持上传音乐
我发这个问题的目的仅仅只是想问一下你们用过的人，而且我也不想费时间去安装测试


既然2楼的hlx98007回复了，我就知道了不支持，进而顺便再问一下，能不能“考虑增加上传功能”。

现在，反正我要了解的已经都了解了，我也就不再说了。

**Comment by lianxiangru** [comment]
@kashu 我没兴趣理解你为什么要用大字体。你上面的话让人感觉很不快。如果你是平时就这个行事风格，只能说明你与人沟通的方式一直都有问题。你想看大字体，放大网页就是了，不要在公共空间搞。你尊不尊重别人，是由他人的观感决定的，不是你说了让人不爽的话，然后一句其实我是尊重你的，就变成了尊重了。

没 linus 的能力，却得了 linus 的病，我觉得这个 issue 已经跑题了，没必要继续下去了。

开发是从无到有，那你开发啊，欢迎啊。什么叫“开发不能想想办法？”什么叫“难道你不知道有这功能？”，小学老师没教过你不要乱用反问句吗。

**Comment by amitbha** [comment]
@kashu PM 即产品经理
客户端还有 FeelUOwn，你可以去那问问
https://github.com/cosven/FeelUOwn

**Comment by arrowrowe** [comment]
re @amitbha: see [FeelUOwn/issues#116](https://github.com/cosven/FeelUOwn/issues/116).

**Comment by amitbha** [comment]
@arrowrowe 那据我所知还有 deepin music，✪ω✪，去 deepin 论坛问问吧
可是此功能不是网易开放的，仅在自家客户端可用，破解此功能就是吃力不讨好的事，何况没几个人用
楼主真需要的话，可以考虑去开源中国悬赏。https://zb.oschina.net/reward

**Comment by lianxiangru** [comment]
@amitbha 其实这个问题早就讨论过了， #182

**Comment by amitbha** [comment]
@lianxiangru 为什么我的问题就没人理呢？ #256 ，求解释

**Comment by lianxiangru** [comment]
@amitbha 没重现出这个问题，加个print 语句看看那个类型为什么变成int了吧。 我凌晨5：50了，得先睡了。

**Comment by amitbha** [comment]
@lianxiangru 虽然以前做过开发工作，可现在没热情搞了
我去追求宇宙人生的真理了，晚安
