### ISSUE TITLE
OS X 上貌似不能正常播放

### ISSUE THREAD

**Issue by TommyTC** [darknessomi/musicbox#261]
Python未入门新手一只。
10.11.2＋Python 2.7
唯一想到的可能就是我那自己装的Python 3了？ 有没有可能呢？

**Comment by darknessomi** [comment]
mpg123 ?

**Comment by wensonsmith** [comment]
我也是！ 什么都正常安装了，包括mpg123, 就是选中音乐后没有反应了。 

mac ox 10.11, python 2.7

**Comment by darknessomi** [comment]
可以通过查看 log ```~/.netease-musicbox/musicbox.log``` 发现问题哦，我的开发环境就是 OS X。

**Comment by wensonsmith** [comment]
```
 2016-02-22 08:59:24,249 - WARNING - NEMbox.menu:42: keybinder module not installed.
 2016-02-22 08:59:24,250 - WARNING - NEMbox.menu:43: Not binding global hotkeys.
```

这两个WARNING 会导致没法正常播放么？

我之前用10.8.5的时候，就来提过一次不能播放，升级10.11 还是不能。。。心痛。。

**Comment by kigawas** [comment]
@wensonsmith 
这两个是绑定快捷键的，不会影响播放。

建议先试试用mpg123，看能不能播放
