### ISSUE TITLE
AttributeError: Ui instance has no attribute 'build_login'

### ISSUE THREAD

**Issue by KJTang** [darknessomi/musicbox#268]
能正常打开，但是进入需要登录的地方时会出现错误，并且是文字显示与错误信息混杂在一起：

>                   网易云音乐
                   享受高品质音乐，loading...Traceback (most recent call last):
                                                                                 File "/usr/local/bin/musicbox", line 9, in <module>
                   0. 排行榜                                                                                                            load_entry_point('musicbox==0.1.2.4', 'console_scripts', 'musicbox')()
                   2. 新碟上架          File "/usr/local/lib/python2.7/dist-packages/src/__init__.py", line 11, in start
                   3. 精选歌单                                                                                              Menu().start()
                -> 4. 我的歌单                                                                                                              File "/usr/local/lib/python2.7/dist-packages/src/menu.py", line 160, in start
                   6. 打碟                           self.dispatch_enter(idx)
                   7. 收藏                                                     File "/usr/local/lib/python2.7/dist-packages/src/menu.py", line 306, in dispatch_enter
                   8. 搜索                                                                                                                                               self.choice_channel(idx)
                           File "/usr/local/lib/python2.7/dist-packages/src/menu.py", line 438, in choice_channel
                                                                                                                     data = self.ui.build_login()
                                                                                                                                                 AttributeError: Ui instance has no attribute 'build_login'

**Comment by KJTang** [comment]
好吧我的错，刚刚找到原因，原来是之前升级的时候弄错名字，原本应该是NetEase-MusicBox直接打成musicbox了。。。（话说musicbox又是个什么情况？）

**Comment by darknessomi** [comment]
并不知道是谁上传的😂
