### ISSUE TITLE
不用sudo就不能正常播

### ISSUE THREAD

**Issue by zerolxf** [darknessomi/musicbox#270]
1.不知道为什么不用sudo就不能正常播放,我用的是ubuntu15.10
2.还有登录的时候输错密码之后有一个填数字选择的，当时第一次按错了，然后就崩了，但是音乐还是照样放
3.之后密码输对了，又崩了

**Comment by darknessomi** [comment]
http://stackoverflow.com/questions/21055859/what-are-the-risks-of-running-sudo-pip
