### ISSUE TITLE
准备写个桌面歌词

### ISSUE THREAD

**Issue by lianxiangru** [darknessomi/musicbox#272]
@darknessomi 你觉得这个 feature 可以加吗。因为可能需要比较多代码，所以先来问一下。

**Comment by darknessomi** [comment]
我之前尝试过，问题在于跨平台的兼容性不太好，需要的依赖太多。
可以试试 gtk+ 自己撸或者 https://github.com/osdlyrics/osdlyrics

**Comment by darknessomi** [comment]
https://github.com/wu-nerd/dmusic-plugin-NeteaseCloudMusic 这个桌面歌词的实现可以参考一下

**Comment by lianxiangru** [comment]
@darknessomi 我打算 gtk，先支持 linux 平台。Mac 和 windows 我都不熟。
deepin 那个貌似是调用的 deepin music player 的 API 吧。

**Comment by lianxiangru** [comment]
@darknessomi 或者用 `notify-send -t` 来实现？就没有依赖问题了，简单很多。

**Comment by darknessomi** [comment]
notify-send 在某些桌面简直没法看。。。

**Comment by darknessomi** [comment]
用 gtk 的话 Mac 和 Linux 应该都能用了

**Comment by lianxiangru** [comment]
@darknessomi 不能吧， python-xlib 支持 mac？

**Comment by lianxiangru** [comment]
@darknessomi 
用 qt 写了 
![ss](https://cloud.githubusercontent.com/assets/8991941/13975033/bdc64b44-f087-11e5-9edd-66ea19575c00.png)

**Comment by darknessomi** [comment]
👍

**Comment by lianxiangru** [comment]
@darknessomi 功能初步写好了，你可以看一下，我发起 Pull Request 了。
![ss](https://cloud.githubusercontent.com/assets/8991941/13997374/27eb97ce-f108-11e5-98bb-8e7b4e7e7bea.png)

**Comment by fiepi** [comment]
@lianxiangru 请问怎么用这功能，快捷键？

**Comment by chaserhkj** [comment]
@fiepi 在配置文件`$HOME/.netease-musicbox/config.json`里面改

有一个`“osdlyrics"`的选项，`"value"`设置成`true`就可以了

**Comment by fiepi** [comment]
@chaserhkj thx

**Comment by fiepi** [comment]
@chaserhkj 依赖是 qt4 还是 qt5 呢？

**Comment by chaserhkj** [comment]
@fiepi

**Comment by darknessomi** [comment]
@fiepi pyqt/4.x  对应 qt 4.x

**Comment by fiepi** [comment]
@darknessomi 在arch这个包叫python-pyqt4，装过了，歌词出不来

**Comment by darknessomi** [comment]
qt 最好还是自己编译安装，包管理装的可能没有dbus支持

**Comment by chaserhkj** [comment]
@fiepi 你应该装`python2-qt4`....(我是不是回复太晚了
