### ISSUE TITLE
歌单只能显示到第999首歌

### ISSUE THREAD

**Issue by Robin-Cao** [darknessomi/musicbox#273]
我自己的歌单有一千多首歌，但是只能显示出前一千首，能否改进一下，谢谢
另外，我在翻歌单的时候翻着翻着就报错了
![2016-03-23 7 58 51](https://cloud.githubusercontent.com/assets/12699615/13984687/c9f91530-f132-11e5-9c38-0d0fa254702e.png)

**Comment by darknessomi** [comment]
已记录

**Comment by zdzliqian** [comment]
这都能发现
