### ISSUE TITLE
QT隐藏边框和置顶不能共存？

### ISSUE THREAD

**Issue by darknessomi** [darknessomi/musicbox#279]
![2016-03-25 4 45 53](https://cloud.githubusercontent.com/assets/6939375/14041137/1812df40-f2a9-11e5-8ae1-43319832ee48.png)
无边框挺好看的，置顶也很有用啊，都想要肿么办。。。。

**Comment by darknessomi** [comment]
问题联动 http://www.qtcentre.org/archive/index.php/t-45162.html

**Comment by lianxiangru** [comment]
可以啊，我就置顶 + 无边框 + 透明底色。
![ss](https://cloud.githubusercontent.com/assets/8991941/14051724/78a65d04-f29b-11e5-9354-614bcb13f175.png)

**Comment by darknessomi** [comment]
```
self.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
self.setWindowFlags(QtCore.Qt.X11BypassWindowManagerHint)
```
我的这两个是冲突的。。。。

**Comment by lianxiangru** [comment]
不知道了。。。不熟悉 Mac 是什么情况。。

**Comment by typcn** [comment]
setWindowFlags 是覆盖的吧。。。我没用过 python 版不清楚，用 CPP 版的时候都是 setFlags(FLAG1 | FLAG2 | FLAG3 )

**Comment by typcn** [comment]
(Qt.platform.os == "osx") ? (Qt.SubWindow) : (Qt.Tool)) | Qt.FramelessWindowHint | Qt.WindowSystemMenuHint | Qt.WindowStaysOnTopHint

之前写的置顶 + 无边框，望有用

**Comment by darknessomi** [comment]
@typcn 这样果然可以，多谢！
