### ISSUE TITLE
支持Windows麼？

### ISSUE THREAD

**Issue by franklinyu** [darknessomi/musicbox#28]
RT，既然Windows也有Python並且mpg123也有windows版本……

**Comment by darknessomi** [comment]
你可以尝试下😊

**Comment by chenai** [comment]
不支持的，谢谢，用的是curses库

**Comment by chenai** [comment]
如果未来确实有这个需求的话，我们会考虑移植到windows上

**Comment by jackwei** [comment]
大多数用户还是在windows 上呢

**Comment by darknessomi** [comment]
win有官方客户端啊，这只是为了 Linux 上没客户端可用的同学搞的

**Comment by franklinyu** [comment]
Windows無對應需求。
