### ISSUE TITLE
打开桌面歌词后不能使用全局按键

### ISSUE THREAD

**Issue by yangwe1** [darknessomi/musicbox#282]
我的系统是 Xubuntu 14.04，在打开桌面歌词之后，如果使用全局按键比如下一曲会有 bug，会同时播放当前歌曲和下一曲，这时如果关闭歌词会强退。在配置文件关闭桌面歌词后正常，想问一下是不是我的个人问题呢？在此之前安装的是 python-qt4

**Comment by darknessomi** [comment]
要是禁用全局按键呢？

**Comment by yangwe1** [comment]
嗯，不用全局按键用中括号 ']' 的话就可以正常切歌

**Comment by zinechant** [comment]
同样的问题，有什么办法可以调试吗，想尝试了解一下Python的项目
有没有log什么的可以分析吗

**Comment by yangwe1** [comment]
看了你的报错我也留意的去试了一下，是一样错误。全局切歌跟在程序里用 ']' 切歌都是调用的 `Menu.next_song()`，所以感觉很可能是 pyqt 那部分的问题，有个警告也跟它有关，
我是按下面的步骤重现的：

1. 在打开桌面歌词的之后使用全局快捷键切歌，再 `ps aux | grep mpg123`会看到有两个 mpg123 进程同时运行，就是说全局键又开了个进程放歌，桌面歌词显示的是原本的进程的。
2. 这个时候可以 Ctrl + Alt + P 暂停新开的解码进程，然后看起来像是一切恢复正常，不过若此时退出就会有个运行时警告：
```
/home/yw/.virtualenvs/musicbox_py2_7/luiocal/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:127: RuntimeWarning: PyOS_InputHook is available for interactive use of PyGTK
  set_interactive(1)
```
并且桌面歌词那部分不会退出而是继续显示在桌面上（当然不会继续滚动歌词），那如果不管这个继续运行 musicbox，听差不多一两首的时候就会出现强退，接着就是上面那个 core dumped 的报错出来了（歌词仍然不受影响继续显示，当然不会滚动）
有没有眉目？

**Comment by zinechant** [comment]
看了下代码,试着改了下，没有成功。
似乎是 osdlyrics 里起的进程接受了全局快捷键。但是不能理解这件事是怎么发生的。
不知道pyqt 内部会不会调用pyGTK

**Comment by chaserhkj** [comment]
其实我觉得既然osdlyrics里面已经用了pyQT，可以考虑把全局快捷键的绑定也用QT来做，这样可以减少依赖，也可以提高代码的一致性

等我毕业论文写完了就来填这坑Orz

**Comment by zinechant** [comment]
@chaserhkj 同在赶论文>_<.....
你也有相同的问题吗? 开启桌面歌词后全局快捷键就不行了？

**Comment by kigawas** [comment]
由于在某些环境下会导致严重问题，全局快捷键已经deprecated ( #395 )，需要可以手动启用
