### ISSUE TITLE
版权歌听不了了？

### ISSUE THREAD

**Issue by lianxiangru** [darknessomi/musicbox#283]
今天打开列表播放一堆放不了。要炸毛了。

**Comment by darknessomi** [comment]
能听啊。。。。

**Comment by lianxiangru** [comment]
@darknessomi 咦
你听 http://music.163.com/#/song?id=4915585
能听嘛

**Comment by darknessomi** [comment]
@lianxiangru 这个网页就能听啊。

**Comment by lianxiangru** [comment]
@darknessomi ........
晕，我看看出了啥问题。。。

**Comment by Catofes** [comment]
官方手机客户端木问题

**Comment by darknessomi** [comment]
我正在玩网易邮箱库呢。。。。有没有兴趣？

**Comment by lianxiangru** [comment]
@Catofes 可能是我在国内用来挂代理的服务器出问题了
@darknessomi 来个链接看看～

**Comment by darknessomi** [comment]
@lianxiangru 几十个 G，才下载了一半~ 等我下完放服务器上

**Comment by darknessomi** [comment]
@lianxiangru ```aHR0cHM6Ly9tZWdhLm56LyNGIUwxVTJqSUFMIUF5WEdSRy02Nll3S3RYNUMzQWpTbmc=```

**Comment by lianxiangru** [comment]
@darknessomi 提示 invalid folder link....

**Comment by lianxiangru** [comment]
啊 我多复制了一个字符

**Comment by darknessomi** [comment]
@lianxiangru 是网盘链接啦

**Comment by lianxiangru** [comment]
@darknessomi 嗯，已经打开了。这是怎么个玩法，密码库？

**Comment by darknessomi** [comment]
@lianxiangru 都是账号密码。。。。

**Comment by lianxiangru** [comment]
@darknessomi  好东西，已存

**Comment by lianxiangru** [comment]
@darknessomi 我还以为你要开个新 repo

**Comment by darknessomi** [comment]
@lianxiangru 有心无力_(:з」∠)_
