### ISSUE TITLE
现在听歌，有些歌不能听，会跳过去

### ISSUE THREAD

**Issue by whwq2012** [darknessomi/musicbox#284]
无论是私人fm里的，还是每日推荐里都有这种问题，还是我的歌单里，大部分日语歌会跳过去，不能播放，那些歌以前能播放的

**Comment by htfy96** [comment]
而且很多歌即使能放也会以7倍速度播放，根本不能听

**Comment by lianxiangru** [comment]
我也发现了，但还没找到时间 debug

**Comment by lianxiangru** [comment]
@darknessomi 
![ss](https://cloud.githubusercontent.com/assets/8991941/14230414/da10b588-f923-11e5-9799-a9882777a4bc.png)
The song is 乱舞のメロディ  -  シド  < BLEACH BEST TRAX >

**Comment by zhonghaoyu555** [comment]
同样问题，log无报错

**Comment by Nachtflug** [comment]
感觉老的API在一点点淘汰，试试新的API https://github.com/Catofes/musicbox/tree/new_api

**Comment by zxk7516** [comment]
是日语好像被跳过去吧.

**Comment by foreverbell** [comment]
@Nachtflug Hi, could you please add some document for the new APIs? ;p

**Comment by hrmthw** [comment]
确定，是日语歌都被跳过

**Comment by darknessomi** [comment]
嗯，是日语的，被版权下架的听不了了，貌似猪场直接删除资源了。

**Comment by hrmthw** [comment]
为何网页版可以听的

**Comment by darknessomi** [comment]
可以试试先用旧版 api 然后再用新版 api 获取资源？这样应该会让一些没被版权的日语歌恢复正常。
@lianxiangru @Catofes

**Comment by zhonghaoyu555** [comment]
#darknessomi 看了一下，日语歌几乎全部不能听了，就算是没被版权的也不行了。

**Comment by fiepi** [comment]
试过很多个版本的第三方客户端，都跪在日语歌上，估计api变了

**Comment by fiepi** [comment]
亲测，api没问题，是网易服务器404了。只要是日语歌曲，web版都不能播放。
看来是无解了，除非能搞到Android版的api
![screenshot_2016-04-09_04-18-43](https://cloud.githubusercontent.com/assets/15153999/14396507/8ce7c0a8-fe0a-11e5-964f-452fc17d2b57.png)
![screenshot_2016-04-09_04-25-51](https://cloud.githubusercontent.com/assets/15153999/14396617/2ca6727e-fe0b-11e5-9e17-61dec4cbf7c2.png)

**Comment by liverliu** [comment]
@fiepi 安卓API和客户端API其实是一样的，有个解决方法不过需要破解网易最新的API加密算法。
最新的API里面，虽然没法通过/eapi/song/enhance/player/url获取版权歌曲以m8开头的url，但是下载接口/eapi/song/enhance/download/url并没有限制，如果能反编译安卓客户端，就有有可能破解加密算法。

**Comment by lianxiangru** [comment]
日了 dog 了，99%歌都是日语歌的我。
![ss](https://cloud.githubusercontent.com/assets/8991941/14398848/64cd3f44-fdb5-11e5-9e04-eaa1e6c602e4.png)

**Comment by fiepi** [comment]
解决办法，采用Android版的接口，刚抓包分析了一下。
首先是根据歌曲id请求下载地址
![img_20160409_063314](https://cloud.githubusercontent.com/assets/15153999/14399257/735e2622-fdb0-11e5-8fe3-cb3de6c0d737.jpg)
拿到url
![screenshot_20160409-062713 01](https://cloud.githubusercontent.com/assets/15153999/14399264/8931e7a4-fdb0-11e5-8db8-54dc35e83ffb.png)

开始下载
![img_20160409_063935](https://cloud.githubusercontent.com/assets/15153999/14399299/e5c74bc6-fdb0-11e5-9806-4cd108bcf3be.jpg)

**Comment by lianxiangru** [comment]
http://www.eyaeya.com/archives/425

**Comment by lianxiangru** [comment]
@fiepi 版权的也能请求到 mp3 的 url 吗？

**Comment by fiepi** [comment]
@lianxiangru 应该可以，窝装了个xposed插件, 版权照样听

**Comment by lianxiangru** [comment]
@fiepi 求 PR 啊，或者给个 api 的说明也行。> <

**Comment by fiepi** [comment]
@lianxiangru  请求方式上边的截图很清楚了，关键是模拟客户端登录，拿到cookie，当然，可以进阶一点，先在 手机上登录，然后抓包提取cookie，复制到电脑/手动滑稽

**Comment by lianxiangru** [comment]
@fiepi 太麻烦了  最近准备NIPS完全没空  我先本地曲库凑合一阵吧  orz

论备份的重要性，自古以来版权相关网站就隔三差五大姨妈

**Comment by lianxiangru** [comment]
搞不好过两天保洁大妈又把电源插上了，api又能用了呢（

**Comment by seasonyuu** [comment]
@fiepi 那些歌曲在网页都是可以播放的 只要不是版权问题  你截图的那首歌我试了也可以播放，而且网页抓包跟项目中的api接口返回的mp3链接并不一样

**Comment by fiepi** [comment]
@seasonyuu 昨晚我用浏览器，日语歌曲确实不能播放，今天又可以了

**Comment by seasonyuu** [comment]
@fiepi 我也觉得是api又更新了，上面截图里面的MP3链接是旧版api的链接。现在网易大概在一个过渡期，正在将旧版本的歌曲一步步全都迁移到新版本中来。所以大概新版本api的抓取要从网页版着手才行

**Comment by fiepi** [comment]
@seasonyuu 找到原因了，是我浏览器扩展插件里的一个脚本的锅。这个脚本开启后会导致日语歌曲无法播放，右下角出现一个下载图标指向404的mp3链接（分析了一下这个脚本，使用了与musicbox一样的api解析出的mp3下载链接），关闭脚本后恢复正常。
由此可见日语歌曲专门有一套不同的api。
还是建议改用客户端版的接口，仔细抓包分析，应该可以弄出来。
脚本开启前后对比
![screenshot_2016-04-09_22-26-26](https://cloud.githubusercontent.com/assets/15153999/14404169/7552717a-fea2-11e5-9bfc-6dd983fa2bbd.png)
![screenshot_2016-04-09_22-26-52](https://cloud.githubusercontent.com/assets/15153999/14404171/7e065b2e-fea2-11e5-8411-08c0f8fc0d9d.png)

**Comment by fiepi** [comment]
刚用wireshark分析了一下网页版播放日文歌曲的情况。请求到的歌曲url格式与之前我在手机上抓到的完全一致。
结果如下：

![screenshot_2016-04-09_23-51-57](https://cloud.githubusercontent.com/assets/15153999/14404670/dc250cc6-feae-11e5-8c11-87c145b4d3d8.png)

之前在手机是抓到的结果：
![img_20160409_063935](https://cloud.githubusercontent.com/assets/15153999/14399299/e5c74bc6-fdb0-11e5-9806-4cd108bcf3be.jpg)

**Comment by lianxiangru** [comment]
@fiepi 绕了一圈又回到四楼的结论。。。

**Comment by seasonyuu** [comment]
@fiepi 不是这样的 网易云音乐仍存在大部分歌曲使用旧版api 的url规则  旧版比例比新版大

**Comment by fiepi** [comment]
窝不会 python，大概看了下代码，抓包分析后，尝试照葫芦画瓢写个新的 geturl 方法，不造text里要有神马，估计会有歌曲id之类的信息。。
```
def get_url(self, song_id):
        action = 'http://music.163.com/weapi/song/enhance/player/url?csrf_token='
        self.session.cookies.load()
        csrf = ""
        for cookie in self.session.cookies:
            if cookie.name == "__csrf":
                csrf = cookie.value
        if csrf == "":
            return False
        action += csrf
        text = {
            #这里有啥？不懂
            "csrf_token": csrf
        }
        data = encrypted_request(text)
        try:
            data = self.httpRequest('POST', action, data)
            return data['url']
        except:
            return -1
```

![screenshot_2016-04-10_21-27-59](https://cloud.githubusercontent.com/assets/15153999/14410487/72bdf1ca-ff63-11e5-97a2-04fc8143a879.png)
![screenshot_2016-04-10_21-29-35](https://cloud.githubusercontent.com/assets/15153999/14410489/7b1fa3f4-ff63-11e5-93b0-14500cbe2bb3.png)

**Comment by fiepi** [comment]
@seasonyuu 抓包结果来看，现在web版歌曲都走新api了， 只是暂时日语之外的歌曲还能走旧版 api 而已，说不定什么时候就给停掉了

**Comment by seasonyuu** [comment]
@fiepi 是我表述有问题  应该说大部分歌曲用旧版api还可以获取到

**Comment by darknessomi** [comment]
可惜新版 API 不能听版权啊

**Comment by lianxiangru** [comment]
我已經走向自建音乐服务器的道路了。。。

**Comment by fiepi** [comment]
能不能开个新api的分支啊，楼上的https://github.com/Catofes/musicbox/tree/new_api貌似名不符实，用的还是原来的api，url显然还是本地拼凑出来的，而不是从服务器请求

**Comment by fiepi** [comment]
@lianxiangru 那还不如下载后从本地读取

**Comment by darknessomi** [comment]
@lianxiangru 握爪，我已经用家里的 NAS 搭起来 iTunes 服务了。

**Comment by Catofes** [comment]
@fiepi ...  喂喂喂 我至于骗你吗。。。
https://github.com/Catofes/musicbox/commit/0f777e21b61fa27f17ae594cf942325c9ae17af2

**Comment by Catofes** [comment]
@darknessomi  就想我之前说的， 新版api可以获取到个人云盘里面的曲子。 所以也不是完全没救。 如果我们能hack掉exe版本中上传的api 我觉得很有可能就能解决。

**Comment by Catofes** [comment]
@fiepi https://github.com/darknessomi/musicbox/wiki/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E6%96%B0%E7%89%88WebAPI%E5%88%86%E6%9E%90%E3%80%82

**Comment by fiepi** [comment]
@Catofes，对不起窝错了/乖，代码写的太妙了，回去马上试试

**Comment by fiepi** [comment]
@Catofes 你这个跑不起来啊
出现
```
...
... 
File "/usr/lib/python2.7/site-packages/NEMbox/config.py", line 139, in check_version
    self.check_version()
  File "/usr/lib/python2.7/site-packages/NEMbox/config.py", line 139, in check_version
    self.check_version()
  File "/usr/lib/python2.7/site-packages/NEMbox/config.py", line 100, in check_version
    if self.config["version"] == self.default_config["version"]:
RuntimeError: maximum recursion depth exceeded
```
查到是递归深度太小，改了递归深度
接着出现
`[1]    19165 segmentation fault (core dumped)  musicbox`

**Comment by fiepi** [comment]
@darknessomi 应该可以听版权歌曲，手机上有个xposed插件，不知是什么原理，版权歌曲可以听(比如泰勒的歌曲)，只是不能下载，甚至歌单里下架的歌曲也能恢复

**Comment by Catofes** [comment]
本来那货就不是怎么能用的，不过api应该是没问题的。

而且我建议你要用的话，删除一下本底文件可能会好一些。

妹妹你好胸 <notifications@github.com>于2016年4月11日周一 下午7:41写道：

**Comment by Catofes** [comment]
这个Xpose插件应该是来自
https://github.com/YiuChoi/Unlock163Music

这个repo引用自
https://github.com/bin456789/Unblock163MusicClient-Xposed

然后再引用自
https://github.com/EraserKing/Unblock163MusicClient

最终目标是
https://github.com/EraserKing/CloudMusicGear

然后锁速可以看到
https://github.com/EraserKing/CloudMusicGear/blob/071f57192ede2be8aefe0e9a1d172b44619ad1d3/CloudMusicGear/NeteaseIdProcess.cs

和musicbox没卵区别。

**Comment by lianxiangru** [comment]
………@fiepi
你说的插件前两天我装了，一样一堆歌不能放

**Comment by lianxiangru** [comment]
@fiepi 网上大部分项目api来源貌似都是@Catofes

**Comment by lianxiangru** [comment]
@darknessomi 不用任何苹果产品的我用ampache搭了个音乐服务器。。。

话说itunes服务也可以在家外面用手机访问吗？

**Comment by fiepi** [comment]
@darknessomi 你确定装的是最新版吗？

**Comment by lianxiangru** [comment]
@fiepi 你是想at我吗。。我是用最新的源码编译的。
https://github.com/bin456789/Unblock163MusicClient-Xposed/issues/2
作者自己也承认放不了

**Comment by darknessomi** [comment]
外网不行，但是可以 VPN，虽然我用的是移动硬盘，aac 还好，但 alac 实在是不行，魔都电信上传不给力

**Comment by fiepi** [comment]
@lianxiangru 
试试这个https://github.com/YiuChoi/Unlock163Music/releases

**Comment by lianxiangru** [comment]
@darknessomi 我用 dropbox 作为存储空间，每个帐号可以免费存 2 G 歌曲，在VPS上用ampache统一管理，感觉体验还可以。

@fiepi 试了 不行
我的一个歌单 http://music.163.com/#/playlist?id=20785430 后半部分大部分歌都放不出来

**Comment by fiepi** [comment]
@lianxiangru 全都可以播放
![screenshot_20160411-214328](https://cloud.githubusercontent.com/assets/15153999/14429077/86574796-ffc1-11e5-932b-6feab10926ad.png)

**Comment by lianxiangru** [comment]
...放不了，虽然是可以点，但是放不出来
难道因为我海外？

**Comment by lianxiangru** [comment]
@fiepi 我擦，开了VPN居然可以放了

黑科技啊

**Comment by fiepi** [comment]
@lianxiangru 在浏览器上看你的歌单，后半部全是灰白的无法播放，而手机全都可以播放

**Comment by lianxiangru** [comment]
@fiepi  确实黑科技，谢谢！

**Comment by fiepi** [comment]
@lianxiangru  我挂ss是为了翻出去，而你是为了翻回来。。。

**Comment by fiepi** [comment]
@lianxiangru 建议用shadowsocks，别用vpn了，ss可以分应用代理，方便不少

**Comment by lianxiangru** [comment]
@fiepi 本科实验室的古董服务器，并不能让我随便折腾。。

**Comment by lianxiangru** [comment]
@fiepi ss居然下载一个python包就可以用了。。。0配置啊。。。
已用上，thanks！

**Comment by fiepi** [comment]
@lianxiangru ss有很多版本，c写的libev最轻量，python版因为原开发者被查水表然后项目被清空了，也不怎么更新。海外党的话，若musicbox用新版api，部分歌曲如果无法播放，完全可以弄个国内的vps搭ss，linux上有个 proxychains 可以让终端里启动的程序走代理，如果用vpn走全局很不方便。

**Comment by darknessomi** [comment]
海外党果真是爽，居然都不知道ss的存在，手头倒是有多台空闲服务器可以无偿提供海外支持，说不定可以集成到musicbox上，方便换了新API的海外党们用

**Comment by lianxiangru** [comment]
@fiepi 已经厌倦了配置，两行命令就能用上是坠吼的。
万年 linux 党平时翻回去都是 http 代理。
手机 ss 真 tm 好用。

@darknessomi 像音乐这种大的媒体文件多少带宽都不够很多人用吧，用 script 抓取网上的 http 代理列表可能比较可行吧。

**Comment by darknessomi** [comment]
人少的话……百兆还是能扛下的，毕竟有时差

**Comment by lianxiangru** [comment]
@darknessomi 牛逼，百兆无偿支持，土豪撒钱了！

**Comment by darknessomi** [comment]
谷时搞个公益也算充分利用了带宽2333

**Comment by Nachtflug** [comment]
@fiepi Catofes那个新API fork 比较早，里面参数要改一下。我记得把config里version 改成6就可以用了
![23d36ec8-d48f-4866-b749-474653843eef](https://cloud.githubusercontent.com/assets/8402784/14446161/940f8ae6-0085-11e6-8611-ecb0fb697633.png)

**Comment by darknessomi** [comment]
@Catofes 抽空发个 pr ？或者更新一下你那边代码也行

**Comment by disoul** [comment]
用了新的api网易那边会报500，后端java报错有个类拿不到
@Catofes clone了大佬的新API版本替换掉使用发现报500的歌还是放不了

**Comment by disoul** [comment]
测试了一下，新api算法里随机生成的aes 16位seckey只有部分网易会认，有些返回500有些就正常    
下面是一些，测试结果    

* fffdfffd39fffd53 [成功]
* fffd3c6324fffdff
*10fffdfffdfffd7c
* 2228d22fffdfffdf
* fffd373e9fffdfff
* fffd22fffdfffdff
* fffdfffd6a1f7fff
* 1538fffd5e19fffd
* fffd1fffd6cfffdf
* fffdfffd5cfffdff
* 3cfffd1121fffd15
* 6cfffd958fffdfff
* 27fffdfffdfffdff [成功]
fffd143c19dfffd1
7fffdfffd1957fff
61113c7c621cfffd [成功]

**Comment by AlecWong** [comment]
现在有什么办法获得歌曲的连接么。旧版的部分获得的404了。。

**Comment by wu-nerd** [comment]
新的API应该是可用的 根据[API分析](https://github.com/darknessomi/musicbox/wiki/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E6%96%B0%E7%89%88WebAPI%E5%88%86%E6%9E%90%E3%80%82#%E8%8E%B7%E5%8F%96%E6%AD%8C%E6%9B%B2url)
主要有两个变量ids和br
ids是歌曲id列表
br是比特率，如192000/320000
文中提到的 "csrf_token"倒是可以不加的

如需要代码参考： 979c1d257abf74220c5b883277df2e623fc078c3

**Comment by wu-nerd** [comment]
如果歌曲下架了，API并不会像API[分析](https://github.com/darknessomi/musicbox/wiki/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E6%96%B0%E7%89%88WebAPI%E5%88%86%E6%9E%90%E3%80%82#%E8%8E%B7%E5%8F%96%E6%AD%8C%E6%9B%B2url)里说得那样返回404，似乎是-110，并且url为空。

**Comment by AlecWong** [comment]
必须要登录才能获得url吗？

**Comment by wu-nerd** [comment]
@AlecWong 
在网页版测试了下，不登录的情况下也是可以的。
API中的csrf_token在不登录的情况下也会在cookie中生成。
只是不知道如何实现。

**Comment by AlecWong** [comment]
from xdg_support import get_cache_file
q请问，这一个import如何解决？ 找不到xdg_support

**Comment by wu-nerd** [comment]
@AlecWong 这个是深度音乐播放器的插件，调用了播放器的一些库。
如果需要的话可以git clone https://github.com/martyr-deepin/deepin-utils.git
然后sys.path.append('path/to/deepin-music/src')

**Comment by wu-nerd** [comment]
不好意思，是git clone https://github.com/linuxdeepin/deepin-music.git

**Comment by biergaizi** [comment]
我观察了一下，有些曲名专辑艺术家都是英文的日文歌曲都被撤下了，但少数曲名专辑艺术家都是日文的歌曲反而啥事没有。如果网易的确是在批量把日文歌曲从**旧** API 下撤下，我倒是觉得根据什么条件判断歌曲是比较有趣的问题。

**Comment by fiepi** [comment]
日文全跪了。。wine了个win版先用着。。

**Comment by darknessomi** [comment]
fixed closed
