### ISSUE TITLE
可以增加歌词鼠标穿透的功能么 

### ISSUE THREAD

**Issue by ruizhipeng** [darknessomi/musicbox#286]
或者增加相对应的快捷键 偶尔会挡住其他页面的按钮

**Comment by darknessomi** [comment]
抱歉，qt 不支持，除非引用 x11 的 XShapeCombineRectangles，需要python-xlib，不想再加过多依赖了，只能暂时搁置。

**Comment by ruizhipeng** [comment]
恩 了解 请加油
