### ISSUE TITLE
建议添显示/隐藏快捷键列表的功能键。

### ISSUE THREAD

**Issue by DingSoung** [darknessomi/musicbox#29]

**Comment by chenai** [comment]
不太清楚你的意思，能详细描述一下么？

**Comment by DingSoung** [comment]
因为初期使用，不熟悉快捷键操作，需要打开Github对照着操作，如果软件界面上显示着快捷键列表，就很方便了

**Comment by chenai** [comment]
主菜单第九项是帮助，操作说明都在里面，另外这个快捷键的操作是基于vim的。

**Comment by mwxxhdb** [comment]
```
-> 0. 排行榜
    1. 艺术家
    2. 新碟上架
    3. 精选歌单
    4. 我的歌单
    5. 主播电台
    6. 每日推荐歌曲
    7. 每日推荐歌单
    8. 私人FM
    9. 搜索
```
没有找到帮助菜单呢？
怎么样可以在程序里显示一个快捷键列表？
现在使用的时候都要打开 readme 看键盘快捷键列表
https://github.com/darknessomi/musicbox#%E9%94%AE%E7%9B%98%E5%BF%AB%E6%8D%B7%E9%94%AE

**Comment by kigawas** [comment]
> ```
> -> 0. 排行榜
>     1. 艺术家
>     2. 新碟上架
>     3. 精选歌单
>     4. 我的歌单
>     5. 主播电台
>     6. 每日推荐歌曲
>     7. 每日推荐歌单
>     8. 私人FM
>     9. 搜索
> ```
> 没有找到帮助菜单呢？
> 怎么样可以在程序里显示一个快捷键列表？
> 现在使用的时候都要打开 readme 看键盘快捷键列表
> https://github.com/darknessomi/musicbox#%E9%94%AE%E7%9B%98%E5%BF%AB%E6%8D%B7%E9%94%AE

我记得好像首页是有个帮助的

**Comment by mwxxhdb** [comment]
> > ```
> > -> 0. 排行榜
> >     1. 艺术家
> >     2. 新碟上架
> >     3. 精选歌单
> >     4. 我的歌单
> >     5. 主播电台
> >     6. 每日推荐歌曲
> >     7. 每日推荐歌单
> >     8. 私人FM
> >     9. 搜索
> > ```
> > 没有找到帮助菜单呢？
> > 怎么样可以在程序里显示一个快捷键列表？
> > 现在使用的时候都要打开 readme 看键盘快捷键列表
> > https://github.com/darknessomi/musicbox#%E9%94%AE%E7%9B%98%E5%BF%AB%E6%8D%B7%E9%94%AE
> 
> 我记得好像首页是有个帮助的

用 pip 安装的没有，我下源码安装就有了。

**Comment by mwxxhdb** [comment]
然而下源码安装播放的时候疯狂切换下一曲。。又换回了没帮助的版本。
