### ISSUE TITLE
File /usr/lib64/python27/subprocess.py raise child_exception OSError:No such file or directory

### ISSUE THREAD

**Issue by Kcetry** [darknessomi/musicbox#290]
These keys `j`,`k`,`h`,`l`,is not work well in using,I often confused when I want to go back or ahead.
Also,I could not play music with it,there is still some errors display on the screen.
`File /usr/lib64/python27/subprocess.py   raise child_exception OSError:No such file or directory`

**Comment by zhenruyan** [comment]
找到解决方案了么？

**Comment by kigawas** [comment]
Seems like that's a bug related with Python on your OS

**Comment by fireyyouth** [comment]
I also encountered this problem. solved by install mpg123.

**Comment by MichealRay** [comment]
same problem in raspberrypi 3B？ any clue？

**Comment by MichealRay** [comment]
> same problem in raspberrypi 3B？ any clue？

Oh, Finnally. I solve this problem. The mpg123 is not installed.  After I intall the mpg123, the problem is solved.
