### ISSUE TITLE
怎样让musicbox在后台运行

### ISSUE THREAD

**Issue by seyrenhe** [darknessomi/musicbox#291]
用ssh连接到树莓派后，执行musicbox听歌，连接一断就自动退出了，试了nohup + &不行。。。

**Comment by wu-nerd** [comment]
这个不是后台的问题。
你需要的是tmux。

**Comment by seyrenhe** [comment]
#228 这个问题和我一样，手机没有tmux，也没有screen，只能通过后台运行来解决了

**Comment by wu-nerd** [comment]
是ssh到树莓派，然后在树莓派上开tmux。

**Comment by seyrenhe** [comment]
@wu-nerd 可以 谢谢
