### ISSUE TITLE
musicbox是如何做到正常登录的?

### ISSUE THREAD

**Issue by bieberg0n** [darknessomi/musicbox#292]
在NEMbox目录中运行python

Python 2.7.3
\>>> import api
\>>> netease = api.NetEase
\>>> netease.login('xxxxxx@163.com','xxxx')        #使用自己的帐号

返回 {u'code': 502}

但是运行musicbox,在里面能正常登录,这是怎么做到的?

**Comment by lianxiangru** [comment]
使用魔法 （其实你可以 PyCharm 单步执行一下就知道了

**Comment by disoul** [comment]
并没有什么黑魔法，只是前端对密码做了加密　　　
[见此](https://github.com/darknessomi/musicbox/blob/995b132b1d7320128103688671df3290b471a14d/NEMbox/ui.py#L419)

**Comment by lianxiangru** [comment]
@disoul 加密也是一种魔法！

**Comment by bieberg0n** [comment]
@disoul 谢谢 原来需要把密码进行md5后再login()
wiki的登录API分析需要更新了

**Comment by Wbqqqq** [comment]
@ghost  哥.....pycharm  怎么运行   我运行不起来了....弄了一天..
