### ISSUE TITLE
elegement os 无法运行

### ISSUE THREAD

**Issue by fuowang** [darknessomi/musicbox#295]
安装好所有必需组件之后运行提示这些
但是会弹出已经签到成功的提示。
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/__init__.py", line 20, in start
    nembox_menu.start_fork(version)
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 159, in start_fork
    Menu().start()
                    File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 184, in start
                         self.ui.build_menu(self.datatype, self.title, self.datalist, self.offset, self.index, self.step, self.START)
                                                        File "/usr/local/lib/python2.7/dist-packages/NEMbox/ui.py", line 220, in build_menu
                                                                self.screen.addstr(i - offset + 9, self.startcol, str(i) + '. ' + datalist[i])
                                                               error: addstr() returned ERR

**Comment by fuowang** [comment]
还有这些提示：
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                         SNIMissingWarning
                                                          /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                          InsecurePlatformWarning

**Comment by kigawas** [comment]
ele OS的终端有兼容性问题，准确的说是不能自定义背景颜色之类的。

建议用apt-get安装gnome终端使用。

**Comment by kigawas** [comment]
刚才试了一下，elementary os自带的终端也能运行，
可以尝试更新系统。

**Comment by fuowang** [comment]
非常感谢！
