### ISSUE TITLE
桌面歌词的问题

### ISSUE THREAD

**Issue by AutuanLiu** [darknessomi/musicbox#297]
请问，ubuntu下，桌面歌词怎么搞出来 ❓ 
是否每次启动时，都需要登录 ❓

**Comment by fiepi** [comment]
依据经验来看，你前一次正常退出时电脑处于联网状态，下一次再打开应该可以自动登录成功的

**Comment by AutuanLiu** [comment]
那请问桌面歌词怎么搞出来？[readme](https://github.com/darknessomi/musicbox)提到的依赖，前三个都可以成功安装，但是和桌面歌词有关的那个就不行。求教具体的方法。感激不尽(linux接触不是很久，有些东西还不太熟悉)  !@fiepi

**Comment by kissunyeason** [comment]
我也是，不知道怎么把歌词搞出来 蛋疼 @AutuanLiu

**Comment by ruizhipeng** [comment]
全都手动编译安装 archlinux下直接安装aur中的git版本就可以

**Comment by lianxiangru** [comment]
我也是 arch 啊。。直接就能用

**Comment by ruizhipeng** [comment]
不知 aur的版本我直接安装git 习惯了
