### ISSUE TITLE
修改客户端背景色

### ISSUE THREAD

**Issue by OsmanthusTree** [darknessomi/musicbox#298]
为何会overwrite我的背景色... 
![screenshot from 2016-05-02 15-54-20](https://cloud.githubusercontent.com/assets/16307070/14949606/05020852-107e-11e6-8c18-ec601b3e48c1.png)
![screenshot from 2016-05-02 15-56-26](https://cloud.githubusercontent.com/assets/16307070/14949614/1da2dc38-107e-11e6-86fc-f02f47846990.png)

**Comment by kigawas** [comment]
It's a feature

**Comment by OsmanthusTree** [comment]
On the one hand I am really pleased with your exellent answer.  On the other hand, you just like Microsoft who tells me darkness is one part of the standard...

**Comment by kigawas** [comment]
There are restricted predefined colors such as RED, BLUE,  YELLOW, BLACK, CYAN etc in curses.COLOR_*, the are the same as colors in your ~/.dir_colors or /etc/DIR_COLORS.

Just like you cannot change your dir color freely in shell, our choices of color are limited due to the curses library.

**Comment by OsmanthusTree** [comment]
I am pretty sorry what i just said to you. But I have already changed the terminal profile and the background never changed. And you should know there are lots of terminal that support 256 colors.
That means the terminal can display more than 8 colors(without any restriction)

**Comment by kigawas** [comment]
Definitely terminal can display lots of colors such as **text or background** colors, however, you cannot change color of your **directories** as you want.

Try google "terminal directory color"

**Comment by OsmanthusTree** [comment]
Thanks for your patiently answering ... Time will really solve my problem..
