### ISSUE TITLE
历史通知记录不会自动清除

### ISSUE THREAD

**Issue by fiepi** [darknessomi/musicbox#303]
推送now playing..通知的时候，通知区域所有推送过的通知会保留，不会自动清理。
对比了其他播放器，正常情况下都只保留一条当前播放歌曲在通知区域。
桌面环境：GNOME

**Comment by darknessomi** [comment]
同是 GNOME ，会自动消失。。。。

**Comment by darknessomi** [comment]
后台未读的话，貌似是会有

**Comment by fiepi** [comment]
比如clementine，能始终保持一条正在播放的信息在通知区域，历史播放通知会被自动清除

**Comment by darknessomi** [comment]
用的不是 libnotify-bin 吧，待我看看

**Comment by Sam0523** [comment]
https://pypi.python.org/pypi/notify2
这个怎么样
