### ISSUE TITLE
小部分歌曲无法播放

### ISSUE THREAD

**Issue by Ping-timeout** [darknessomi/musicbox#306]
版本0.2.2.3，处于帐号登录状态，拿Aimer做测试……比如这首Last stardust，播放的话界面就会闪一下，出现下面这样的画面，然后消失。
![_2016-05-04_05-22-27](https://cloud.githubusercontent.com/assets/17251660/15014300/d4a998c6-1237-11e6-94a6-ba09a9ad5c78.png)
这首曲子用搜索歌曲名可以搜到，搜索艺术家Aimer进去有时是看不见的，有时又出现了，但也不能播。
拿ClariS测试也能碰见好多。
也不知道是不是我自己的问题，又或者是API的锅。

**Comment by fiepi** [comment]
版权歌曲，不能播放。。。不信你在网页版查看这首歌曲，是灰色的限制播放

**Comment by darknessomi** [comment]
即将修复崩溃，但听不了我也没办法╮(╯_╰)╭
