### ISSUE TITLE
无法隐藏歌词窗口标题栏

### ISSUE THREAD

**Issue by chopins** [darknessomi/musicbox#321]
我的环境版本如下：

* OS: Fedora 23
* Gnome 3.18.2
* gnome-shell-3.18.5
* PyQt4-4.11.4
* Python 2.7.11

开启显示歌词后会存在标题栏。
我没怎么详细研究解决这个问题，我只是通过在文件`NEMbox/osdlyrics.py`，增加`self.setWindowFlags(QtCore.Qt.CustomizeWindowHint|QtCore.Qt.WindowStaysOnTopHint)` 来隐藏标题（窗口移动使用Alt+鼠标左键）。

**Comment by kigawas** [comment]
![image](https://cloud.githubusercontent.com/assets/4182346/15102893/8e063192-15d7-11e6-93ea-c43a47114920.png)
没懂。你是要隐藏1还是2？

**Comment by chopins** [comment]
这个修改只对0.2.2.1有效
