### ISSUE TITLE
超长歌名如果出现在列表最后一行，异常换行+滚动

### ISSUE THREAD

**Issue by fiepi** [darknessomi/musicbox#323]
正常情况下，如果显示宽度不够，不换行的情况下，选中的歌曲名会以滚动形式显示。
现有一个异常，如果列表最后一行的歌曲名超过了终端宽度，就会自动换行，并且移动光标选中该行后，这行包括换行后的下一行的歌名就会一起滚动，然后头接尾全乱了。。。
既然换行了，歌名已经完全显示，已经没必要滚动，或者不换行滚动。理想状态应该是不换行。

**Comment by Catofes** [comment]
Fixed

**Comment by fiepi** [comment]
@Catofes  顶部当前正在播放的歌曲标题能否也实现不换行并滚动显示呢？

**Comment by fiepi** [comment]
或者换行后的第二行对齐第一行的第一个音乐符号，前面留点空间，看起来协调些
