### ISSUE TITLE
archlinux上所有歌曲都会自动快进

### ISSUE THREAD

**Issue by yangxuan8282** [darknessomi/musicbox#328]
OS: archlinux arm
大概从 **0.2.2.3** 版本开始，选中一首歌后会自动快进30s左右才能正常播放
一直到今天的 **0.2.2.10** 版本还是这样，重新安装也不能解决
同样的版本在Debian(raspbian)上是正常的，不知道是不是新API的问题
查看log没发现相关报错

**Comment by kigawas** [comment]
先试试用mpg123播放音乐会不会快进。

**Comment by yangxuan8282** [comment]
@kigawas 试了一下，确实应该是mpg123的问题，版本是 **1.22.4**

**Comment by yangxuan8282** [comment]
编译安装了最新的mpg123 1.23.4还是会自动快进，不知道该怎么办了

**Comment by yangxuan8282** [comment]
看了mpg123的这个[bug](https://sourceforge.net/p/mpg123/bugs/224/)发现是pulseaudio原因，卸载之后就正常了

**Comment by yangxuan8282** [comment]
卸载pulseaudio是临时解决办法
后来发现要想mpg123在已安装pulseaudio前提下工作，需要安装 gstreamer0.10-good-plugins 

    gstreamer0.10-good-plugins (optional) - for OSS and PulseAudio support
