### ISSUE TITLE
无法播放呀

### ISSUE THREAD

**Issue by toddlerya** [darknessomi/musicbox#33]
nice

**Comment by darknessomi** [comment]
详细描述一下？

**Comment by toddlerya** [comment]
好了好了，是我蠢了，木有看到播放快捷键，给32个赞


来自 魅族 MX3

-------- 原始邮件 --------
发件人：ZHANG RT <notifications@github.com>
时间：周二 2月10日 18:20
收件人：darknessomi/musicbox <musicbox@noreply.github.com>
抄送："Allen.Guo" <toddlerya@gmail.com>
主题：Re: [musicbox] 无法播放呀 (#33)
