### ISSUE TITLE
lrc歌词怎么下载？

### ISSUE THREAD

**Issue by fancyerii** [darknessomi/musicbox#330]
我看代码，应该是下面这样的格式：
http://music.163.com/api/song/lyric?os=pc&id=29431066&lv=-1&kv=-1&tv=-1

我直接wget或者用浏览器打开，返回403。

**Comment by arrowrowe** [comment]
需要设置 `REFERER: http://music.163.com/`.

**Comment by fancyerii** [comment]
it works, thank you.
