### ISSUE TITLE
新版登陆API疑问

### ISSUE THREAD

**Issue by tskshy** [darknessomi/musicbox#332]
@darknessomi 
你好 我用api.py -> encrypted_request生成的请求参数({'params':xx, 'encSecKey': xx})
然后模拟登陆请求http://music.163.com/weapi/login
得到的结果始终是 {code: 502}的提示

但是用浏览器截取的参数可以正常模拟登陆
能得到用户相关信息

**Comment by Catofes** [comment]
可能和UA有关

**Comment by tskshy** [comment]
找到原因了 password没有md5 😓
