### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by adminzhou** [darknessomi/musicbox#333]
Command "/usr/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-dCAj1H/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-yievDb-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-dCAj1H/pycrypto/

**Comment by kigawas** [comment]
安装Pycrypto的问题...

**Comment by Amehinou** [comment]
Apt-get install python-dev
