### ISSUE TITLE
我擦。Linux版！

### ISSUE THREAD

**Issue by Catofes** [darknessomi/musicbox#336]
http://www.cnbeta.com/articles/504523.htm

**Comment by Catofes** [comment]
arch 依赖太新。。好烦

**Comment by shiywang** [comment]
一看deepin,估計是用wine做的吧......

**Comment by Catofes** [comment]
no 原生的

**Comment by chaserhkj** [comment]
试了下感觉还可以…没有wine的版本右键不能的问题…
arch下面我就手动装了个libcue1.4就能跑了
然而感觉还是musicbox的命令行比较符合我的哲学=w=(拖走

**Comment by chaserhkj** [comment]
可惜不是开源的…不过这样以后反工API更方便了呢（

**Comment by Catofes** [comment]
我这边openssl报错 什么版本不对神马的。。。怎么解决？

**Comment by Catofes** [comment]
@chaserhkj 你用的是哪个版本？

**Comment by Catofes** [comment]
哦 现在是网络报错。。。

**Comment by chaserhkj** [comment]
@Catofes 我这边openssl没有任何报错啊
ldd了一下就差一个libcue.so.1装上就行了

**Comment by Catofes** [comment]
@chaserhkj 恩 我错了。 不过你那边能听歌嘛？ 我一直说网络错误

**Comment by chaserhkj** [comment]
@Catofes 我听在线歌曲没有问题
但是我尝试把我的flac曲库导入本地，然后它out of memory了。。。。

**Comment by Catofes** [comment]
@chaserhkj  我这边在线报错。。。不明。。。代理的过？

**Comment by Catofes** [comment]
好吧呀  貌似是libcue的过。。。

什么鬼！

**Comment by Catofes** [comment]
啊 并不是。。。还在报错， 一部分的曲子可以听， 不少不可以

**Comment by Catofes** [comment]
。。。貌似不是用ALSA输出的。 声音好多问题。。。。云盘的曲子貌似无法播放。。。

**Comment by Catofes** [comment]
哦 是GPU加速的锅。。 居然还会影响到输出

**Comment by chaserhkj** [comment]
@Catofes 这货好像漏内存漏的有点吓人啊……和本地音乐没什么关系
我裸开什么都不做就这样了

![screen](https://cloud.githubusercontent.com/assets/1768423/15535005/15832e36-229e-11e6-9896-c4787184d349.png)

内存占用一直涨着而且有个线程一直100%占用
你那有这情况么 = =

**Comment by Catofes** [comment]
我这边没有。 

不过我这边木法播放mp3 的文件。。。。哪个库有问题吗。。。

**Comment by Sam0523** [comment]
貌似只有 deb 包？

**Comment by arrowrowe** [comment]
大家折腾好了么...... 用 Wine 开 Windows 版的表示体验良好.........

**Comment by chaserhkj** [comment]
@Catofes 我发现不能从它自己的目录以外的pwd启动它……否则就会吃内存233333

**Comment by hxhc** [comment]
Mint 17.3 表示内存占用大概300M不到（还是有点高啊），CPU占用1.52%
目前一切良好

顺便， pip uninstall NetEase-MusicBox 不能删除吗 = =
> Can't uninstall 'NetEase-MusicBox'. No files were found to uninstall.

**Comment by Catofes** [comment]
为啥我的就不能播放MP3格式的音乐呢。。。。。。缺啥库了啊

**Comment by mingyumu** [comment]
哈哈！以后liunx不用再一直听网页版的了

**Comment by chaserhkj** [comment]
@Catofes 我这好像也不能放本地MP3……不过网易的在线流不应该都是mp3的么？没理由是解码问题吧……
嘛，不过我的本地音乐基本都是flac所以应该都大丈夫（

**Comment by retaw106** [comment]
表示deepin上木有楼上的任何问题，内存135M左右，哈哈

**Comment by Catofes** [comment]
好吧呀  感觉是 chrome 的锅？

**Comment by ikzk** [comment]
让我们更方便地肝 API

**Comment by kigawas** [comment]
Fedora用户表示没有看到rpm😂

**Comment by Catofes** [comment]
https://github.com/archlinuxcn/repo/blob/master/netease-cloud-music/PKGBUILD 

唔， 果然是openssl的过。

**Comment by hlx98007** [comment]
Fedora 用户表示直接装deb和配套openssl版本等的，网易官方linux 会奔溃

**Comment by zinechant** [comment]
@Catofes 你是在国外吗，我使用公司的局域网（加州IP）就是一直网络错误。

**Comment by cleardusk** [comment]
Mint 17.2，网易云貌似只要网络不好就会崩溃...
还是用 musicbox 频率更多哈哈，cli 很方便呀！

**Comment by yangwangjinxing** [comment]
有些时候前10s左右会一卡一跳（3-4s后进度条就到10+s了），网络原因？不像。

**Comment by shutup** [comment]
我的是kali2016.2 ,我尝试安装了官方版本没啥大问题啊，就是依赖处理比较麻烦。。。

**Comment by sheacoding** [comment]
还有网易和深度合作推出的网易云音乐Linux官方版呢 
------------------ Original ------------------
