### ISSUE TITLE
网易云音乐有Linux版的了

### ISSUE THREAD

**Issue by godfather1103** [darknessomi/musicbox#338]
网易云音乐出Linux版了；
![qq 20160526234146](https://cloud.githubusercontent.com/assets/11797964/15580487/816cdf36-239b-11e6-8783-8a6d94f6f3b5.png)

链接;[music.163.com/#/download](music.163.com/#/download)

**Comment by Catofes** [comment]
#336

**Comment by Catofes** [comment]
#336
