### ISSUE TITLE
请问大牛下架的歌曲能下载吗（编程也行）

### ISSUE THREAD

**Issue by fancyerii** [darknessomi/musicbox#342]
比如获取音乐“任贤齐的心太软”的信息：
http://music.163.com/api/song/detail/?id=144145&ids=%5B144145%5D
mp3Url和bMusic,hMusic什么的都是null，还有别的接口能搞到下架的歌曲的mp3吗？

**Comment by kigawas** [comment]
:joy: 我们也想能啊。。。

**Comment by fancyerii** [comment]
http://music.loadfield.com/song
找到了这个网站，好像他们缓存了一些。我把9万多首下架的url存了下来。

**Comment by metowolf** [comment]
反查专辑就可以获得 hMusic
