### ISSUE TITLE
新版API     rsaEncrypt 这个函数 看不太懂

### ISSUE THREAD

**Issue by huweigoodboy** [darknessomi/musicbox#349]
新版API https://github.com/darknessomi/musicbox/wiki/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E6%96%B0%E7%89%88WebAPI%E5%88%86%E6%9E%90%E3%80%82  rsaEncrypt 这个函数  看不太懂
如果加密算法 用 java实现就完美了

**Comment by huweigoodboy** [comment]
好像有点伸手党 不过有人能帮忙 解释一下也可以

**Comment by metowolf** [comment]
我用 PHP 实现了，语法应该比较接近 Java，你可以看看 [网易云音乐API分析（v2）](https://github.com/metowolf/NeteaseCloudMusicApi/wiki/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90API%E5%88%86%E6%9E%90%EF%BC%88v2%EF%BC%89#3-rsa-%E5%8A%A0%E5%AF%86)

**Comment by huweigoodboy** [comment]
@metowolf  非常感谢   通过你的代码  我已经 实现了  生成那两个参数  但是很奇怪 我用python 去访问http://music.163.com/weapi/song/enhance/player/url这个地址是成功的，比如参数如下

{
    'params': 'SRKwLUX6J6g3kC+odZu1jTSZF62KqjClRVKgGkRSw+ZJej0S2wjPk//7vq7MSFB6',
    'encSecKey': 'd7e206d833bcbdb7d46cebf147f3143887fb70294124737362cd927c902b7216f7e5a0d6fc1986534b0c7a314f51c0784aa67d4b29fbc411c38da8a047d4e0e5d8cf62e042695f8fd0b53fe4ac03604e553c7e0be9c503f4873833bf5370da94bd667a6275461e6728eeedb96bd580ce44312df4ca30f083a1879c80919520d4',
}，但是在postman和android 上 请求，报{"msg":"参数错误","code":400}

**Comment by kigawas** [comment]
@huweigoodboy 
Referer设置成music.163.com试试

**Comment by huweigoodboy** [comment]
@kigawas    Referer设置成music.163.com 连普通接口 都不能访问了 下面是请求的具体内容

POST /api/song/enhance/player/url HTTP/1.1
Cookie	; appver=1.2.1os=osx
Host	music.163.com
Referer	http://music.163.com/
User-Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36
Connection	keep-alive
Content-Type	application/x-www-form-urlencoded
Content-Length	338
Accept-Encoding	gzip


encSecKey=ac8bb9680b4b96526a65b20df56bbaae0c1f2a26e94044b53466415ac11c39ed1b7a4c9eeacdf49abf8a33465426c771b97e65d258c6600c3af4dd9a8e016b5168a5520360c6abeb890ef2cf2acc1943a50c9a4a7fc52a3e526040fb413e3234e3a25e08f61cc929c37ca0ffeb9cecad1b5bbc0fca21bbcc14729247226b4d7c&params=zgAFoNJZjvunHTNbLoitVSnKiY50xJiC4pKppvl0nyH4UXBra97pUKDHzzdascV4

**Comment by huweigoodboy** [comment]
@kigawas   我看看 把请求贴出来的时候 发现是我的 地址拼错了  应该是http://music.163.com/weapi  开头


但是现在返回的json串又没url，同样的参数 python上面是有的 ，我再仔细看看。
{"data":[{"id":26117507,"url":null,"br":0,"size":0,"md5":null,"code":404,"expi":1200,"type":null,"gain":0.0,"fee":0,"uf":null,"payed":0,"flag":0,"canExtend":false}],"code":200}

**Comment by huweigoodboy** [comment]
@kigawas 

谢谢你的回答    我用wireshark 仔细比对了 请求 ，发现我的cookie拼接有问题。 问题解决了。

python
 ************************************

 POST /weapi/song/enhance/player/url HTTP/1.1
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36
Accept-Encoding: gzip, deflate
Cookie: os=osx; appver=1.2.1
Accept: */*
Content-Length: 342
Referer: http://music.163.com/
Host: music.163.com

encSecKey=d0278ae97496709cf34ccee7a8204241a088f2e0e98b26a73a3853cebec940e4bff6d452ae2d750ba95579d7013cd4693ef54a548773cca50b68c34fe1cd754198f464a9d4d961a6079db9dbb204c8a686fa6159734c0576229331bfb978a07f57cc6dedb154208025a1368affdaf2cacd46b208e3182a17395a0dc2d0862a5a&params=93XErL6YSWSZ1hoIKzj1u87%2B9swpHlvnvLegTSivWrFxUZLknDeKMG7%2B9ZFUiaPw


*****************


Android

*******************
POST /weapi/song/enhance/player/url HTTP/1.1
Cookie: ; appver=1.2.1os=osx
Host: music.163.com
Referer: http://music.163.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded
Content-Length: 340
Accept-Encoding: gzip

encSecKey=79d4bbd4b15cd2016b831b8f3a59a0cebdd32285ac536e47a56a867b39ae409bc7278b42d1b0ef1f0cdb65ff1c9794c63d411ec141a005ba379011c5643beaeb698573966eaa29c5452d8002668451bfb0759684269f5b251d02a5eb064a1dbf77b15ce0d4a58b7a6f93b1a30719fb877865bda1006bcb96f6d16117a290a5ac&params=%2FqiOpYWATx9CMTcYbNBYM1lLqQvqmcLdSuGtqYW3S7JuzkCzZmZ52kTFKHAQoMRp

*************************
