### ISSUE TITLE
请教一下关于 cookies 的问题

### ISSUE THREAD

**Issue by xiahei** [darknessomi/musicbox#350]
您好，拜读了您的代码在代码里面找相关的内容，想要获取登录后的`set-cookie`项，在 `api.py` 里面 `NetEase` class 类似的处理，登录成功，但是在保存的 cookies 文件里依然没有`Set-Cookie`项，只有`#LWP-Cookies-2.0`一行，请问您能指点指点？
大概就是这么写：
![](http://ww2.sinaimg.cn/large/005NaGmtjw1f5nl9w08q0j30n404vjsk.jpg)

**Comment by kigawas** [comment]
cookie在`~/.netease-musicbox/cookie`

**Comment by xiahei** [comment]
@kigawas 想知道的是怎么获取它。

**Comment by kigawas** [comment]
https://github.com/darknessomi/musicbox/blob/master/NEMbox/api.py#L226
