### ISSUE TITLE
不支持socks5代理

### ISSUE THREAD

**Issue by xiaod0510** [darknessomi/musicbox#352]
请问如何支持socks5代理  目前貌似是通过mpg123 的-p 参数实现的 但是我没找到mpg123如何使用socks5.
这个功能能不能加上 ^_^

**Comment by htfy96** [comment]
```
export all_proxy=socks5://XXX
musicbox
```
不知道行不行

**Comment by kigawas** [comment]
http://superuser.com/questions/423563/convert-http-requests-to-socks5
