### ISSUE TITLE
字符界面下mpg123奔溃

### ISSUE THREAD

**Issue by lirawx** [darknessomi/musicbox#353]
纯字符界面下mpg123奔溃，导致播放速率加快.
运行环境ubuntu16.04

**Comment by kigawas** [comment]
怎么重现？

**Comment by lirawx** [comment]
关掉图形界面之后进入tty，运行musicbox，然后随便选一首歌播放就会出现了。我用alsamixer调节音量的大小之后，可以完整的听一首歌，但是下一首歌曲就不行了。

**Comment by kigawas** [comment]
https://github.com/darknessomi/musicbox/issues/362
