### ISSUE TITLE
如何修改音质

### ISSUE THREAD

**Issue by redapple0204** [darknessomi/musicbox#356]
默认的最高音质太蛋疼，我的网速很慢，听起来一卡一卡的

**Comment by kigawas** [comment]
shift c下载下来听:joy:

**Comment by redapple0204** [comment]
@kigawas 下一首要等个十多分钟

**Comment by silenceu** [comment]
修改~/.netease-musicbox/config.json里面的"music_quality"参数，默认的是0(320kbit/s),另外可以设置成1(192Kbits)或者2(128kbit/s)

**Comment by redapple0204** [comment]
@silenceu 非常感谢，这起作用了。

**Comment by redapple0204** [comment]
@silenceu 顺便请问下载的音质如何更改，默认的也吃不消==

**Comment by silenceu** [comment]
`这个倒是不清楚，我一直都是在线使用，你确定修改音质后下载下来的还是302K的？
可以进~/.netease-musicbox/cache文件夹，mpg123 歌名，在命令行看看下载下来是什么音质的

2016-07-31 21:46 GMT+08:00 redapple0204 <notifications@github.com>:

**Comment by redapple0204** [comment]
@silenceu 我看了下，确实是302k的
