### ISSUE TITLE
为什么不支持window？？？

### ISSUE THREAD

**Issue by lilySnian** [darknessomi/musicbox#363]
好像要window版啊，求window版。。。。。

**Comment by kigawas** [comment]
win10不是里面自带一个Ubuntu么:joy:

**Comment by lilySnian** [comment]
我还在用win8
win10一堆bug
 
 
------------------ Original ------------------

**Comment by kigawas** [comment]
:joy:不支持Windows的原因主要是一些库不能在Windows下正常工作

**Comment by lilySnian** [comment]
好吧，5555555555~~~~~~

**Comment by kigawas** [comment]
换Mac（逃
