### ISSUE TITLE
不支持 Python3？

### ISSUE THREAD

**Issue by heramerom** [darknessomi/musicbox#364]
Python3下面有错误，是不支持吗？

**Comment by kigawas** [comment]
https://github.com/darknessomi/musicbox/tree/python3

**Comment by heramerom** [comment]
你好，
python3上还是有问题，
我切换到```python3```分支
然后运行
```
 python setup.py install
```
好几个文件报```print```格式错误，
改过print后可以安装但是运行的时候出现
```
No module named '_curses'
```
错误。不知道为什么，我用的是```pyenv```难道这样不行吗？

**Comment by kigawas** [comment]
不要运行setup.py，直接python -m NEMbox.__init__
curse是Python用来操作命令行的标准库，如果这里有问题重新安装一个环境

**Comment by heramerom** [comment]
按照网上curse库是装过的。但是还是不行，可能是因为我用pyenv的问题。

**Comment by kigawas** [comment]
建议使用virtualenv

**Comment by heramerom** [comment]
好的，我试一下。

**Comment by Wbqqqq** [comment]
@kigawas   哥....如何在pycharm上 运行  我想单步调试下 学习学习  但是命令行可以起来  pychram怎么都起不来  如果是运行init.py   报ModuleNotFoundError: No module named '__main__.menu'; '__main__' is not a package    很痛苦   弄了一晚上...
