### ISSUE TITLE
在macOS 歌曲无法播放

### ISSUE THREAD

**Issue by TaylorHere** [darknessomi/musicbox#367]
![2016-08-20 21 23 56](https://cloud.githubusercontent.com/assets/12156543/17831487/8dcba9e6-671c-11e6-9968-780a25df24be.png)

**Comment by kigawas** [comment]
mpg123装了么

**Comment by TaylorHere** [comment]
刚刚看了一下，mpg123安装不成功提示c编译器不能运行，应该是macOS的原因吧

**Comment by kigawas** [comment]
建议用homebrew装
