### ISSUE TITLE
作者是不是有网易云内部的人啊，各个接口的传参规则是怎么知道的呢

### ISSUE THREAD

**Issue by moyuyc** [darknessomi/musicbox#369]
莫非是看着压缩混淆后的js破解的吗

**Comment by U2FsdGVkX1** [comment]
网上不是都有API文档了吗……直接搜一下“网易云音乐 API”就是一大堆

**Comment by moyuyc** [comment]
网上其他的大都是没改版前的，没有加密的，抓包就能分析出来了，但新版加密后的，你抓包后也分析不出来，除非你直接读的压缩后的js代码，或者你是内部的人，知道网易云音乐服务器端的另一个密钥是什么

**Comment by Catofes** [comment]
就是读压缩代码。 当时弄了一下午吧。

**Comment by metowolf** [comment]
可以读出来的，再着错误参数接口也会提示。

**Comment by gao-lex** [comment]
但是您是怎么知道要加密的text的呢？？
加密规则可以在js代码中找到，
但是加密前的数据,比如：
```
text = {
    'username': '邮箱',
    'password': '密码',
    'rememberLogin': 'true'
}
```
是怎么知道的呢？？非对称加密，应该不是自己解开的把？？很疑惑

**Comment by moyuyc** [comment]
@gao-lex  text 也是通过 js 加密后  ajax 发过去的

**Comment by sssir** [comment]
@gao-lex 同问，很好奇text是怎么找到的。
