### ISSUE TITLE
如何使用桌面歌词

### ISSUE THREAD

**Issue by redapple0204** [darknessomi/musicbox#371]

**Comment by kigawas** [comment]
`config.py`里面有选项

**Comment by Sherlock-Holo** [comment]
咱在config.json里面把所有跟osd的都改成true了，然后打开osd lyrics，它显示客户端为xmms2,自动变成这个的，但是咱不知道如何开启桌面歌词，osd右键他搜索歌词也没有东西，如果是其他播放器会显示当前播放的歌名
