### ISSUE TITLE
i3wm中无法正常播放

### ISSUE THREAD

**Issue by yanpan9** [darknessomi/musicbox#374]
在i3wm中,播放歌曲时前30秒左右的歌曲会变成杂音,且时间一跳就是几秒.但是开了alsamixer后,就可以正常播放.

**Comment by kigawas** [comment]
应该是mpg123调用系统API播放的问题

**Comment by Yuan-Hang** [comment]
这个问题怎么解决呢？只能一直把alsamixer开启吗？

**Comment by csbde** [comment]
同样问题，无法解决
               +                OS: Arch Linux x86_64
               #                Hostname: SimonLaptop.computer
              ###               Kernel Release: 4.7.6-1-ARCH
             #####              Uptime: 1:04
             ######             WM: Awesome
            ; #####;            DE: None
           +##.#####            Packages: 1456
          +##########           RAM: 1932 MB / 15753 MB
         #############;         Processor Type: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
        ###############+        $EDITOR: vim
       #######   #######        Root: 49G / 78G (62%) (ext4)
     .######;     ;###;`".      
    .#######;     ;#####.       
    #########.   .########`     
   ######'           '######    
  ;####                 ####;   
  ##'                     '##   
 #'                         `#

**Comment by kelvinh** [comment]
遇到同样的问题，Ubuntu16.04 + i3-wm + urxvt，使用pip install安装的。

看了.netease-musicbox/musicbox.log，有大量的这种错误：
ERROR - NEMbox.player:464: list index out of range

不知道跟这个有没有关系？

**Comment by kigawas** [comment]
@kelvinh 其他终端能播放吗？

**Comment by kelvinh** [comment]
@kigawas 谢谢及时回复。

又研究了一会儿，发现在终端下，用mpg123本身放的时候也是，概率性地会变成杂音并且快进（概率非常大），加上-v参数也没发现有什么错误输出，怀疑是mpg123内部不明bug，google搜索也没有什么有用结果。

但我从 https://github.com/darknessomi/musicbox/issues/160 这个issue里找到了解决办法，给mpg123加上-b参数可以解决这个问题，试过多次，完全不会再出现杂音。

解决方法：在**~/.netease-musicbox/config.json**中，将`mpg123_parameters`的`value`改为：`["-b", "1"]`即可。看mpg123的文档，要求-b参数最小为1024，不然没什么用，但实测填1024播放刚开始会有较长时间的空白，所以只填1来绕过这个杂音的bug即可。希望以上能帮到后续遇到这个问题的朋友。

PS：非常nice的project，谢谢你们的great work!

**Comment by csbde** [comment]
感谢 @kelvinh  根据你的方法修改value值为 ["-b", "144"] 解决了这个问题。

实际上在其它终端下直接使用 mpg123播放 mp3也会出现同样的快进杂音问题。

但是在gnome下不会有任何问题，包括在gnome下的终端用mpg123 也不会出现问题，所以在gnome下使用musicbox 是不会出现快进杂音问题的。

**Comment by kigawas** [comment]
Thanks。反馈内容已经加入readme

**Comment by liaowang11** [comment]
以前没这个问题,今天升级就出现这个问题了...

**Comment by WooHooDai** [comment]
感谢@kelvinh的解决方法
不过设置-b设置成1没有效果，倒是设置成1024正常了，而且播放开始没有空白
所以其他遇到相同问题的可以两个值都试试

**Comment by peterzky** [comment]
如果使用的是PulseAudio的话会出现这样的问题，可以使用 ./configure --with-audio=pulse 重新编译mpg123
https://bugs.launchpad.net/ubuntu/+source/mpg123/+bug/1585926

**Comment by unstartdev** [comment]
@peterzky 也可安装osspd

**Comment by mfk530** [comment]
可以使用参数["-o", "pulse"]，解决杂音快进以及进程无法关闭导致多个mpg123进程的情况，archlinux实测

**Comment by zhang-wenchao** [comment]
向上游报告吧
https://bugs.launchpad.net/ubuntu/+source/mpg123/+bug/1585926

**Comment by itgoyo** [comment]
> @kigawas 谢谢及时回复。
> 
> 又研究了一会儿，发现在终端下，用mpg123本身放的时候也是，概率性地会变成杂音并且快进（概率非常大），加上-v参数也没发现有什么错误输出，怀疑是mpg123内部不明bug，google搜索也没有什么有用结果。
> 
> 但我从 #160 这个issue里找到了解决办法，给mpg123加上-b参数可以解决这个问题，试过多次，完全不会再出现杂音。
> 
> 解决方法：在**~/.netease-musicbox/config.json**中，将`mpg123_parameters`的`value`改为：`["-b", "1"]`即可。看mpg123的文档，要求-b参数最小为1024，不然没什么用，但实测填1024播放刚开始会有较长时间的空白，所以只填1来绕过这个杂音的bug即可。希望以上能帮到后续遇到这个问题的朋友。
> 
> PS：非常nice的project，谢谢你们的great work!

牛逼呀，解决了我i3wm，打开音乐时候的杂音问题

**Comment by cike2056** [comment]
> 如果使用的是PulseAudio的话会出现这样的问题，可以使用 ./configure --with-audio=pulse 重新编译mpg123
> https://bugs.launchpad.net/ubuntu/+source/mpg123/+bug/1585926

debian10,i3wm,治标治本
