### ISSUE TITLE
Python 2 和 3 支持

### ISSUE THREAD

**Issue by kigawas** [darknessomi/musicbox#379]
#378 
花了半个周末让Python 3分支兼容Python 2，顺便修复几个问题，目前在终端下没发现什么问题（桌面歌词还没仔细测试）

@darknessomi 
@Catofes

**Comment by kigawas** [comment]
@darknessomi #381 
hotfix 需要更新pypi 😄 
（能让pypi自动用master分支嘛）

**Comment by darknessomi** [comment]
hotfixed

**Comment by darknessomi** [comment]
可以写个自动发布脚本

**Comment by kigawas** [comment]
@darknessomi Fix #382

**Comment by darknessomi** [comment]
@kigawas OK, Happy Mid-autumn Day
