### ISSUE TITLE
請把 src 重命名爲有意義的包名

### ISSUE THREAD

**Issue by farseerfc** [darknessomi/musicbox#38]
比如參考 https://github.com/LiuLang/kwplayer 他們的包名叫 kuwo 。
按目前的方式，雖然 python2 setup.py install 是對的，但 pip2 install 是錯的，會把包安裝在類似
/usr/lib/python2.7/site-packages/src/menu.py 這樣的路徑。
同理，目前archlinux沒法爲這個項目打包。

**Comment by darknessomi** [comment]
多谢提醒，已修复

**Comment by farseerfc** [comment]
讚修復速度！

**Comment by farseerfc** [comment]
https://aur.archlinux.org/packages/netease-musicbox/
已爲archlinux打包

https://github.com/archlinuxcn/repo/tree/master/netease-musicbox
並已加入archlinuxcn中文社區源

**Comment by darknessomi** [comment]
多谢！
