### ISSUE TITLE
话说桌面歌词非得要pyqt5么

### ISSUE THREAD

**Issue by redapple0204** [darknessomi/musicbox#384]
qt4不行？表示debian7没法装qt5,而且pip install PyQt5也不行。

**Comment by kigawas** [comment]
安装miniconda，然后conda install pyqt4

**Comment by redapple0204** [comment]
@kigawas qt4也可以？

**Comment by kigawas** [comment]
我们用的就是pyqt4啊...

**Comment by redapple0204** [comment]
@kigawas 1.我还以为是qt5.....
2.这个东西源里没有？

**Comment by kigawas** [comment]
pyqt依赖qt的二进制文件，安装方式不是pip。miniconda是Python的二进制包管理工具，可以避免浪费时间手动下载源代码编译。
