### ISSUE TITLE
请问可以加入电台功能吗

### ISSUE THREAD

**Issue by hoyho** [darknessomi/musicbox#39]
电台和每日推荐是网易云必不可少的功能，不知能不能加进去

**Comment by chaserhkj** [comment]
我准备在 chaserhkj:cloud 这个分支上开始写对包括编辑歌单，收藏歌单，新建歌单，播放和收藏电台等比较全面的云音乐功能。因为是个比较大的工程所以另外开了一个分支做……做完以后再merge进主代码库什么的……
