### ISSUE TITLE
last.fm support

### ISSUE THREAD

**Issue by muzikmoe** [darknessomi/musicbox#390]
please add last.fm support

**Comment by kigawas** [comment]
Thanks for your advice, but this program's name is  *netease*-muisicbox, so we'll not do this.

If you'd like, you can try https://github.com/hugovk/lastfm-tools

**Comment by muzikmoe** [comment]
Thank for reply. you know last.fm is an online music catalog with music, so I mean send the listening record to last.fm when I am using netease-musicbox, add the function into musicbox just like the last.fm plugin for VLC player or some last.fm Chrome extensions.
