### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by CigarZh** [darknessomi/musicbox#391]
ubuntu16.04

$pip install NetEase-MusicBox   
Collecting NetEase-MusicBox
  Using cached NetEase-MusicBox-0.2.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-KcitPr/NetEase-MusicBox/setup.py", line 40, in <module>
        from future import standard_library
    ImportError: No module named future
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-KcitPr/NetEase-MusicBox/

**Comment by kigawas** [comment]
先`pip install future`
