### ISSUE TITLE
安装成功，运行music box 报错：pkg_resources.DistributionNotFound: BeautifulSoup4

### ISSUE THREAD

**Issue by huangbqsky** [darknessomi/musicbox#392]
报错：
   raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: BeautifulSoup4

但是 BeautifulSoup4已经安装
Requirement already satisfied (use --upgrade to upgrade): BeautifulSoup4 in /Library/Python/2.7/site-packages

**Comment by kigawas** [comment]
重装bs4试试
