### ISSUE TITLE
ImportError: No module named future

### ISSUE THREAD

**Issue by kouunn** [darknessomi/musicbox#394]
`[~] kou2n$ sudo -H pip install NetEase-MusicBox
Collecting NetEase-MusicBox
  Using cached NetEase-MusicBox-0.2.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-jKmWNb/NetEase-MusicBox/setup.py", line 40, in <module>
        from future import standard_library
    ImportError: No module named future
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-jKmWNb/NetEase-MusicBox/`

**Comment by kigawas** [comment]
pip install future

Will fix this in next version

**Comment by kouunn** [comment]
@kigawas Thank you！
