### ISSUE TITLE
某一次滚过系统就变成这样了

### ISSUE THREAD

**Issue by fiepi** [darknessomi/musicbox#398]
之前一直是正常使用的，更新过后变成这样 不知是系统更新的缘故还是 musicbox 更新的缘故
似乎是不能正确处理键盘指令 键盘的输入在下方的光标显示 但是 musicbox
无任何相应 只能ctlr+c退出 
系统arch 通过aur安装
https://youtu.be/Pzepw8qiqOY

**Comment by kigawas** [comment]
先试试最新版，有可能修复了这个问题
pip install https://github.com/darknessomi/musicbox/archive/master.zip

**Comment by fiepi** [comment]
@kigawas 这个键盘没问题 不过不能联网。。

**Comment by fiepi** [comment]
多次尝试发现 使用python2，键入无效；使用python3，无法联网。

**Comment by kigawas** [comment]
检查一下使用mpg123是否能直接播放URL地址

**Comment by fiepi** [comment]
@kigawas 
直接 mpg123 history.mp3 这样可以播放本地文件，播放不了HTTP URL。这个 HTTP URL 直接放到 Chrome 浏览器里可以播放。
```
$ mpg123 http://localhost/history.mp3  
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.23.6; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes
HTTP request failed: 502 No data received from server or forwarder
main: [src/mpg123.c:709] error: Access to http resource http://localhost/history.mp3 failed
```

**Comment by fiepi** [comment]
mpg123没问题。musicbox的问题依旧——使用python2，键入无效；使用python3，无法联网。

**Comment by kigawas** [comment]
Python3不能联网有错误信息吗？
看看requests装了没

**Comment by fiepi** [comment]
@kigawas 
很感谢。重新走了一遍依赖， python3 下已经ok了。
可能是依赖包多次升级有残留，删除 /usr/lib/python3.5/site-packages/ 下的一些残留文件重新安装依赖包就解决了
已安装的 dependencies:
mpg123
python-setuptools
python-requests
python-crypto
aria2
python-keybinder
