### ISSUE TITLE
一直提示 you need login

### ISSUE THREAD

**Issue by lwjcjmx123** [darknessomi/musicbox#399]
如题，我登陆了还是会提醒

**Comment by lwjcjmx123** [comment]
系统 ubuntu 16.04 能正常使用。

**Comment by kigawas** [comment]
检查`~/.netease-musicbox/cookie`

**Comment by lwjcjmx123** [comment]
自己down了一份源码，把api.py 里的notifier “you need login” 那两行删除掉然后安装后就不会有这个提示了。因为一直登陆不了，还总是提示登陆
