### ISSUE TITLE
there is a problem.i do not know what it is.

### ISSUE THREAD

**Issue by flyinskyin2013** [darknessomi/musicbox#40]
M-gM-=~QM-f~X~SM-dM-:~QM-i~_M-3M-dM-9~P

                -> 0. M-f~N~RM-hM-!~LM-fM-&~\
                   1. M-h~IM-:M-f~\M-/M-eM-.M-6
                   2. M-f~VM-0M-gM-"~_M-dM-8~JM-f~^M-6
                   3. M-gM-2M->M-i~@~IM-fM--~LM-e~M~U
                   4. M-f~H~QM-g~Z~DM-fM--~LM-e~M~U
                   5. DJM-h~J~BM-g~[M-.
                   6. M-f~I~SM-gM-"~_
                   7. M-f~TM-6M-h~W~O
                   8. M-f~P~\M-gM-4M-"
                   9. M-eM-8M-.M-e~JM-)

when i run it,this is the first look

**Comment by darknessomi** [comment]
please tell me your OS release version

**Comment by flyinskyin2013** [comment]
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 14.04.2 LTS
Release: 14.04
Codename: trusty

**Comment by darknessomi** [comment]
I can't reproduce this bug in Ubuntu 14.04

**Comment by 20015jjw** [comment]
Do you have any Chinese font installed? I can't reproduce it neither.

**Comment by chaserhkj** [comment]
leave your `echo $LANG` here so we can know if it is your locale that is not properly configured

**Comment by flyinskyin2013** [comment]
en_US.UTF-8

**Comment by darknessomi** [comment]
Please use zh_CN.UTF-8

**Comment by chaserhkj** [comment]
en_US.UTF-8 works for me here.

But please double check that your terminal emulator is properly set to handle utf8 encoding

**Comment by hrzhu** [comment]
Having the same problem. With en_US.UTF-8, musicbox can't display Chinese characters. Other console programs doesn't have this problem. Adding LC_CTYPE=zh_CN.UTF-8 or LANG=zh_CN.UTF-8 doesn't solve the poblem.

**Comment by hrzhu** [comment]
Well, this problem only occurs with my self-compiled python, not the system python. Do you have any clues what might be wrong?

**Comment by hrzhu** [comment]
Just for the sake of information, I recompile my python after installing libncursesw5-dev. Now musicbox can display Unicode characters.
