### ISSUE TITLE
全局快捷键

### ISSUE THREAD

**Issue by liaowang11** [darknessomi/musicbox#401]
现在全局快捷键被deprecate掉了 f49a5eed2bf89013419410b6afc0625899f91608 , 不能用快捷键了..有其他得方案支持么?

**Comment by kigawas** [comment]
如果你的环境没有问题，可以手动启用。
在https://github.com/darknessomi/musicbox/blob/master/NEMbox/menu.py取消相对应的注释并BINDABLE=True

**Comment by liaowang11** [comment]
好的.一直用着好好的.不知道是什么问题?

**Comment by kigawas** [comment]
https://github.com/darknessomi/musicbox/pull/395
