### ISSUE TITLE
xubuntu 32位登录错误

### ISSUE THREAD

**Issue by hak0** [darknessomi/musicbox#405]
python2.7.12
仍然是 timestamp out of range for platform time_t的问题，在linux上未得到修复。如果在api.py中注释掉保存cookie的语句，那么可以暂时访问自己的歌单但无法使用每日推荐等功能。
可否利用[之前jinxingxing提供的工具](https://gist.githubusercontent.com/jinxingxing/b990267b7903a20decea/raw/d138d7b802fcc0b23a386c5f60be4044eeed2c85/musicbox_login.py)，手动保存cookie，以此得到正常的使用？

**Comment by kigawas** [comment]
可以试试Python3

**Comment by hak0** [comment]
尝试用python3来安装运行，也没有改观
最后解决办法是把api.py中的self.session.cookies.save()给注释掉，再在另一台64位机上登陆了一次，把cookie文件拷过来了，功能正常
