### ISSUE TITLE
获取高品质音乐url接口不能用

### ISSUE THREAD

**Issue by hoyho** [darknessomi/musicbox#416]
试了下获取320的，返回链接不能播放，显示404，
于是用wireshark抓了同一首歌发现可以POST /api/linux/forward HTTP/1.1\r\n，但是不知道这个eparam参数怎么加密的
![screenshot from 2016-10-16 12-51-17](https://cloud.githubusercontent.com/assets/8370967/19441394/2e187ac8-94b8-11e6-92fa-2920300e0d59.png)

**Comment by kigawas** [comment]
404有可能是你没有设置referer

**Comment by hoyho** [comment]
不知是不是没有表达清楚，还要设置referer？我是获取到url后直接用chrome打开的，举个例子我试验的歌曲id=31654461（Release Me），linux版网易云返回的歌曲url是：
http://m8.music.126.net/20161017222442/0b30fde8f6376bae847d2ca44fef83b7/ymusic/170b/9041/e11e/85f2545c8dfd7602defe282a655ab49f.mp3（chrome可播放）
但是我调用musicbox里的API返回的结果是：
http://m2.music.126.net/_k1SVz1c5oCMCqqyEVxmIg==/7865906186262034.mp3（不可播放）
