### ISSUE TITLE
Linux下歌曲暂停后无法继续播放自动跳到下一首歌曲

### ISSUE THREAD

**Issue by tianyujieyi** [darknessomi/musicbox#42]
问题重现方式：

从终端运行musicbox，进入搜索，进入精选集，随意找个精选集，开始播放列表歌曲。
若空格暂停某一首歌曲一会儿，如接个电话之类的事情，然后再次空格播放，
本来3分钟多的歌曲播放了一会（大概一分钟？）后，并没有完整播放，自动跳到列表歌曲的下一首。

不知这是否是Bug,　还是咱系统配置问题，目前只在我的作业系统Linux Mint 17.1 64位操作系统测试过有这问题。其他并未确认。

请指教。

**Comment by darknessomi** [comment]
在 OS X10.10 CentOS7 kali Linux 3.18 中未能重现问题，请问能否排除网络问题，因为是在线服务所以如果歌曲加载不出来的话，会跳到下一首播放的。

**Comment by tianyujieyi** [comment]
这几天断断续续我又重新看了一下，切换几个不同的网络环境，又尝试了一下。并不是所有的歌曲都会出现这个问题。有个别歌曲会出现这类问题，而且特别是暂停时间比较长的情况，但并不是所有的歌曲都会出现这个问题。如进入搜索－网易精选集－找到名为“献给爱二次元的小伙伴们”的精选集，里面的歌曲有的歌曲暂停时间较久后播放，虽说没马上跳到下一首歌曲，但总是播放一段时间后，这段时间比较长（有时如果咱不是比较熟悉这歌曲，还是听不出来这歌曲是不完整的），然后会跳到下一首歌曲。

**Comment by chenai** [comment]
@tianyujieyi OSX 10.9 我也出现了这个问题，可能是网络的原因吧，我找找原因

**Comment by wujianye3** [comment]
ubuntu 14.04也出现了这个问题

**Comment by Catofes** [comment]
@wujianye3  更新一下程序，现在有进度条，看看到底是卡住了还是音乐后部分就是静音。
