### ISSUE TITLE
支持鼠标操作

### ISSUE THREAD

**Issue by renzhn** [darknessomi/musicbox#420]
比如htop/vim是可以开启鼠标支持的，能否考虑一下？

我查了下文档应该可以实现 https://docs.python.org/2/library/curses.html?highlight=mouse#curses.getmouse

**Comment by yanpan9** [comment]
*为什么要支持鼠标操作呢?*  
用键盘不是比鼠标快n倍。

**Comment by Catofes** [comment]
#59 你看我们连上下左右都不支持～

23333
