### ISSUE TITLE
tmux下无法正常使用

### ISSUE THREAD

**Issue by tarvos21** [darknessomi/musicbox#425]
/usr/local/lib/python3.5/dist-packages/NEMbox/ui.py", line 78, in addstr
                                self.screen.addstr(args[0], args[1], args[2].encode('u8'), *args[3:])
                                           _curses.error: addstr() returned ERR

tmux下好像ui有问题？哈哈，偶尔发现的

**Comment by liaowang11** [comment]
```bash
echo $TERM
```
看看是不是screen-256color?

**Comment by tarvos21** [comment]
哦，我刚看了， 是`xterm-256color`，这个有区别吗？需要设置？

**Comment by tarvos21** [comment]
解决了，tmux里设置成`set -g defaut-termianl "xterm-256color"`，这里原先是`"screen-256color"`，而`echo $TERM`的结果是`xterm-256color`，应该是颜色不一致导致的问题。
