### ISSUE TITLE
ubuntu 下 账户信息无法保存；进入歌手-李志 程序会进入混乱，无法运行

### ISSUE THREAD

**Issue by msongz** [darknessomi/musicbox#43]
如题

**Comment by darknessomi** [comment]
Ubuntu 14.04 测试结果
1.账户信息无法保存 未能重现
2.进入李志歌单报错 成功重现，是歌单信息解析问题，正在处理。

**Comment by chenai** [comment]
李志的问题我刚才给临时修补了一下，打算PR，

主要原因是因为data[i]['album']  可能是空，而且不一定是dict 。
感觉从网易那边get 过来的json 可能会有很多 为空的情况，所以以后是不是可以考虑对python的dict 写个__missing__方法 封装一下？@darknessomi

**Comment by darknessomi** [comment]
@chenai  嗯，有这种打算了，网易的json略坑，没有就直接空着。。。
