### ISSUE TITLE
musicbox flickering under tmux new window

### ISSUE THREAD

**Issue by mayesheng** [darknessomi/musicbox#435]
Musicbox will flicker in tmux new window <C-a> c, but will be ok with tmux new pane <C-a> %.

**Comment by Catofes** [comment]
![2016-11-18 23-18-07](https://cloud.githubusercontent.com/assets/3324513/20435001/f68dcf42-ad6f-11e6-8335-ebfea29f9e5a.png)

Can not reproduce.
