### ISSUE TITLE
在说明文档里写出升级方式不可以么？

### ISSUE THREAD

**Issue by zhuziyi1989** [darknessomi/musicbox#437]
如题
sudo pip install --upgrade NetEase-MusicBox

**Comment by redapple0204** [comment]
可以用啊

**Comment by faimin** [comment]
谢谢 @zhuziyi1989 , 要不是看到这个issue我还真不知道怎么升级

**Comment by tomoya92** [comment]
用pip安装的就用pip升级方式升级就可以了，用homebrew安装的就用homebrew的升级方式升级呀，这个没必要写吧
