### ISSUE TITLE
建议在README中加入不支持python3

### ISSUE THREAD

**Issue by kulowlance** [darknessomi/musicbox#44]
用python3安装了一次  如何卸载呢？  直接删除 /usr/lib/python3.4/site-packages/下的musicbox文件吗？  不熟悉python

**Comment by darknessomi** [comment]
直接删除即可，在大多数 Linux 发行版中 Python 即代表 Python 2.X

**Comment by 4679** [comment]
arch中 python代表python3 建议做个注释

**Comment by darknessomi** [comment]
@4679 这应该是 arch 用户最基本的知识了

**Comment by kulowlance** [comment]
@darknessomi  /s/高品质网易云音乐命令行版本，简洁优雅，丝般顺滑，基于Python编写。/高品质网易云音乐命令行版本，简洁优雅，丝般顺滑，基于Python2编写。
