### ISSUE TITLE
返回的数据是{"code":502}

### ISSUE THREAD

**Issue by danleechina** [darknessomi/musicbox#442]
请问一下，我自己调试代码的时候，每次请求返回的数据都是{"code":502}，但是用 pip 安装的 musicbox 的话每次返回的数据都是正确的，是什么原因呢？我在调试登录接口。

**Comment by kigawas** [comment]
检查Referer

**Comment by danleechina** [comment]
我知道什么原因了。密码没有用 md5 值。
随便想问一下，你们是怎么知道它是用 RSA + AES 的？我现在正在做一个山寨网易云音乐的 iOS app，但是用的接口地址有一点点不同，Post 的参数是加密了的，和 web 的参数也不一样。而且返回数据也是加密了的，有点卡主了，谁能给点思路？？

**Comment by danleechina** [comment]
https://github.com/danleechina/NetEaseCloudMusic 这是我的模仿网易云音乐的项目地址

**Comment by danleechina** [comment]
我还想知道，你们是怎么知道它加密的数据是比如：
["username":"loginName", "password":"loginPwdMD5", "rememberLogin":"true"]
这样子的？？

**Comment by kigawas** [comment]
RSA+AES网上有人逆向过网易云音乐的加密方式。

至于md5，chrome开发者工具看一看前端的加密代码就行了

**Comment by danleechina** [comment]
嗯，我刚才看前端代码看到了。
这个逆向他们是怎么做的？能否给个地址

**Comment by kigawas** [comment]
https://github.com/darknessomi/musicbox/wiki/网易云音乐新登录API分析

**Comment by danleechina** [comment]
谢谢了

**Comment by danleechina** [comment]
你好，又要麻烦你了。请问一下，为什么有些音乐的 mp3url 在 musicbox 里面可以播放，但是拷贝到浏览器里面则无法播放？我抓包好像也没有抓到？

**Comment by kigawas** [comment]
分新API（浏览器不能直接播放）和旧API（可以直接播放），某些歌的旧API被禁用了，只能用新API

**Comment by danleechina** [comment]
嗯，仔细一看 python 代码里面有。谢谢提醒。
