### ISSUE TITLE
用邮箱登录时报错。

### ISSUE THREAD

**Issue by WeihuaGu** [darknessomi/musicbox#450]
因为好多人用网易云音乐用的是网易邮箱的帐号，能不能增加对于邮箱登录的支持。

**Comment by sheacoding** [comment]
不是可以用邮箱登录吗？ 
------------------ Original ------------------

**Comment by WeihuaGu** [comment]
@sheacoding 因为输入邮箱帐号和密码后就：

![](https://raw.githubusercontent.com/WeihuaGu/asserversource/master/musicbox1.png)

![](https://raw.githubusercontent.com/WeihuaGu/asserversource/master/musicbox2.png)

**Comment by kigawas** [comment]
看上去是pyopenssl的问题，更新一下requests吧

**Comment by WeihuaGu** [comment]
@kigawas 用pip更新，显示是最新的：
```
pip install --upgrade requests
Requirement already up-to-date: requests in ./.local/lib/python2.7/site-packages
```

**Comment by kigawas** [comment]
https://github.com/conda/conda/issues/3938

从上面提到的情况看，requests是新版但pyopenssl可能是旧版，需要更新pyopenssl

**Comment by WeihuaGu** [comment]
@kigawas  谢谢你。更新了pyopenssl为最新版，这回不会像上面图二了。可是退出还是报了错误：
```
Traceback (most recent call last):
……
 File "/usr/lib/python2.7/cookielib.py", line 99, in time2isoz
    year, mon, mday, hour, min, sec = time.gmtime(t)[:6]
ValueError: timestamp out of range for platform time_t
```
我不懂python,好像跟时间戳有关。

**Comment by kigawas** [comment]
32位Python的一个问题，见https://github.com/darknessomi/musicbox/issues/405

**Comment by WeihuaGu** [comment]
@kigawas 再次感谢！ 看了下#405 ，好像是因为处理年限的关系,在32位linux上面会报错。
