### ISSUE TITLE
怎么设置代理

### ISSUE THREAD

**Issue by myahmao** [darknessomi/musicbox#451]
在哪里可以设置代理？系统的代理好像不管用。

**Comment by kigawas** [comment]
看readme

**Comment by myahmao** [comment]
加了代理，买了会员，还是播放不了

215 2016-12-10 19:33:44,890 - WARNING - NEMbox.player:111: Song 298957 is not compatible with old api.
216 2016-12-10 19:33:44,891 - WARNING - NEMbox.player:112: http://m10.music.126.net/20161211115844/4d127e2795bd79c891c23797ee525b75/ymusic/e620/01be/1932/af3ece57de28894eac7ccde7a9bd6acc.mp3

**Comment by leo-mao** [comment]
- 代理你要这样如下@myahmao，亲测会员毫无卵用

> "mpg123_parameters": {
>     "default": [],
>     "describe": "The additional parameters when mpg123 start.",
>     "value": ["-p", "http://ip:port"]
> }
> 

- 如果你的代理需要帐号密码验证的话改成这样,亲测有效，详情见[man for mpg123](http://derpi.tuwien.ac.at/cgi-bin/man/man2html?1+mpg123)

> "mpg123_parameters": {
>     "default": [],
>     "describe": "The additional parameters when mpg123 start.",
>     "value": ["-p", "http://ip:port", "-u","user:password"]
> }

-  @kigawas 建议在readme中加上需要验证的代理格式，另外还有部分本来限制IP的歌曲还是会跳出来you need login,例如

> Shape of You  -  Ed Sheeran  < Shape Of You >

,具体原因未知，但是大部分限制IP的歌曲，亲测可以播放．
环境如下
OS: Manjaro 16.10 Fringilla
Kernel: x86_64 Linux 4.8.17-1-MANJARO
Shell: zsh 5.3.1
NetEase-MusicBox－0.2.4.0
