### ISSUE TITLE
remove键可以删除一些...奇怪的东西

### ISSUE THREAD

**Issue by chaserhkj** [darknessomi/musicbox#46]
remove键的检查机制里面只检查了datatype是不是main..所以这直接导致了这个行为可以影响一些奇怪的datatype,比如说帮助菜单什么的...我不知道这个是不是intended behavior...

#45 里的上移下移功能里的检查是参考remove功能的检查实现的,所以也可以移很多奇怪的东西...

我不是很清楚这个东西是不是本来就是设计成这样的...姑且问一问...

**Comment by darknessomi** [comment]
并没有想到还能这么玩。。。。
