### ISSUE TITLE
Mac os 10.11无法播放，没有声音。

### ISSUE THREAD

**Issue by wangKuma** [darknessomi/musicbox#467]
<img width="919" alt="screen shot 2017-01-13 at 6 31 36 pm" src="https://cloud.githubusercontent.com/assets/18530891/21926859/94130564-d9be-11e6-9227-0f2c344cb5ec.png">

**Comment by ikzk** [comment]
Make sure you have installed mpg123

**Comment by myt00seven** [comment]
我也是OSX 10.11.6 播放的时候显示00:00/00:01，然后过几秒钟就跳到下一首歌，依然显示00:00/00:01. 用mpg123播放本地的mp3可以正常播放。没有Error信息，执行 cat musicbox.log显示cat: musicbox.log: No such file or directory。

**Comment by Sunnyhp** [comment]
用 sudo musicbox启动就有声音
