### ISSUE TITLE
如何登录，使用过程频繁提示需要登录，不知如何操作~~~

### ISSUE THREAD

**Issue by libaoming** [darknessomi/musicbox#469]
这个如何操作

![Uploading netease-music.jpeg…]()

**Comment by kigawas** [comment]
图看不见

**Comment by libaoming** [comment]
![image](https://cloud.githubusercontent.com/assets/20967916/22006306/fa6c825c-dca4-11e6-92d0-e7334725644b.png)

见上图~

**Comment by kigawas** [comment]
在终端里面登录

**Comment by libaoming** [comment]
好快回复~~~  终端咋登录，入口是啥~~~

**Comment by kigawas** [comment]
https://github.com/darknessomi/musicbox/blob/master/README.md

看readme的动图

**Comment by libaoming** [comment]
感谢感谢。home > 我的歌单. you save my time~~~
