### ISSUE TITLE
windows bash Ubuntu 版 没有声音

### ISSUE THREAD

**Issue by yutiansut** [darknessomi/musicbox#470]
![_20170116184223](https://cloud.githubusercontent.com/assets/11537812/21979885/cf7fa012-dc1b-11e6-9b72-3d4450611a26.png)

**Comment by chenygang** [comment]
这是歌曲的评论！你在上一个目录 即歌曲目录  按空格就可以播放了

**Comment by yutiansut** [comment]
![_20170116202551](https://cloud.githubusercontent.com/assets/11537812/21983066/3f45938a-dc2a-11e6-9252-5699abe8d23d.png)
![_20170116202558](https://cloud.githubusercontent.com/assets/11537812/21983079/489666ee-dc2a-11e6-85c0-62b6a8c15a5a.png)
![_20170116202608](https://cloud.githubusercontent.com/assets/11537812/21983085/5061cfb2-dc2a-11e6-9475-0e0e04fd472b.png)
我的就是这样的 并没有一个地方可以播放 另外 windows bash下的backspace 似乎不能后退?

**Comment by yutiansut** [comment]
![_20170116203028](https://cloud.githubusercontent.com/assets/11537812/21983141/a6fa7b9e-dc2a-11e6-9515-8ffdc3dad78a.png)
![_20170116202939](https://cloud.githubusercontent.com/assets/11537812/21983142/a7cc740a-dc2a-11e6-9e1e-d57ec9de1773.png)
不好意思 我找到了 但是 依旧没法播放  在00:01就卡住了  似乎和别的issue里面 MAC用户的情况一样

**Comment by yutiansut** [comment]
[和这个issue一样](https://github.com/darknessomi/musicbox/issues/467)

**Comment by kigawas** [comment]
mpg123装了么

**Comment by yutiansut** [comment]
装了 sudo apt-get install mpg123
然后还是卡在00:01的位置上

**Comment by xdujiang** [comment]
问题相同，报错也相同，系统win10 1611，ubuntu14.04，musicbox用的源码安装

**Comment by kigawas** [comment]
试一下mpg123能不能播放 @xdujiang

**Comment by xdujiang** [comment]
@kigawas 问题好像就出在mpg123上了...好像差文件...
也许win10的ubuntu差声卡驱动？

$ mpg123 test.mp3
[module.c:129] error: Failed to open module jack: file not found
[module.c:129] error: Failed to open module portaudio: file not found
[module.c:129] error: Failed to open module pulse: file not found
[module.c:129] error: Failed to open module nas: file not found
[module.c:129] error: Failed to open module openal: file not found
[audio.c:180] error: Unable to find a working output module in this list: alsa,oss,jack,portaudio,pulse,nas,openal
[audio.c:532] error: Failed to open audio output module
[mpg123.c:901] error: Failed to initialize output, goodbye.

**Comment by Sunnyhp** [comment]
用 sudo musicbox启动就有声音
