### ISSUE TITLE
Request feature for configuration option that controls the auto-check-in behavior.

### ISSUE THREAD

**Issue by legendtang** [darknessomi/musicbox#471]
The reason is that I've deployed another check-in services myself, thus this behavior often interrupts my tool's judgment on whether the check-in was successful. And some people might not need this feature to be enabled by default. Please consider it.

**Comment by ikzk** [comment]
A simple workaround would be adding a line to https://github.com/darknessomi/musicbox/blob/master/NEMbox/api.py

```
    def daily_signin(self, type):
        return 1 # add this line
        action = 'http://music.163.com/weapi/point/dailyTask'
        text = {'type': type}
        data = encrypted_request(text)
        try:
            return self.httpRequest('POST', action, data)
        except requests.exceptions.RequestException as e:
            log.error(e)
        return -1
```
