### ISSUE TITLE
OS X 10.10.4 播放没声音

### ISSUE THREAD

**Issue by FTAndy** [darknessomi/musicbox#475]
随便播放一首歌：

```
http://music.163.com/api/v1/resource/comments/R_SO_4_451703096/?rid=R_SO_4_451703096&%20%20%20%20%20%20%20%20%20%20%20%20offset=0&total=fasle&limit=100
```
返回
{"code":403,"message":"illegal request!"}

**Comment by wakerman** [comment]
版本：10.12.4 (16E195)

同样没有声音，登录之后播放也是没有。
歌曲选了之后
![image](https://cloud.githubusercontent.com/assets/3078413/25062434/a1f190d2-21fe-11e7-8361-e6ef8d9ee8c5.png)
回车之后就跳到了评论列表。

**Comment by kigawas** [comment]
mpg123装了吗？
另外播放是按space

2017年4月15日(土) 17:12 iMactool <notifications@github.com>:

**Comment by wakerman** [comment]
嗯，OK，可以了 ;-）

**Comment by alongsoCJR** [comment]
你怎么解决的呀，我本地也播放不了。

**Comment by alongsoCJR** [comment]
mpg123 http://music.163.com/api/v1/resource/comments/R_SO_4_451703096/\?rid\=R_SO_4_451703096\&%20%20%20%20%20%20%20%20%20%20%20%20offset\=0\&total\=fasle\&limit\=100

High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.25.13; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes
Warning: additional info in content-type ignored (charset=UTF-8)
main: [src/mpg123.c:684] error: Unknown mpeg MIME type text/plain;charset=UTF-8 - is it perhaps a playlist (use -@)?
main: [src/mpg123.c:685] error: If you know the stream is mpeg1/2 audio, then please report this as mpg123 bug
