### ISSUE TITLE
由于python版本pow函数的问题MacOS无法登录个人网易云音乐账号

### ISSUE THREAD

**Issue by xmfbit** [darknessomi/musicbox#477]
您好，@darknessomi，您的作品我很喜欢。但是我在使用中尝试登录个人的网易云音乐账号，musicbox异常退出，并提示以下错误信息：
```
TypeError: __pow__() takes exactly 2 arguments (3 given)
```
我使用的系统为MacOS10.12.2，在安装musicbox时我使用了GitHub中的源码并使用`python setup.py install`命令进行安装。

我搜索后发现这和python3与python2中的pow函数接受参数不同有关，请参见这个GiitHub上的[讨论帖](https://github.com/PythonCharmers/python-future/issues/87)

所以，我将api.py文件`rsaEncrypt(text, pubKey,modulus)`函数中的`rs`变量计算过程修改如下：
```
tmp = pow(int(binascii.hexlify(text), 16), int(pubKey, 16))
rs = tmp % int(modulus, 16)
```
这样，才能够登录我的个人账号。

**Comment by kigawas** [comment]
应该好了，你git pull再尝试一下
