### ISSUE TITLE
arch live中打开错误

### ISSUE THREAD

**Issue by redapple0204** [darknessomi/musicbox#479]
![2](https://cloud.githubusercontent.com/assets/16254644/22591237/6a067dfa-ea4e-11e6-8ec2-21c51231a32e.PNG)

**Comment by kigawas** [comment]
http://stackoverflow.com/questions/14547631/python-locale-error-unsupported-locale-setting

locale设定问题

**Comment by redapple0204** [comment]
@kigawas 谢谢，搞定了。
