### ISSUE TITLE
Win10调用signal 模块时出现'module' object has no attribute 'SIGWINCH'

### ISSUE THREAD

**Issue by heyuan1993** [darknessomi/musicbox#481]
Anaconda，python 3.5.2。
运行之后Win10调用signal 模块时出现'module' object has no attribute 'SIGWINCH'。。。

**Comment by kigawas** [comment]
不支持win，请尝试Cygwin或者bash on Windows

**Comment by kigawas** [comment]
windows有官方客户端.....

**Comment by heyuan1993** [comment]
我安过ubuntu双系统了，不过不太常用。你说的这两个用容我先去研究一下，坑有点多哈哈。。多谢多谢~api.py这个帮了大忙了，主要是想抓网易云所有评论的内容来着，我也太曲线救国了。。。

**Comment by kigawas** [comment]
那忘掉Cygwin吧...bash on Ubuntu在win10里面可以直接安装

**Comment by heyuan1993** [comment]
哈哈，谢谢啦。我跨掉了这个问题直接调用api.py提取数据了。
另外有个问题：每首歌的评论好像最多只能抓100条？我试过api.py里的内置函数，怎么调参数都只能抓100条以内，后来是自己调api的评论地址，每次抓100条一直到抓到全部的。
此外，可否增加一个api的功能，就是如果看到喜欢的评论，可以点进这个用户空间看对方收藏的歌曲和歌单之类的~
