### ISSUE TITLE
打开屏幕会一闪一闪的

### ISSUE THREAD

**Issue by bigsuperangel** [darknessomi/musicbox#489]
可以正常播放，只是屏幕会有一闪一闪的，光标一直在跳动，ubuntu server 14

**Comment by wangKuma** [comment]
你好，能提供更多的信息吗？
## 所使用的系统版本
## 所使用产品版本
## 问题的详细描述与截图(如果可以)
## 如何复现该问题

**Comment by wangKuma** [comment]
用的是默认的 terminal 吗？
能录一个 gif 吗？
