### ISSUE TITLE
音质问题

### ISSUE THREAD

**Issue by chaserhkj** [darknessomi/musicbox#50]
关于这个程序使用的云音乐的源的音质问题，我有一些疑问

今天读源码的时候注意到程序是从song details里面的'mp3Url'键值读取音乐播放地址的，但是我尝试了几首曲子，发现这个键值里面的音乐都是96kbps的mp3，而不是README里面说的320kbps

另一方面，我在[另外一个项目](https://github.com/yanunon/NeteaseCloudMusic)中, 看到了关于网易云音乐音频存储的URL加密机制的说明文档和相关的加密算法，可以用来实现播放320kbps的mp3流

考虑到这个程序[复杂的背景](http://www.v2ex.com/t/123375)，只播放96kpbs音频可能是一种保险的做法，因为虽然加密算法是大家反向工程出来的，没有使用任何网易的代码，不存在__版权__问题，但是如果网易持有对上述算法的__专利权__的话，毫无疑问对于该算法的重实现也是违反__专利权法__的。

不过，鉴于上述的项目中的代码长期存在并且未被网易追究，而且我查阅了[中国国家知识产权局](http://www.sipo.gov.cn/)的[公众专利查询系统](http://www.pss-system.gov.cn/sipopublicsearch/portal/app/home/declare.jsp)，并未查询到网易有申请和这个算法相关的专利记录，也许这一担心是多余的……

于是，我觉得现在我们要做的事情应该是这样的：

- 如果觉得知识产权问题应该不是个问题的话，应该参照上述项目给出的算法在这个程序里面实现货真价实的320kbps播放
- 如果怕惹麻烦的话，在维持现状的同时至少应该把README中的320kbps播放去掉……要不然实在太有误解性了……

这个该怎么做就得由Project owner @darknessomi 决定了 = =

**Comment by darknessomi** [comment]
6db5f98
音源问题已经解决，优先使用320kbps，如果没有再使用其他kbps的音源

**Comment by chaserhkj** [comment]
其实在提交issue之前我已经写过一个patch实现320k了但是还在犹豫要不要提交上来……结果你又写了一遍Orz

Anyway, issue closed

**Comment by darknessomi** [comment]
但愿不会被水表，我看 chrome 插件活得好好地。
