### ISSUE TITLE
树莓派Ubuntu mate 16.04 系统下，输入 musicbox，musicbox: command not found

### ISSUE THREAD

**Issue by lanlingsheng** [darknessomi/musicbox#519]
我在树莓派Ubuntu mate 16.04 系统下安装， pip list 里都显示 NetEase-MusicBox (0.2.4.0)，
在命令行输入 musicbox， 出现musicbox: command not found。
mpg123 也安装成功了。

**Comment by zhonghaoyu555** [comment]
路径没有配置在环境变量里。
建立个软链接/usr/bin/musicbox就行

**Comment by Eacials** [comment]
我也是这个情况... 建立软链接也不行诶

**Comment by ZHWUER** [comment]
怎么建立软链接啊。。

**Comment by 2niuhe** [comment]
我也碰到这个问题，解决方法如下：
```shell
niuhe@niuhe-VirtualBox:~$ cd ~/.local/bin/
niuhe@niuhe-VirtualBox:~/.local/bin$ ls
chardetect  futurize  musicbox  pasteurize  pip  pip2  pip2.7  pip3  pip3.5
niuhe@niuhe-VirtualBox:~/.local/bin$ ./musicbox 
```
当上边都能运行了，然后建立软链接：
`niuhe@niuhe-VirtualBox:~/.local/bin$ sudo ln -s /home/niuhe/.local/bin/musicbox /usr/bin/musicbox`

注意：sudo ln -s 源文件 目标路径

两个路径都要是完整的绝对路径，不能是相对路径。
然后输入musicbox就可以直接运行了。

**Comment by 2niuhe** [comment]
我也碰到这个问题，解决方法如下：
```shell
niuhe@niuhe-VirtualBox:~$ cd ~/.local/bin/
niuhe@niuhe-VirtualBox:~/.local/bin$ ls
chardetect  futurize  musicbox  pasteurize  pip  pip2  pip2.7  pip3  pip3.5
niuhe@niuhe-VirtualBox:~/.local/bin$ ./musicbox 
```
当上边都能运行了，然后建立软链接：
`niuhe@niuhe-VirtualBox:~/.local/bin$ sudo ln -s /home/niuhe/.local/bin/musicbox /usr/bin/musicbox`

注意：sudo ln -s 源文件 目标路径

两个路径都要是完整的绝对路径，不能是相对路径。
然后输入musicbox就可以直接运行了。
