### ISSUE TITLE
Centos 7 occurs error when play a song

### ISSUE THREAD

**Issue by Keleir** [darknessomi/musicbox#520]
> Python： 3.5.2
> NetEase-MusicBox installed version：0.2.4.0

```
(/usr/bin/notify-send:44388): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_O
```

![image](https://cloud.githubusercontent.com/assets/7112075/24442244/d269f7da-148f-11e7-845d-11594416ba26.png)

**Comment by ikzk** [comment]
看起来是 notify-send 的锅. 更新一下 libnotify 呢?
