### ISSUE TITLE
操作反人类

### ISSUE THREAD

**Issue by mo10** [darknessomi/musicbox#524]
使用中丝毫没有“Vimer式快捷键让操作丝般顺滑”
迷之Vim.
我不是Vim用户,我希望能用 **上 下 左 右** 来选择菜单项目,用空格等键位来控制播放,而不是记下长长的键位表,或者花时间去自己琢磨设置键位.

以上,一个不是Vimer的异端用户

**Comment by godfather1103** [comment]
代码是开源的，如果不符合你的习惯的话你可以自己去改啊！

**Comment by mo10** [comment]
嘛。只是提个意见 (摊手

**Comment by LaoQi** [comment]
@mo10 又不是商业软件，没有必要对用户负责。
你自己看看附带的协议写的 `WITHOUT WARRANTY OF ANY KIND`，你觉得按键不合适自己fork一份自己改。

**Comment by XenonChau** [comment]
操作很顺手啊。。。就是不知道为什么按了一下播放就报错退出了。
太晚了没时间看源码了。改天再看吧。
