### ISSUE TITLE
显示播放进度以及控制的相关问题

### ISSUE THREAD

**Issue by Catofes** [darknessomi/musicbox#53]
其实是我当初挖的坑。。为了加入音量功能，所以用了mpg123 的 -R模式。

mpg123 模式获取歌曲的长度的方法如下：

LP载入歌曲，SAMPLE 的第二个参数得到总体采样数目， FORMAT 的第一个参数得到采样率，相除就是秒数。

    SAMPLE
    @SAMPLE 0 9673465
    FORMAT
    @FORMAT 44100 2

获取当前播放时间可以关闭SILENCE模式，播放时会返回

```
@S 1.0 3 44100 Joint-Stereo 0 1044 2 1 1 0 320 0 0
@F 0 8396 0.00 219.32
@F 0 8396 0.00 219.32
@F 1 8395 0.03 219.30
@F 2 8394 0.05 219.27
@F 3 8393 0.08 219.25
@F 4 8392 0.10 219.22
@F 5 8391 0.13 219.19
@F 6 8390 0.16 219.17
```

格式的结构。 @s的 1044 表明一共1044帧， @F的第一个参数表示当前帧数。相除即可。

或者不停的输入SAMPLE， 计算当前位置。

SO 诸君的意思呢？

**Comment by Catofes** [comment]
或者说我们需要现实播放时间以及控制具体的进度嘛？

**Comment by darknessomi** [comment]
唔, @chaserhkj @chenai 怎么看？
@F 第四个参数不就是剩余秒数么？

**Comment by Catofes** [comment]
啊咧。。。。。。。。。 好像是啊

**Comment by Catofes** [comment]
已写。 不过好难看。
