### ISSUE TITLE
成功安装musicbox却不能运行？ImportError: No module named 'menu'不支持windows？

### ISSUE THREAD

**Issue by dAxIOnG8** [darknessomi/musicbox#531]
(py35) C:\Users\shu>pip install musicbox
Collecting musicbox
  Downloading musicbox-0.1.2.4.tar.gz
Requirement already satisfied: requests in c:\anaconda3\envs\py35\lib\site-packages (from musicbox)
Requirement already satisfied: BeautifulSoup4 in c:\anaconda3\envs\py35\lib\site-packages (from musicbox)
Building wheels for collected packages: musicbox
  Running setup.py bdist_wheel for musicbox ... done
  Stored in directory: C:\Users\shu\AppData\Local\pip\Cache\wheels\0b\8e\69\5ab88b956db7a15795b348889e6acfd2ef3e6cc1e34c694653
Successfully built musicbox
Installing collected packages: musicbox
Successfully installed musicbox-0.1.2.4

(py35) C:\Users\shu>
(py35) C:\Users\shu>musicbox
Traceback (most recent call last):
  File "c:\anaconda3\envs\py35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\envs\py35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\py35\Scripts\musicbox.exe\__main__.py", line 5, in <module>
  File "c:\anaconda3\envs\py35\lib\site-packages\src\__init__.py", line 8, in <module>
    from menu import Menu
ImportError: No module named 'menu'

**Comment by kigawas** [comment]
pip install错了。
pip install NetEase-MusicBox

支不支持主要看mpg123能不能支持Windows

2017年4月23日(日) 16:33 dAxIOnG8 <notifications@github.com>:

**Comment by rogl4784** [comment]
Send me $1.00.
