### ISSUE TITLE
如何源代码启动？

### ISSUE THREAD

**Issue by ccfwwm** [darknessomi/musicbox#533]
python ./NEMbox/__init__.py 无法启动

Traceback (most recent call last):
File "init.py", line 19, in 
from .menu import Menu
ValueError: Attempted relative import in non-package

**Comment by kigawas** [comment]
python -m NEMbox.__init__

**Comment by fffx** [comment]
在项目根目录下， 
    
    cd NEMbox; python -m NEMbox.__init__

**Comment by ikzk** [comment]
Detailed explanation can be found here http://stackoverflow.com/questions/6630822/running-a-python-package
