### ISSUE TITLE
mac下放着放着就停住了且狂占cpu

### ISSUE THREAD

**Issue by out0fmemory** [darknessomi/musicbox#543]
mac下播放歌单或者排行榜，播放一段时间后不自动播放下一曲，并且占用大量cpu

**Comment by ahumeijun** [comment]
+1
烫死了

**Comment by out0fmemory** [comment]
通过调试大致找到原因了，mpg123在一定情况下会halt，一直后台空循环
稍后我来发个pull request

**Comment by out0fmemory** [comment]
大家又遇到问题，可以试试我发的pull request，https://github.com/darknessomi/musicbox/pull/549
