### ISSUE TITLE
api.py中有一个小bug以及一个小建议

### ISSUE THREAD

**Issue by OneGIl** [darknessomi/musicbox#55]
bug：
在api.py中search函数体里面的limit被写死了，参数limit失去了调节返回数量的作用。导致每次响应都会返回60个结果。'limit': 60 => 'limit': limit

疑问：
在api.py中有一个import logger，可能我用的是python3的原因，告诉我没有getLogger这个函数。所以我就把logger换成了logging，这样就不会报错了。不知道在python3中这样改有没有不妥的地方？

建议：
因为win平台的限制，只能用api来进行二次开发。在我第一次尝试使用api的时候，却卡在了登陆那里，怎么弄都不行，然后查看ui.py文件发现，发出登陆请求前会对输入的密码进行一个md5的加密，这个加密过程不知道能不否放到api.py里面，这样其他有二次开发需求的人开发起来也会方便一些。当然，作为编程初学者，我不懂的东西很多，你们这样弄应该有这么弄的理由吧？ : )

**Comment by darknessomi** [comment]
真的是很小一个 bug 了，其实也不算是 bug ,因为limit本来就是写死的，不过还是谢谢提出。

至于密码md5加密的问题，因为本地是保存有登陆信息的，所以要提前在ui.py里加密
如需要在api.py里加密，可参考 9930cb8

**Comment by OneGIl** [comment]
好的，谢谢!
