### ISSUE TITLE
 error: Setup script exited with error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

### ISSUE THREAD

**Issue by twodogegg** [darknessomi/musicbox#564]
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
error: Setup script exited with error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

百度了一天了，还是没有办法。

**Comment by wangKuma** [comment]
windows 目前不在支持系统中
