### ISSUE TITLE
Bash on Ubuntu 

### ISSUE THREAD

**Issue by akyakya** [darknessomi/musicbox#567]
![image](https://user-images.githubusercontent.com/6993269/27212345-e4a29bc4-5291-11e7-973d-ff957a0c3c3f.png)

安装运行登陆都没问题,播放的之后没法播放一直跳

**Comment by out0fmemory** [comment]
什么系统上的？

**Comment by out0fmemory** [comment]
在#568上修复了，麻烦验证下

**Comment by akyakya** [comment]
不好意思，我的是在win10上面的那个linux 子系统里面跑的，最近更新了好像登录还是不能播放，但是错误不一样了

![image](https://user-images.githubusercontent.com/6993269/28529897-70222db8-70c4-11e7-835a-040333917b25.png)

**Comment by zkl99999** [comment]
me too  +1

**Comment by bodhisatan** [comment]
请问解决了吗= =我也不能用，wsl

**Comment by wangKuma** [comment]
@bodhisatan  你新开一个 issue 吧；用的版本，安装方式，错误日志，系统信息贴一下。

**Comment by bodhisatan** [comment]
@wangKuma
新开了，麻烦解答一下，谢谢
