### ISSUE TITLE
自动显示default的字样

### ISSUE THREAD

**Issue by han8gui** [darknessomi/musicbox#571]
系统为centos7

![问题图片](http://img.blog.csdn.net/20170627171651460?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvVGltZTg4OA==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

**Comment by han8gui** [comment]
系统为centos7

**Comment by ziluoxingjun** [comment]
我也是这个问题，centos7 python 2.7.5，git clone ,python setup.py install 安装的

**Comment by wangKuma** [comment]
你好，这个问题会在下一个版本中修复；
现在可以切换到 develop 分支，然后安装

**Comment by han8gui** [comment]
可以了
