### ISSUE TITLE
上移下移项目有什么用？

### ISSUE THREAD

**Issue by chenai** [darknessomi/musicbox#58]
@chaserhkj  我的电脑上，K J 上下移动项目，可是歌单列表都没有对上号,,, 这个功能到底是干嘛的?

**Comment by chenai** [comment]
发现这个问题是只出现在排行榜上，原来是个bug

**Comment by darknessomi** [comment]
用处不大，因为不能同步到云端

**Comment by chaserhkj** [comment]
主要这个功能是我用来修改本地的收藏列表顺序的……以及以后打算加入云端的播放列表的修改功能

如果在一些地方调整它没有作用的话，我回头加个过滤判断吧
