### ISSUE TITLE
CentOS7启动播放器后屏幕上不断跳出Default

### ISSUE THREAD

**Issue by nemo95** [darknessomi/musicbox#580]
`2017-07-06 10:26:06,608 - ERROR - NEMbox.terminalsize:83: Struct() argument 1 must be string, not unicode`
`2017-07-06 10:26:06,608 - ERROR - NEMbox.terminalsize:83: Struct() argument 1 must be string, not unicode`
`2017-07-06 10:26:06,609 - ERROR - NEMbox.terminalsize:83: Struct() argument 1 must be string, not unicode`
`2017-07-06 10:26:06,609 - ERROR - NEMbox.terminalsize:83: Struct() argument 1 must be string, not unicode`
`2017-07-06 10:26:06,609 - ERROR - NEMbox.terminalsize:99: u'LINES'`

日志上不断出现这样的报错

python 版本为 2.7.5

**Comment by liulongleo** [comment]
hi， 请问你的Centos是使用哪个命令安装的？我使用dnf安装时提示找不到资源，使用pip安装时也是失败，提示为
`Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8el137/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Cph1Bv-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-8el137/pycrypto/`

**Comment by liulongleo** [comment]
对了，我是Centos7的最小安装

**Comment by ziluoxingjun** [comment]
我也是满屏跑 default ，python 版本为 2.7.5 ，我是用git clone ，python setup.py install 方法安装的！

**Comment by xiaodaowanwan** [comment]
我也是同样的问题。

**Comment by wangKuma** [comment]
你好，这个问题会在下一个版本中修复；
现在可以切换到 develop 分支，然后安装
