### ISSUE TITLE
ubuntu 14.04 安装失败 如下图

### ISSUE THREAD

**Issue by zdzliqian** [darknessomi/musicbox#586]
![2017-07-16 14 41 03](https://user-images.githubusercontent.com/10721790/28245247-249fb12a-6a35-11e7-8b21-6bd96a8c8ad3.png)

**Comment by amitbha** [comment]
看上去是当前路径有无法解析的字符，可能和中文路径有关系
切换到不带中文的路径，再安装试试

**Comment by zdzliqian** [comment]
@amitbha 可以了 多谢
