### ISSUE TITLE
国外服务器访问网易云音乐的接口问题。。

### ISSUE THREAD

**Issue by wxz1211** [darknessomi/musicbox#589]
我的服务器是新加坡阿里云上的，访问网易云的接口，接口返回值是加密过的。
在本地测试时 返回是正常的。。这个问题有人遇到过吗
<url http://music.163.com/weapi/cloudsearch/get/web  requestJsonStr {"hlpretag":"","hlposttag":"","s":"innocence","type":"1","offset":"0","total":"true","limit":"15"} result {"result":"35b1748964af8a7c1d883e3abf4d0338b10b0bc055f6f6245faf12e84e4fb3f97c0b4da0ddffe579a05362fd773a62480b4dcb047c42bb746e654e66deb10b6497b185133b9774d76c59c38977358afdd1e0394446e487b52ca01a7b0b9ea6fcea8ad5106403458974e5661e19fd483a408ca6681ba62ab9de408b442e4fe0b2a26e3e5f094f4d7c4d06401819382d4da88c87b3ba047cb763046b177fc5ae5dab992c2ede792c2df922859dcd23ab3cc118f6bcc981aca86b3f06“}

**Comment by Binaryify** [comment]
由于网易限制,此项目在国外服务器上使用会受到限制,如需解决,可使用大陆服务器或者使用代理,感谢 @hiyangguo提出的解决方法,在 'util.js' 的 'headers'处增加 X-Real-IP':'211.161.244.70' //任意国内IP 即可解决

**Comment by wangKuma** [comment]
歌曲 API 只接受中国大陆地区访问，可以自行设置代理。
详细配置可以查看 README.md 中**配置文件**那节
