### ISSUE TITLE
[投票]关于绑定上下左右按键到hjkl的投票。

### ISSUE THREAD

**Issue by Catofes** [darknessomi/musicbox#59]
现在方向按键没有利用起来，而且我估计有不少人不习惯hjkl的操作习惯。能不能把上下左右按键也加入到菜单的控制里面去？

**Comment by darknessomi** [comment]
这不是能不能的问题，这是本程序的特色之一，否则此功能早就加上了。

**Comment by Catofes** [comment]
。。好吧呀。 我不明白这个特色有什么用。 vim都支持上下左右捏，两种操作方式都支持不也不错？

**Comment by chenai** [comment]
哈哈，我觉得这个功能要发起一个投票~~

**Comment by darknessomi** [comment]
这么说吧，当初吸引我和小伙伴的原因之一就是键位了

**Comment by chenai** [comment]
@darknessomi 作为vim党 和 HHKB党，我的确也认为按键很爽 : )
但是我觉得我们已改定位一下这个好好产品的初衷，这样以后要加什么功能，不加什么功能就很明确啦 :+1:

**Comment by Catofes** [comment]
这个想法是在今天我在给一个用osx朋友推荐这个软件的时候想到的。他觉得hjkl不是特别的顺手。然后我就觉得对于普通用户来说，可能上下左右更习惯一些。所以希望能够
额外 添加上下左右控制。

个人虽然表示无所谓，但是不太理解增加这种控制会有啥不好之处。如果没啥大的意见，发起个投票我觉得不错～

**Comment by darknessomi** [comment]
来来来，投票投票
<iframe src="https://docs.google.com/forms/d/1FoF42FGh0tQn9c0UHR8J1ZuYU4jySie-y-7T4WL5P9c/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">正在加载...</iframe>
