### ISSUE TITLE
杂音

### ISSUE THREAD

**Issue by jth445600** [darknessomi/musicbox#591]
有规律的杂音，点点点点

**Comment by wangKuma** [comment]
你好，感谢使用，能否依据以下格式提供详细信息
## 所使用的系统版本
## 所使用产品版本
## 问题的详细描述与截图(如果可以)
## 如何复现该问题

**Comment by jth445600** [comment]
树莓派3b
rasp-debian
我使用外接音响
可能是那个音响的问题，因为是有规律的点点点。
不过也都无所谓了，树莓派电源坏了，我也一时半会用不上。

**Comment by wangKuma** [comment]
可以看一下这个 issue #374
