### ISSUE TITLE
安装失败 这是怎么回事？

### ISSUE THREAD

**Issue by liguge** [darknessomi/musicbox#592]
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastm
ath.
    building 'Crypto.Random.OSRNG.winrandom' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual
C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "c:\users\administrator\appdata\local\programs\python\python36-32\python
.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\
Local\\Temp\\pip-build-h3uaqz7j\\pycrypto\\setup.py';f=getattr(tokenize, 'open',
 open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code
, __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\pip-
y71nsgay-record\install-record.txt --single-version-externally-managed --compile
" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-h3u
aqz7j\pycrypto\

**Comment by luckyScript** [comment]
缺少Cpp的编译器吧

**Comment by zhaiweihao** [comment]
也碰到这个问题，我修复了vs2017，安装了vc++编译器，但是还是不行

**Comment by wangKuma** [comment]
你好，感谢使用，能否依据以下格式提供详细信息
## 所使用的系统版本
## 所使用产品版本
## 问题的详细描述与截图(如果可以)
## 如何复现该问题

**Comment by falling12** [comment]
应该是安装pycrypto时出了问题，可以尝试使用pycryptodome取代
