### ISSUE TITLE
非正常退出影响终端使用

### ISSUE THREAD

**Issue by Saddam0523** [darknessomi/musicbox#60]
RT，某些情况下非正常退出（如未联网播放音乐）会导致终端命令不回显，而且回车显示异常。
不算是严重的 bug 吧，不过可以改进一下么？

**Comment by chenai** [comment]
@Saddam0523 谢谢反馈~~
我发现在未联网的情况下，的确一些选项会出现crash，比如说未联网下艺术家 一直按L进入到底就会crash,请问你说的bug是这种吗？
如果不是能大概说一下怎么复现出来么？

**Comment by Saddam0523** [comment]
没错，就是这种情况。

**Comment by darknessomi** [comment]
最新版本崩溃已经不会花屏了
