### ISSUE TITLE
双行歌词显示带翻译歌词的问题

### ISSUE THREAD

**Issue by BruceZhang1993** [darknessomi/musicbox#601]
https://github.com/darknessomi/musicbox/blob/8f9fd959bb5fc5c333ead965124bb3a3a8a5a8e2/NEMbox/ui.py#L225

下一行歌词翻译没有更新

![screenshot_20170820_113736](https://user-images.githubusercontent.com/6873988/29491940-0e51931e-859e-11e7-93b9-762a2af98340.png)

**Comment by out0fmemory** [comment]
找个时间我来修复下

**Comment by pkumza** [comment]
遇到同样的问题…希望尽快修复。
这都已经12月了。

**Comment by pkumza** [comment]
我已经修好了，[PR#643](https://github.com/darknessomi/musicbox/pull/643)  @out0fmemory

**Comment by BruceZhang1993** [comment]
@pkumza 感谢PR.. I'll close this...
