### ISSUE TITLE
多个终端 如何只启动一个musicbox?

### ISSUE THREAD

**Issue by aikunzhe** [darknessomi/musicbox#607]
如题

**Comment by wangKuma** [comment]
你好，感谢使用，能否依据以下格式提供详细信息
## 所使用的系统版本
## 所使用产品版本
## 问题的详细描述与截图(如果可以)
## 如何复现该问题

**Comment by wangKuma** [comment]
你好，我没有理解你的意思。能叙述的详细一点吗？

**Comment by muwuren** [comment]
使用shell脚本启动musicbox，在启动前创建一个空文件，结束时删除这个空文件，如果启动时发现这个文件存在，表示已经有musicbox启动了，直接退出。
