### ISSUE TITLE
= =我来问问怎么支持win的

### ISSUE THREAD

**Issue by TXIuTnVsbA** [darknessomi/musicbox#608]
= =我算是把api里的算法看来三天了，也搬砖了，win下可以用了，
就是mp3在win下的播放问题，虽然可以播放，但是关于播放完自动下一首的这个问题我解决不了

**Comment by diandengs** [comment]
win直接官方下窗口版不是更好用？？

**Comment by TXIuTnVsbA** [comment]
= =我不知道要怎么回复楼上，我只想用python而已

**Comment by renxida** [comment]
@TXIuTnVsbA 实践精神万岁。

如果把 @diandengs 的想法极端化，那我们其实也可以说“Linux直接换windows不是更好？”

实践精神：真的真的很贱很精神 XD

**Comment by Aceassassinpark** [comment]
没有去研究代码，直接用pip安装会在安装"pycrypto"的时候出现编译错误，后来直接在cygwin下面安装好了，这也算是在win下面运行了吧。

**Comment by TXIuTnVsbA** [comment]
@Aceassassinpark win下可以用那个包,你需要python for vs那个什么鬼，而且python 需要64位，然后就可以用pip安装会在安装"pycrypto"了

**Comment by TXIuTnVsbA** [comment]
@Aceassassinpark http://blog.csdn.net/werewolf_st/article/details/45935913

**Comment by TXIuTnVsbA** [comment]
= =最后还是靠自己
https://github.com/TXIuTnVsbA/music163_test/blob/master/FM_play_test.py
哪个大神帮忙改改= =只能用timer来自动下一首了，不知道怎么暂停timer,所以还是不加暂停的功能了
后来发现pygame好像更好一点，就是不能直接load url,只能先下载再load

**Comment by dogabner** [comment]
Win10的话 可以用Bash on Ubuntu on Windows

**Comment by KingerLee** [comment]
@dogabner bash on Ubuntu on Windows上还是不能用，可能是ubuntu下声卡驱动和win下不一样的问题

**Comment by wangKuma** [comment]
#363
