### ISSUE TITLE
如何运行...

### ISSUE THREAD

**Issue by slidoooor** [darknessomi/musicbox#612]
使用

$ musicbox
Enjoy it !

mac安装之后输入musicbox找不到命令,小白求问...

**Comment by qq864151925** [comment]
ubuntu 17.10表示也没有命令

**Comment by cursorfei** [comment]
CentOS 7 表示也没有命令。。。

**Comment by qq864151925** [comment]
sudo 命令下安装就好 在2017年10月18日 16:47，cursorfei 写道： CentOS 7 表示也没有命令。。。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by wangKuma** [comment]
请尝试重新打开终端并运行下面这条命令
`ls  /usr/local/bin |grep musicbox`
