### ISSUE TITLE
实际上已经登录成功了，但还总是推送 You need login

### ISSUE THREAD

**Issue by fiepi** [darknessomi/musicbox#618]
每隔几分钟推送一次
![image](https://user-images.githubusercontent.com/15153999/32131810-3513db6a-bbea-11e7-852d-b5f75e5d5e3d.png)

**Comment by fiepi** [comment]
![image](https://user-images.githubusercontent.com/15153999/32132119-1a1098ca-bbf0-11e7-81a4-d4e02172cba2.png)

**Comment by ssfdust** [comment]
git版本？

**Comment by fiepi** [comment]
@ssfdust 发这条 issue 之前刚刚从 aur 升级到最新版。这条推送看起来是定时的，每五分钟推一次。
 musicbox -v
NetEase-MusicBox installed version:0.2.4.1

**Comment by aretlas** [comment]
我不想登陆。。怎么取消这个推送啊

**Comment by wangKuma** [comment]
[https://github.com/darknessomi/musicbox/issues/627](url) 相似问题

**Comment by wangKuma** [comment]
fixed @aretlas @fiepi
