### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by XIAZY** [darknessomi/musicbox#62]
为什么不添加一个将歌曲添加到歌单的功能呢？

**Comment by chaserhkj** [comment]
这是一个我已经开了坑但是还没有动手做的功能 = =
看[这个评论](https://github.com/darknessomi/musicbox/issues/56#issuecomment-88128073)

**Comment by darknessomi** [comment]
这是个坑，还没来得及回填

**Comment by jiexinhuang** [comment]
能有加心功能就是极好的~~

**Comment by darknessomi** [comment]
@jiexinhuang @XIAZY 已经有加❤功能了

**Comment by XIAZY** [comment]
终于加上了，谢谢。
前几天在树莓派上运行失败了，不知道怎么回事……

发自我的 iPad
