### ISSUE TITLE
无法播放，进度条只有1s

### ISSUE THREAD

**Issue by Tochase** [darknessomi/musicbox#621]
如题，求解答
ubuntu 17.10
![image](https://user-images.githubusercontent.com/15307280/32688400-e5dbc7ca-c70a-11e7-9452-e6bdf7719280.png)

**Comment by tleydxdy** [comment]
+1

**Comment by Tommywt** [comment]
+1

**Comment by Wanguy** [comment]
Try use system terminal instead Zsh or another shell?

**Comment by wangKuma** [comment]
由于这首歌没有版权，所以无法播放
