### ISSUE TITLE
网易云查ua了，不带浏览器ua只能插到歌单第一首歌

### ISSUE THREAD

**Issue by zanjie1999** [darknessomi/musicbox#628]

**Comment by chen-niu** [comment]
我的也是，歌单只有一首歌

**Comment by MacGuffinLife** [comment]
同样的问题，是什么原因，这两天突然这样的

**Comment by zanjie1999** [comment]
我自己寫的一個調接口生產歌單的程序也廢了

**Comment by Greedysky** [comment]
用网页版的api是可以的，旧版的api应该是废弃了

**Comment by out0fmemory** [comment]
应该不是ua的问题，musicbox里边已经有ua了

**Comment by square-li** [comment]
http request的header里 user-agent 改一下就可以了 比如改成curl的ua就可以

On Nov 26, 2017, at 22:32, Sparkle <notifications@github.com<mailto:notifications@github.com>> wrote:


我自己寫的一個調接口生產歌單的程序也廢了

**Comment by zanjie1999** [comment]
前天测试过改成chrome的ua已经不行了

**Comment by out0fmemory** [comment]
大家编译试试 #631 ，借鉴https://github.com/Binaryify/NeteaseCloudMusicApi/commit/a1239a838c97367e86e2ec3cdce5557f1aa47bc1 ，使用了v3接口请求播放列表

大家自行编译后尝试下有没有解决问题，本地简单测试了下，是可以使用了

如果有问题，请及时反馈我来更新
