### ISSUE TITLE
小白通过命令行可以运行，放到pycharm处运行不起来。。。

### ISSUE THREAD

**Issue by Wbqqqq** [darknessomi/musicbox#641]
ModuleNotFoundError: No module named '__main__.menu'; '__main__' is not a package    因为想进行单步调试进行学习。。。。 不知道啥原因。。。

**Comment by wangKuma** [comment]
绝对引用的问题
有两种方式解决
1. 将 musicbox 的路径添加到 环境变量 PYTHONPATH 中
2. 修改 from .menu import Menu 为 from menu import Menu

**Comment by Wbqqqq** [comment]
![1513832828983](https://user-images.githubusercontent.com/17332298/34241372-015d606c-e650-11e7-969c-c53e7b5963e9.jpg)

**Comment by Wbqqqq** [comment]
![1513832853473](https://user-images.githubusercontent.com/17332298/34241377-0a3b54c8-e650-11e7-8315-db32a500bc7e.jpg)

**Comment by Wbqqqq** [comment]
我的是mac 然后我是这么配的  .meun 应该没错 如果是meun反倒应该错了...就是跑不起来...

**Comment by wangKuma** [comment]
你需要将 /Users/***/musicbox  加入到 PYTHONPATH 中
或者
因为所有的文件都在一个文件夹内，你可以使用 “from menu import Menu” 这种方式引用

**Comment by Wbqqqq** [comment]
老哥。。。我又来麻烦你了.... PYTHONPATH我也有的  应该不是环境的问题   你有q啥的吗  我现场演示给你看....
