### ISSUE TITLE
无法在pycharm中单步调试

### ISSUE THREAD

**Issue by Wbqqqq** [darknessomi/musicbox#646]
在PyCharm can't find terminal 报错之后  我在环境pycharm的变量中加上了TERM=xterm   但是 随之的错误就是 File "/Users/wangbingquan/Desktop/Python/musicbox/NEMbox/ui.py", line 57, in __init__
    curses.cbreak()
_curses.error: cbreak() returned ERR  始终报这句错  找了很多资料都不得其法 。终端运行 完美无压力  只是在pycharm上出现了这样的问题.   求解救  感恩。

**Comment by Yxnt** [comment]
终端运行----> pycharm IDE 菜单栏----> Run ----> Attach to local Process
@Wbqqqq
