### ISSUE TITLE
怎么得到歌单api

### ISSUE THREAD

**Issue by yoga1314** [darknessomi/musicbox#648]
方便透露下，怎么得到歌单api：http://music.163.com/api/playlist/detail?id={songId}吗，找了两天在Chrome也没找到

**Comment by wangKuma** [comment]
https://github.com/darknessomi/musicbox/wiki
可以看一下这个 wiki

**Comment by vc1** [comment]
网易云音乐 PC 客户端加密 API 逆向解析 http://www.freebuf.com/articles/web/164636.html @wangKuma @darknessomi

**Comment by ExerciseBook** [comment]
好厉害啊。
