### ISSUE TITLE
没有正确处理终端窗口大小变更

### ISSUE THREAD

**Issue by jiegec** [darknessomi/musicbox#651]
我在macOS的iTerm2下用tmux，窗口大小的变更比较常见，但是变更后没有重新绘制整个窗口，于是会出现奇怪的现象。

另外，在抛出异常（如断网）的时候，会直接显示出来，但是由于ncurses会十分混乱。

P.S. 我十分努力地克制住了自己用英语写issue的行为。。写了个英文的title又删掉了（

**Comment by jiegec** [comment]
例子：两个箭头
![image](https://user-images.githubusercontent.com/6127678/34478707-648c58be-efdd-11e7-926b-2eb7ce6a68d0.png)

**Comment by zhang-wenchao** [comment]
请作者看下，这个怎么处理吧

**Comment by zhang-wenchao** [comment]
我也有这个问题，不过我不是使用的 tmux，我是使用的 i3wm

**Comment by zhang-wenchao** [comment]
@darknessomi
