### ISSUE TITLE
建议将Pycrypto的依赖改为pycryptodome

### ISSUE THREAD

**Issue by falling12** [darknessomi/musicbox#654]
在windows上安装pycrypto很困难，
而[pycryptodome](https://pypi.python.org/pypi/pycryptodome)的对于windows的兼容性更好。

**Comment by wangKuma** [comment]
不推荐在 windows 上使用；

**Comment by sunhuachuang** [comment]
我也赞成替换，因为pycrypto已经不再开发和维护了，现在大部分新项目全部都在迁移到pycryptodome

**Comment by ExerciseBook** [comment]
windows上使用简直崩溃

**Comment by kigawas** [comment]
已经换到pycryptodome，让@darknessomi 更新一下就行了
