### ISSUE TITLE
error没有声音

### ISSUE THREAD

**Issue by zkl99999** [darknessomi/musicbox#657]
♫  ♪ ♫  ♪ HD 320k 近了，远了 - 严宽  < 近了，远了 >Exception in thread Thread-1:
             T顺序播放 [                                 ] (00:00/00:01)
               作词 : 阡寒
ython3.6/threadin 作曲 : 姜超迁6, in _bootstrap_inner
                                                         self.run()
                网易云音乐 > 新碟上架 > 近了，远了                   File "/home/zkl/anaconda3/lib/python3.6/threading.py", line 864, in run
                                                                self._target(*self._args, **self._kwargs)
                           File "/home/zkl/anaconda3/lib/python3.6/site-packages/NetEase_MusicBox-0.2.4.2-py3.6.egg/NEMbox/player.py", line 97, in runInThread
                                                                                  strout = self.popen_handler.stdout.readline().decode('utf-8')
                                                               AttributeError: 'NoneType' object has no attribute 'stdout'

**Comment by wangKuma** [comment]
1.本地使用 mpg123 能播放音乐吗？
2.tail -f ~/.netease-musicbox/musicbox.log 查看一下日志
