### ISSUE TITLE
Win 新歌手分类，采用了新 url 

### ISSUE THREAD

**Issue by darknessomi** [darknessomi/musicbox#66]
![0c jin_m j2vcychszu9 q](https://cloud.githubusercontent.com/assets/6939375/7670304/56df01fe-fcd2-11e4-88b7-e991f70100b2.jpg)
url : 
http://music.163.com/eapi/v1/artist/list
http://music.163.com/eapi/toplist/artist
![7j7re 4 v 4bma u 8d 2a](https://cloud.githubusercontent.com/assets/6939375/7670307/74f98a60-fcd2-11e4-86ee-29d38a2b8a85.png)
![oe5k_r2k5rmpl lis 7m8ms](https://cloud.githubusercontent.com/assets/6939375/7670308/7b83bf86-fcd2-11e4-85b8-d50a8d2bb2ac.png)
看上去是加密了的样子

**Comment by darknessomi** [comment]
http://music.163.com/eapi/toplist/artist 

POST /eapi/toplist/artist HTTP/1.1                
    Host: music.163.com                
    Connection: keep-alive                
    Content-Length: 810                
    Accept: */*                
    Content-Type: application/x-www-form-urlencoded                
    Origin: orpheus://orpheus                
    User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.138 Safari/537.36                
    Accept-Encoding: gzip,deflate                
    Accept-Language: en-us,en;q=0.8                
    Cookie: os=pc; deviceId=B144B77FEDED2A34A967A4FABD38B04A0BB28B56001C42002733; osver=Microsoft-Windows-8-Professional-build-9200-64bit; appver=1.7.0.89635; usertrack=ezq0aVVYfmIviTtqC0arAg==; MUSIC_A=19e6696c10aff9bf82d5d454ae511032c191799626c91a7bb682aa5e3352209df052f4911d156841e20334c68f9e270d14f7bc14f265edf78853d8e422e454d5d43d015b29b8f86e5812ec6e75baef4128114078ccd72be78ea35baf971a78d5bf122d59fa1ed6a2; __csrf=743bf36c8b6c12c736f414ebaa640fc8; usertrack=ezq0aVVYfmIviTtqC0arAg==; channel=netease 

http://music.163.com/eapi/v1/artist/list 
POST /eapi/v1/artist/list HTTP/1.1                
    Host: music.163.com                
    Connection: keep-alive                
    Content-Length: 778                
    Accept: */*                
    Content-Type: application/x-www-form-urlencoded                
    Origin: orpheus://orpheus                
    User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.138 Safari/537.36                
    Accept-Encoding: gzip,deflate                
    Accept-Language: en-us,en;q=0.8                
    Cookie: os=pc; deviceId=B144B77FEDED2A34A967A4FABD38B04A0BB28B56001C42002733; osver=Microsoft-Windows-8-Professional-build-9200-64bit; appver=1.7.0.89635; usertrack=ezq0aVVYfmIviTtqC0arAg==; MUSIC_A=19e6696c10aff9bf82d5d454ae511032c191799626c91a7bb682aa5e3352209df052f4911d156841e20334c68f9e270d14f7bc14f265edf78853d8e422e454d5d43d015b29b8f86e5812ec6e75baef4128114078ccd72be78ea35baf971a78d5bf122d59fa1ed6a2; __csrf=743bf36c8b6c12c736f414ebaa640fc8; usertrack=ezq0aVVYfmIviTtqC0arAg==; channel=netease

**Comment by TangMonk** [comment]
现在正在开发一款爬虫，歌手分类这里有点难抓包了，请问 @darknessomi 解决了吗？谢谢
