### ISSUE TITLE
请问下CentOS该如何安装，谢谢

### ISSUE THREAD

**Issue by aqzwss** [darknessomi/musicbox#67]
这一步进行完了 sudo python setup.py install
然后呢？
我的CentOS没法使用apt-get，有没有yum安装方法？

**Comment by prikevs** [comment]
然后直接输入musicbox就可以了

**Comment by darknessomi** [comment]
CentOS 自带源没有 mpg123 ，需自己编译安装。
或者去[这里](http://pkgs.repoforge.org/mpg123/)下载对应系统版本rpm安装。

**Comment by aqzwss** [comment]
首先感谢解答。
我是CentOS 7 链接里的rpm包最高支持到CentOS6,我尝试下载安装了一个，目前的现象是点击歌曲的时候程序就无响应了。
我在mpg123官网上看到的下载包都是zip 里面是dll和exe格式的

**Comment by darknessomi** [comment]
没有对应版本的，请自己下载源码编译安装，不要安装非对应版本程序。

**Comment by darknessomi** [comment]
我想你需要的是这个 ```ftp://ftp.pbone.net/mirror/atrpms.net/el7-x86_64/atrpms/stable/mpg123-1.18.1-1.el7.x86_64.rpm```

**Comment by aqzwss** [comment]
谢谢！我已经成功安装了这个rpm包，可是还是在播放歌曲的时候没有响应，只有左下角的光标在闪烁。
是因为我的声卡驱动问题么？

**Comment by aqzwss** [comment]
好用了。原来是按空格不是按数字播放，是我自己没有搞清楚。
很感谢你的热心支持！

**Comment by zhangolve** [comment]
上面的链接应该失效了吧，翻墙都打不开，我的是centOS 6 ，没找到对应的rpm包。

**Comment by kigawas** [comment]
Pip安装
