### ISSUE TITLE
用的win10WSL，所有歌曲都是1s

### ISSUE THREAD

**Issue by bodhisatan** [darknessomi/musicbox#685]
![lt2ll5_eb2lx _ 7c4 g_0y](https://user-images.githubusercontent.com/35862184/37775148-2074500e-2e1d-11e8-8f2c-67d6f70ead62.png)

![mb a78 3k12132 0b5ir74u](https://user-images.githubusercontent.com/35862184/37775161-2b05d6dc-2e1d-11e8-8bab-3181798e3afa.png)

还有这个问题 = =

**Comment by bodhisatan** [comment]
安装的方法是按照Ubuntu安装方法来的qwq

**Comment by wangKuma** [comment]
#686
