### ISSUE TITLE
Mac 10.13.4输入musicbox命令，提示无法找到这个命令

### ISSUE THREAD

**Issue by 1mrliu** [darknessomi/musicbox#695]
-bash: musicbox: command not found

**Comment by kigawas** [comment]
https://github.com/darknessomi/musicbox#macos%E5%AE%89%E8%A3%85

**Comment by osindex** [comment]
ln -s /Library/Frameworks/Python.framework/Versions/3.6/bin/musicbox /usr/local/bin/musicbox
