### ISSUE TITLE
About build_playinfo

### ISSUE THREAD

**Issue by 20015jjw** [darknessomi/musicbox#70]
I'm working on the **song name scrolling feature**. I'm finished with the menu part, where the long song name will scroll automatically. Here' s what it looks like:

![scroll_demo](https://cloud.githubusercontent.com/assets/1016134/8105765/b2e1d29c-106e-11e5-8a9a-2667abce3a81.gif)

I'm now having trouble applying it to the ```build_playinfo``` function: it repeatedly print the whole screen. I'm wondering, how is this function different from  ```build_menu```? Thanks in advance.

**Comment by darknessomi** [comment]
Please create a new Pr
Thx

**Comment by 20015jjw** [comment]
Okay, let me finalize.
