### ISSUE TITLE
请问下网易后台怎么确定一个不同的secret下对应的每组encrypt_data是符合验证的

### ISSUE THREAD

**Issue by actanble** [darknessomi/musicbox#703]
## 请问下网易后台怎么确定一个不同的secret下对应的每组encrypt_data是符合验证的
- 就是 `encrypt.py` 中的后台怎么处理这个 post 后的data 进行用户验证。这个 `secret` 是不一样的， 那个算法是什么。
- 我也想把这个应用到我自己的平台上来， 就是不知道这个后台怎么处理 传回来的 data

**Comment by kigawas** [comment]
RSA+AES。

**每次请求**的时候生成随机字节作为AES密钥k，用公钥p加密k，用k加密数据d，把加密后的数据ed和加密后的密钥ek一起传过去。

服务器用私钥先解密ek得到k（RSA），然后用密钥k解密ed得到d（AES）。

**Comment by kigawas** [comment]
注意：网易的参数不一定是密码学安全的。

如果你想自己搞一套这个东西可以参考pycryptodome的[文档](https://pycryptodome.readthedocs.io/en/latest/src/examples.html)
