### ISSUE TITLE
0.2.5 版本引入的问题

### ISSUE THREAD

**Issue by frostRed** [darknessomi/musicbox#709]
环境：Manjaro 最新

安装方式：pip

每首歌总是再剩下最后 10 秒左右自动停了，也不会播放其它歌

登录后总显示 『这里什么都没有 -，-』，帐号里面的歌单拉不到了

**Comment by kigawas** [comment]
好像是mpg123的问题，我也发现了

**Comment by frostRed** [comment]
新版本已修复
