### ISSUE TITLE
播放完一首不能自动播放下一首

### ISSUE THREAD

**Issue by sudoyang** [darknessomi/musicbox#720]
NetEase-MusicBox installed version:0.2.5.2
Ubuntu 16.04
使用了shadowsocks-qt5代理服务

**Comment by agutools** [comment]
树莓派中也有同样的问题，所有"播放模式"均无效，另外Python2版本则是启动十几秒后出现脚本错误提示。

**Comment by sudoyang** [comment]
依然不能自动播放下一首 我是通过pip安装的 已经升级到0.2.5.3
