### ISSUE TITLE
最新版 单曲循环播放歌曲达到一定次数时，出错  快速遍历歌曲停不下来

### ISSUE THREAD

**Issue by little-humor** [darknessomi/musicbox#731]

**Comment by out0fmemory** [comment]
列表随机循环一样有这个问题，所以这次的版本重构完就是一坨shit。。。根本没测试

最近我来找时间看下这个问题

**Comment by Catofes** [comment]
@out0fmemory  其实核心是根本木人去管， 0.2.5.2 出来之后基本就不能用，我去凑合凑合的调了调，在自己电脑上跑起来之后就没管了。

作为一个golang用户谁知道list.clear()是 python3 才有的。。

说白了这个项目缺单元测试。

**Comment by out0fmemory** [comment]
@Catofes  这个项目的维护者就是胡搞，merge、重构什么的完全没测试。。。。

现在最新的版本就是不能用的，播放列表里的引用url也不刷新，过一会儿就不能听了。。。

**Comment by Catofes** [comment]
我觉得彻底重构一遍比较靠谱。不过还是这个问题，谁来做呢。

**Comment by Catofes** [comment]
以及我在我机子上测试了啊。然而并不管用。

**Comment by out0fmemory** [comment]
我找时间来看下吧，最近很少时间，已经回滚到23bedaf05972c63fe2512c3e1915e15ec7b75ca7

**Comment by Catofes** [comment]
核心问题就是这个，大家都没时间。。

这个项目早该重构了，我看我自己写的代码都觉得不不忍直视。。
