### ISSUE TITLE
musicbox在FreeBSD下中文显示乱码

### ISSUE THREAD

**Issue by darkgeek** [darknessomi/musicbox#76]
您好，

我在FreeBSD 10.1 RELEASE下（python版本为2.7_2,2，LC_ALL设置为zh_CN.UTF-8）尝试安装musicbox，过程都很顺利，没有错误。但运行它的时候，发现中文全是乱码，如图所示：

![2015-06-17-191921_732x401_scrot](https://cloud.githubusercontent.com/assets/1317617/8205779/4424124a-1526-11e5-8226-411711fc8a46.png)

我猜想可能是FreeBSD下python对于编码转换方面有问题，不过我不懂python，所以不敢确定。您若有兴趣，希望您能帮忙看看这个问题。谢谢。

**Comment by darknessomi** [comment]
是的，参考#40 ，你需要使用UTF-8编码

**Comment by darknessomi** [comment]
重新定义了LC_ALL ，请覆盖重装试试？

**Comment by darkgeek** [comment]
@darknessomi 谢谢你的回复。刚才我又Google了一会儿，发现这其实是个涉及到FreeBSD的一个很低层的[问题](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=171246)。Python会使用系统的libreadline.so，而FreeBSD下的libreadline.so是链接到libncurses.so，而非libncursesw.so，前者不支持Unicode但后者支持……好吧，看起来应该是FreeBSD的问题😓。

**Comment by BoKoIsMe** [comment]
我的文字正常 但是没有声音，mpg123能播放的
