### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by hwdef** [darknessomi/musicbox#788]
无论用手机号还是邮箱都显示登录信息不对，系统是fedora29，pip安装

**Comment by LstHeart** [comment]
你可能是设置了登录保护，我之前设置登录保护之后，无论怎么登录都不行，现在取消登录保护之后，就可以直接登录了。 @hwdef

**Comment by hwdef** [comment]
@LstHeart 你说的对，问题解决了，谢谢
