### ISSUE TITLE
歌词第三行没有清除

### ISSUE THREAD

**Issue by Park-ma** [darknessomi/musicbox#789]
前一首歌曲播放完之后，由于歌词过长，在第三行有显示歌词，然后这段歌词一直会显示，直到有新的覆盖掉之前的。![图片](http://wx2.sinaimg.cn/mw690/0060lm7Tly1g0ahp35g5kj30vg0jq40m.jpg)

**Comment by Park-ma** [comment]
就像上面的第三行会一直显示

**Comment by cyalias** [comment]
实在不行可以拉着命令窗口右边框往左一下，然后再拉回原位置即可清除

**Comment by Park-ma** [comment]
谢谢

**Comment by cyalias** [comment]
这个只是一个临时解决方法，如果你懂代码，可以从根本上解决
