### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by paranoidjk** [darknessomi/musicbox#79]
ubuntu15.04
执行sudo python setup.py install
出错
Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

**Comment by chaserhkj** [comment]
`sudo apt-get install python-setuptools`

Just RTFM of python please.

**Comment by paranoidjk** [comment]
It works, thank you.
