### ISSUE TITLE
mac  始终无法登陆

### ISSUE THREAD

**Issue by C-Jason-Yang** [darknessomi/musicbox#812]
<img width="1680" alt="WX20190509-093604@2x" src="https://user-images.githubusercontent.com/22712601/57421335-ef9b1380-723d-11e9-92b6-c201ffd60f5a.png">

**Comment by Tuuure** [comment]
Arch linux, the same problem

**Comment by PoacherBro** [comment]
Manjaro, same problem

**Comment by alongsoCJR** [comment]
解决了吗？

**Comment by huguiqi** [comment]
兄弟解决了吗？我mac系统升级以后，musicbox也无法登陆了
