### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by hiapk** [darknessomi/musicbox#83]
艾玛，登录信息好像不对呢 (O_O)#

                   [1] 再试一次
                   [2] 稍后再试

                   请键入对应数字:

**Comment by razhangwei** [comment]
I had exactly the same issue when I was trying to log in with my netease account.

**Comment by WilenceYao** [comment]
@hiapk  只能用手机号码,登录用微博等其他的帐号不行，需要在 [music.163.com](http://music.163.com/) 网站上先绑定手机号

**Comment by caisan** [comment]
使用手机号同样出现了这样的问题

**Comment by darknessomi** [comment]
网易是换接口了，还加密了。。。。。

**Comment by YaozhongZhang** [comment]
我也遇到了这个问题

**Comment by caisan** [comment]
@darknessomi 只是登陆接口吗？听歌没有问题。

**Comment by darknessomi** [comment]
@caisan 是的

**Comment by hiapk** [comment]
以前可以的  另外  sc  收藏这个功能,不能去掉重复,不能删掉自己不想要的歌曲么?

**Comment by stkevintan** [comment]
这个问题，我已经解决了：<http://kevinsfork.info/2015/07/23/nwmusicboxapi/>
网易这次真是丧心病狂。。

**Comment by darknessomi** [comment]
@stkevintan  十分感谢，我会尽快推出更新的:-D

**Comment by darknessomi** [comment]
@stkevintan 请问，encSecKey 经过 RSA 加密之后是如何输出为 Hex 格式的？

**Comment by stkevintan** [comment]
@darknessomi 将明文从utf8编码转化为hex编码，得到一个16进制的数R，然后进行16进制运算：`R^exponent%modulus`得出来的结果就是hex格式。

**Comment by darknessomi** [comment]
@stkevintan 还有一个问题，AES加密两次后，为何我的输出的base64，很短，AES-128-CBC难道不是16位输出的么

**Comment by stkevintan** [comment]
@darknessomi 我也发现这个 问题了，但是在node.js上能够很容易解决，所以我也没有深究什么原因。

**Comment by mchome** [comment]
这是网页新接口吧，好像之前新老接口都能一起用，现在关了老接口返回code:500...

**Comment by Azcat** [comment]
@darknessomi 重新clone分支后,卸载重装,登录时还是不能使用

**Comment by darknessomi** [comment]
@Azcat  那是因为还没有搞定的缘故，待可以之后，我会合并到主分支的

**Comment by mchome** [comment]
额，好像是pycrypto不完整openssl，没有做padding，我用requests参照那个js写，试了下可以了

参考：http://stackoverflow.com/questions/10548973/encrypting-and-decrypting-with-python-and-nodejs

**Comment by darknessomi** [comment]
@mchome 来个 pr 呗

**Comment by darknessomi** [comment]
Thx！@stkevintan @mchome
