### ISSUE TITLE
登录时总显示登录信息不对

### ISSUE THREAD

**Issue by finalshake** [darknessomi/musicbox#832]
archlinux采用pip3安装，python3.7，网易云音乐没有手机注册，直接用的网易邮箱和密码登录的，在手机上的app登录没问题。但是musicbox上总是提示登录信息不对。

**Comment by finalshake** [comment]
删除pip的musicbox，git clone安装了它，竟然能登录了，很奇怪。

**Comment by finalshake** [comment]
删除pip的musicbox，git clone安装了它，竟然能登录了，很奇怪。

**Comment by rikewang** [comment]
同样登录不了2.7.6 mac
