### ISSUE TITLE
mac OS Catalina 可用 亲测

### ISSUE THREAD

**Issue by e71828** [darknessomi/musicbox#844]
![Screen Shot 2020-03-28 at 1 16 35 PM](https://user-images.githubusercontent.com/24602820/77815479-6e1ecf00-70f6-11ea-981c-022e87978246.png)

感谢大神。

**Comment by wangjianyuan10** [comment]
本人的 fork 版本 mac 专用版 https://github.com/wangjianyuan10/musicbox  ，因为未在其他平台测试所以重开分支，支持触摸板 上下键 快速切换

**Comment by e71828** [comment]
@wangjianyuan10 你的下一页  d  有问题，f 对应的私人FM

**Comment by e71828** [comment]
@wangjianyuan10  Ubuntu18.04一样的问题，还需要加软连接
https://github.com/darknessomi/musicbox/issues/519#issuecomment-379989643

**Comment by wangjianyuan10** [comment]
@e71828   d f  已修复，谢谢  软链接问题应该是和原来的冲突了

**Comment by e71828** [comment]
打碟列表是什么，不过这个 z 有点问题。

...英文句号对应 下一fm。
///右除对应  加载更多fm。
@wangjianyuan10

**Comment by wangjianyuan10** [comment]
@e71828 
我很少用这个 fm ，所以没测试过，现在已经改好了😁  a 和 z 是俩个键  a 添加到打碟歌单，z 切换到打碟歌单，谢谢

**Comment by e71828** [comment]
构建不容易，熬夜不值得。

**Comment by wangjianyuan10** [comment]
哈哈哈，今日事，今日毕
