### ISSUE TITLE
我尝试在termux上运行，播放音乐时报错

### ISSUE THREAD

**Issue by blleng** [darknessomi/musicbox#845]
我在安卓上用termux运行musicbox，其他功能基本正常，但是播放时出错:

FileNotFoundError: [Errno 2] No such file or directory: 'mpg123'

**Comment by wangjianyuan10** [comment]
需要依赖 mpg123 库

**Comment by blleng** [comment]
> 需要依赖 mpg123 库

是的，我已经知道了，可惜termux官方的仓库里没有mpg123，很麻烦。
