### ISSUE TITLE
Windows的适配

### ISSUE THREAD

**Issue by rakernel** [darknessomi/musicbox#85]
试着在Windows上运行，结果当然不太好。
- 首先是curses在Windows下的缺失（当然可以通过 http://www.lfd.uci.edu/~gohlke/pythonlibs/ 来解决
- 其次是窗口指令（因为缺乏了XTerm，所以SIGWINCH作废
- 然后是窗口输出乱码（老问题了
- 最后比较不确定的是mpg123这个库的Windows情况（因为没运行起来

建议？：
- 判断OS，如在Windows系统下则跳过SIGWINCH以及转换为gbk（当然翻译成英文个人也是可以的

_因为个人不是学python的所以也无能为力提交pull request :(_

**Comment by darknessomi** [comment]
之前折腾过的，在最后一步卡住了，mpg123.....

**Comment by rakernel** [comment]
@darknessomi 如果是调用mpg123的二进制文件的话很容易把。。加入path里就好了

**Comment by darknessomi** [comment]
@rakernel 发一下你使用的命令行环境吧，我抽空搞一下

**Comment by rakernel** [comment]
@darknessomi 是`PATH`么？
···
PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Scripts;D:\mpg123;C:\Python27;C:\Python27\Scripts
···
使用的是[ConsoleZ](https://github.com/cbucher/console/)

**Comment by darknessomi** [comment]
嗯，知道了，周末看看

**Comment by darknessomi** [comment]
![image](https://cloud.githubusercontent.com/assets/6939375/9038682/cde34c36-3a28-11e5-87f5-f64182541b99.png)
出现新问题了，pycrypto 编译不过，不知为何，会调用 vc 来编译。。。

**Comment by rakernel** [comment]
@darknessomi 去那里提示的链接 http://aka.ms/vcpython27 安装就好，会自行调用的。
（貌似这个工具能编译的不仅仅只有python，在path里加入`C:\Users\%username%\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\bin\amd64`之后可以调用nmake编译了）
