### ISSUE TITLE
centos7(python3.7.7)安装musicbox报错no module named '_ctypes'

### ISSUE THREAD

**Issue by sevenyoungairye** [darknessomi/musicbox#867]
<img width="768" alt="help" src="https://user-images.githubusercontent.com/49781944/92249288-66145800-eefc-11ea-9c55-8b41a7176e3a.png">

求帮忙，，ヾ(^▽^*)))ヾ(^▽^*)))  ＜（＾－＾）＞，怎么解决啊。

**Comment by QRQaccount** [comment]
加个`--user`试试？

**Comment by sevenyoungairye** [comment]
没用呀

**Comment by sevenyoungairye** [comment]
> 加个`--user`试试？

没用呀
