### ISSUE TITLE
在播放到未有版权的歌曲时界面会打印出错误信息

### ISSUE THREAD

**Issue by QRQaccount** [darknessomi/musicbox#868]
使用的ubuntu20.04系统，KDE桌面环境，konsole终端。打印出错误信息后需要手动刷新,例如退回到上一界面再进入这个界面错误信息才会被刷新掉。不影响使用但有点点不美观。

**Comment by eavesmy** [comment]
启动的时候 musicbox 2> /dev/null,不显示就行
