### ISSUE TITLE
Mac OS X安装0.1.6版的pycrypto-2.6.1.tar.gz出现问题。

### ISSUE THREAD

**Issue by caisan** [darknessomi/musicbox#89]
Processing pycrypto-2.6.1.tar.gz
Running pycrypto-2.6.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-F_MEc_/pycrypto-2.6.1/egg-dist-tmp-CcQNCV
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
clang: error: unknown argument: '-mno-fused-madd'
error: Setup script exited with error: command 'cc' failed with exit status 1

我想是不是要把编译器连接到clang。因为我在Ubuntu上安装就没问题，而且Ubuntu上cc默认是连接到gcc的。

**Comment by caisan** [comment]
应该是clang不支持'-mno-fused-madd'这个参数

**Comment by caisan** [comment]
另外：sudo pip install pycrypto也是同样的错误提示。

**Comment by darknessomi** [comment]
额，同样是 clang 为何我就顺利编译呢？ 试试 gcc？

**Comment by darknessomi** [comment]
试试 sudo pip install -I pycrypto ？

**Comment by caisan** [comment]
我的是OS X 10.9，clang 6.0（llvm 3.5）

**Comment by caisan** [comment]
难道是少了“GMP or MPIR”这两个库？

**Comment by darknessomi** [comment]
有没有试试 gcc？我是 darwin15 clang 7.0

**Comment by caisan** [comment]
@darknessomi gcc试过（在Ubuntu上成功了）

**Comment by darknessomi** [comment]
是这样的，OS X 上你安装 gcc 后，/usr/bin/gcc 编译依然会调用 /usr/bin/clang ，你需要使用 gcc-5 命令来使用。

其实 gcc 只是 指向 clang 的别名。

**Comment by caisan** [comment]
@darknessomi 我懂你的意思了。但是 “你需要使用 gcc-5 命令来使用。“这句话的意思是说在执行这条命令：sudo python setup.py install时使用，即就是诸如这样：sudo python setup.py install gcc-5 ？

**Comment by darknessomi** [comment]
不是的，我是指你在手动安装pycrypto-2.6.1.tar.gz时，可以使用gcc-5来安装

**Comment by caisan** [comment]
@darknessomi 看来还得重新编译&安装gcc。非常感谢 :D

**Comment by caisan** [comment]
@darknessomi  os x上安装gcc 4.8和gcc 4.6都试过了，都失败了，报不同的错误，

**Comment by darknessomi** [comment]
gcc 5.2 呢？

```
➜  ~  gcc-5 -v
Using built-in specs.
COLLECT_GCC=gcc-5
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/5.2.0/libexec/gcc/x86_64-apple-darwin15.0.0/5.2.0/lto-wrapper
Target: x86_64-apple-darwin15.0.0
Configured with: ../configure --build=x86_64-apple-darwin15.0.0 --prefix=/usr/local/Cellar/gcc/5.2.0 --libdir=/usr/local/Cellar/gcc/5.2.0/lib/gcc/5 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew gcc 5.2.0 --without-multilib' --with-bugurl=https://github.com/Homebrew/homebrew/issues --enable-plugin --disable-nls --disable-multilib
Thread model: posix
gcc version 5.2.0 (Homebrew gcc 5.2.0 --without-multilib)
```

**Comment by caisan** [comment]
@darknessomi 
hi 你好：
今天我又重新装了一次gcc5.2，不过还是出错了，不知道是不是我过程不对，于是我把安装的过程记录下来，
希望得到您的帮助
1）安装gcc 5.2
$ brew install gcc52
整个过程自动完成，很顺利
2）由于编译用到的编译器是cc，于是我进行了如下操作：
先:   cd /usr/bin
接着：sudo ln -s /usr/local/Cellar/gcc5/5.2.0/bin/x86_64-apple-darwin13.0.0-gcc-5.2.0 cc
检验一下，显示如下：
➜  bin  cc --version

cc (Homebrew gcc5 5.2.0) 5.2.0

Copyright (C) 2015 Free Software Foundation, Inc.

This is free software; see the source for copying conditions.  There is NO

warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

（不知道这里显示的信息是否完整或者正确？）

然后，我就开始安装了，试试看用pip安装：

➜ pip install pycrypto --trusted-host pypi.douban.com

到最后还是出错了，出错信息如下：

configure: creating ./config.status

  config.status: creating src/config.h

  building 'Crypto.PublicKey._fastmath' extension

  creating build/temp.macosx-10.9-intel-2.7

  creating build/temp.macosx-10.9-intel-2.7/src

  cc -fwrapv -Wall -Wstrict-prototypes -Qunused-arguments -Qunused-arguments -arch x86_64 -arch i386 -pipe -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/ -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/_fastmath.c -o build/temp.macosx-10.9-intel-2.7/src/_fastmath.o

  cc: error: unrecognized command line option '-Qunused-arguments'

  cc: error: unrecognized command line option '-Qunused-arguments'

  error: command 'cc' failed with exit status 1

----------------------------------------

  Failed building wheel for pycrypto

Failed to build pycrypto

Installing collected packages: pycrypto

  Running setup.py install for pycrypto

    Complete output from command /Users/caisan/.virtualenvs/test0721/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/b_/n5jxs3xx5qd5xzsc_544xklh0000gn/T/pip-build-cjKwn1/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/b_/n5jxs3xx5qd5xzsc_544xklh0000gn/T/pip-IA2Z3D-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/caisan/.virtualenvs/test0721/include/site/python2.7/pycrypto:

    running install

    running build

    running build_py

    running build_ext

    running build_configure

    building 'Crypto.PublicKey._fastmath' extension

    cc -fwrapv -Wall -Wstrict-prototypes -Qunused-arguments -Qunused-arguments -arch x86_64 -arch i386 -pipe -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/ -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/_fastmath.c -o build/temp.macosx-10.9-intel-2.7/src/_fastmath.o

    cc: error: unrecognized command line option '-Qunused-arguments'

    cc: error: unrecognized command line option '-Qunused-arguments'

    error: command 'cc' failed with exit status 1

   ----------------------------------------

我想还是编译器的问题吧。

**Comment by darknessomi** [comment]
➜  ~  pip install pycrypto --trusted-host pypi.douban.com
```
Collecting pycrypto
  Downloading pycrypto-2.6.1.tar.gz (446kB)
    100% |████████████████████████████████| 446kB 894kB/s
Building wheels for collected packages: pycrypto
  Running setup.py bdist_wheel for pycrypto
  Stored in directory: /Users/omi/Library/Caches/pip/wheels/96/b0/e6/03e439d41cb2592b5c4c9c77873761d6cbd417b332076680cd
Successfully built pycrypto
Installing collected packages: pycrypto
Successfully installed pycrypto-2.6.1
```

**Comment by darknessomi** [comment]
我直接用 clang 就过了

**Comment by darknessomi** [comment]
我在 Win 上神奇复现了错误。。。。
的确是编译器的问题，但是 clang 应该是可以直接通过编译的。

**Comment by darknessomi** [comment]
![image](https://cloud.githubusercontent.com/assets/6939375/9038682/cde34c36-3a28-11e5-87f5-f64182541b99.png)

**Comment by caisan** [comment]
@darknessomi 
以下这条命令可以成功：
```
$ CFLAGS=-Wunused-command-line-argument-hard-error-in-future pip install -U pycrypto --trusted-host pypi.douban.com
```

**Comment by caisan** [comment]
@darknessomi 我成功了，谢谢你了，:-D

**Comment by darknessomi** [comment]
说说解决方法呗

**Comment by caisan** [comment]
@darknessomi 看上面加粗的部分。
