### ISSUE TITLE
树莓派安装后显示快捷键错误，点击没反应

### ISSUE THREAD

**Issue by Qa70601234** [darknessomi/musicbox#899]
return request('get', url, params=params, **kwargs)
  File "/home_ _ z Z Z LD 128k 四季予你  -  程响  < 四季予你 >pi.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/requests_cache/core.py", line 136, in request
    **kwargs
  File "/home/pi/.local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/requests_cache/core.py", line 104, in send
    response, timestamp = self.cache.get_response_and_time(cache_key)
  File "/home/pi/.local/lib/python3.7/site-packages/requests_cache/backends/base.py", line 70, in get_response_and_time
    if key not in self.responses:
  File "/usr/lib/python3.7/_collections_abc.py", line 666, in __contains__
    self[key]
  File "/home/pi/.local/lib/python3.7/site-packages/requests_cache/backends/storage/dbdict.py", line 169, in __getitem__
    return pickle.loads(bytes(super(DbPickleDict, self).__getitem__(key)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 1: ordinal not in range(128)

能进去界面，但是快捷键没反应，确认键可以，也能正常播放

**Comment by JWCook** [comment]
Try this:
```
pip3 install -U --user requests-cache
```

`requests-cache 0.6.3` may fix this issue.

**Comment by Qa70601234** [comment]
> Try this:
> 
> ```
> pip3 install -U --user requests-cache
> ```
> 
> `requests-cache 0.6.3` may fix this issue.

**Comment by Qa70601234** [comment]
> Try this:
> 
> ```
> pip3 install -U --user requests-cache
> ```
> 
> `requests-cache 0.6.3` may fix this issue.
> 下载你的  `pip3 install -U --user requests-cache  `显示错误如下，还是不能用数字键
```
netease-musicbox 0.3.1 has requirement requests-cache<0.6.0,>=0.5.2, but you'll have requests-cache 0.6.3 which is incompatible.
Installing collected packages: requests-cache
Successfully installed requests-cache-0.6.3
```

**Comment by JWCook** [comment]
The message "`...requirement requests-cache<0.6.0,>=0.5.2...`" is due to [this line in pyproject.toml](https://github.com/darknessomi/musicbox/blob/master/pyproject.toml#L37). I believe `musicbox 0.3.1` and `requests-cache 0.6.3` are compatible, though.

Do you still get the message "`UnicodeDecodeError: 'ascii' codec can't decode byte...`"? It is possible that there are old items in the cache created with **python 2**, and encoded with `ascii` instead of `utf-8`.

Try clearing the cache:
```bash
python -c "\
import NEMbox.api; \
import requests_cache; \
requests_cache.clear()"
```

Or a different way to do the same thing, by deleting the cache file directly:
```bash
cache_path=$(python -c "from NEMbox.api import Constant; print(Constant.cache_path)")
echo $cache_path
rm $cache_path
```

**Comment by Qa70601234** [comment]
no  `UnicodeDecodeError: 'ascii' codec can't decode byte...`
还是不行，清除了缓存，我点数字后再点j或k会跳过点的数字，比如指标在0，点了数字5在点j，指标就会在5那里，像是加了个5一样。。。

**Comment by JWCook** [comment]
Oh, that's strange! These might be 2 separate problems, then. I don't have any more ideas about the shortcut keys, sorry!
