### ISSUE TITLE
requests_cache 库错误

### ISSUE THREAD

**Issue by PhyX-Meow** [darknessomi/musicbox#915]
musicbox 启动报错：
```
❯ musicbox
Traceback (most recent call last):
  File "/usr/sbin/musicbox", line 33, in <module>
    sys.exit(load_entry_point('netease-musicbox==0.3.1', 'console_scripts', 'musicbox')())
  File "/usr/sbin/musicbox", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/NEMbox/__main__.py", line 10, in <module>
    from .menu import Menu
  File "/usr/lib/python3.9/site-packages/NEMbox/menu.py", line 27, in <module>
    from .api import NetEase
  File "/usr/lib/python3.9/site-packages/NEMbox/api.py", line 24, in <module>
    requests_cache.install_cache(Constant.cache_path, expire_after=3600)
AttributeError: module 'requests_cache' has no attribute 'install_cache'
```

操作系统：Manjaro Linux testing branch
requests-cache 包版本：0.6.2-2
Python 版本：3.9.3

**Comment by JWCook** [comment]
This may happen if there are other missing dependencies (due to how imports are handled in [`requests_cache/__init__.py`](https://github.com/reclosedev/requests-cache/blob/fc5944c47162253e7abc81bf904bb48bcf6e09a1/requests_cache/__init__.py#L10-L25)).

Try this:
```
pip install -U --upgrade-strategy=eager requests-cache
```
which should install version 0.6.3 and all its dependencies. If that does not work, please post the output of `pip freeze`.

You could also try installing the older version pinned in [pyproject.toml](https://github.com/darknessomi/musicbox/blob/cd2874eda6d71d5329ac417bb0f8308ab012e657/pyproject.toml#L37):
```
pip install requests-cache==0.5.2
```

Apologies for posting in English, hopefully you can make some sense of that with Google translate!

**Comment by PhyX-Meow** [comment]
@JWCook Thanks very much, installing version 0.5.2 with pip makes things work. Seems newer version is somehow not compatible with musicbox.

**Comment by JWCook** [comment]
It looks like musicbox works with the latest version of requests cache, if it's installed from PyPI (`pip install NetEase-MusicBox`), so this may be specific to Manjaro and Arch Linux. The newer version (0.6.x) adds another dependency, [url-normalize](https://pypi.org/project/url-normalize/), which is on PyPI but not on AUR. Did you install from the Arch User Repository, or a different repo?

I took a look at the [netease-musicbox-git]( https://aur.archlinux.org/packages/netease-musicbox-git/) AUR package, and I see that the [python-requests-cache](https://aur.archlinux.org/packages/python-requests-cache/) package only has 0.5.2 available. So installing musicbox _should_ only install requests-cache 0.5.2.

So it's possible that what happened is a different package (other than musicbox) installed a newer version of requests-cache into your `/usr/lib/python3.9/site-packages/`, but didn't install one of its extra dependencies (probably url-normalize).

**Comment by PhyX-Meow** [comment]
@JWCook Thank you very much. Confirmed musicbox run normally after installing extra dependencies (url-normalize and itsdangerous).
Actually python-requests-cache has 0.6.3 available in aur, but the package does not has the two dependencies.
See https://aur.archlinux.org/packages/python-requests-cache/
