### ISSUE TITLE
Failed to run on RPi4 32-bit

### ISSUE THREAD

**Issue by BlueEve04** [darknessomi/musicbox#942]
pi@raspberrypi:~ $ musicbox
Traceback (most recent call last):
  File "/usr/local/bin/musicbox", line 6, in <module>
    from NEMbox.__main__ import start
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/__main__.py", line 16, in <module>
    from .menu import Menu
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/menu.py", line 24, in <module>
    from .api import NetEase
  File "/usr/local/lib/python2.7/dist-packages/NEMbox/api.py", line 20, in <module>
    import requests_cache
  File "/usr/local/lib/python2.7/dist-packages/requests_cache/__init__.py", line 6, in <module>
    from .response import AnyResponse, CachedHTTPResponse, CachedResponse, ExpirationTime
  File "/usr/local/lib/python2.7/dist-packages/requests_cache/response.py", line 39
    def __init__(self, original_response: Response, expire_after: ExpirationTime = None):
                                        ^
SyntaxError: invalid syntax
pi@raspberrypi:~ $ 

以上为命令行错误信息

**Comment by kigawas** [comment]
需要Python 3

**Comment by BlueEve04** [comment]
okk 
已解决
但不是缺python3

而且在RPi3B+上可以进入但是放歌会报错  
mpg123已经装了

求教。。

错误信息：
      \u266b  \u266a \u266b  \u266a    POP SONG   -   \u7c73\u6d25\u7384\u5e2b  < POP SONG >Exception in thread Thread-1:
     Traceback (most recent call last):
                   \u7f51\u6613\u4e91\u97f3\u4e50 > \u6392\u884c\u699c   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                   self.run()
                                               File "/usr/lib/python2.7/threading.py", line 754, in runOP SONG   -   \u7c73\u6d25\u7384\u5e2b  < POP SONG >
                   1. T    self.__target(*self.__args, **self.__kwargs)

-                    2. \u7ea6\u5b9a   -   \u5bb9\u7956\u513f  < \u7ea6\u5b9a >                        File [`"/home/pi/.local/lib/python2.7/site-packages/src/player.py",`](url) line 48, in runInThread                 4. \u7231   -   BKStore, \u5218\u601d\u9274  < \u7231. >

      self.popen_handler = 

> 

> `**_subprocess.Popen(['mpg123',` '-R',], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE) Selena Gomez  < Let Somebo

dy Go >_**            7. \u4fa6\u63a2   -   \u6c88\u4ee5\u8bda, \u5f20\u94b0\u742a  < \u4fa6  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__\u83b9  < \u8d64\u9cb8 >
                   9. \u795e\u9b42\u98a0\u5012   -       errread, errwrite)
                                                             File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
                                                      raise child_exception
                                                                           OSError: [Errno 2] \u6ca1\u6709\u90a3\u4e2a\u6587\u4ef6\u6216\u76ee\u5f55

**Comment by BlueEve04** [comment]
> 需要Python 3

不是这个原因

但是reboot了N次之后就好了。。。就很奇妙。。

**Comment by BlueEve04** [comment]
**_\u266b  \u266a \u266b  \u266a    POP SONG   -   \u7c73\u6d25\u7384\u5e2b  < POP SONG >Exception in thread Thread-1:
     Traceback (most recent call last):
                   \u7f51\u6613\u4e91\u97f3\u4e50 > \u6392\u884c\u699c   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                   self.run()
                                               File "/usr/lib/python2.7/threading.py", line 754, in runOP SONG   -   \u7c73\u6d25\u7384\u5e2b  < POP SONG >
                   1. T    self.__target(*self.__args, **self.__kwargs)
                   2. \u7ea6\u5b9a   -   \u5bb9\u7956\u513f  < \u7ea6\u5b9a >                        File "/home/pi/.local/lib/python2.7/site-packages/src/player.py", line 48, in runInThread                 4. \u7231   -   BKStore, \u5218\u601d\u9274  < \u7231. >
      self.popen_handler = subprocess.Popen(['mpg123', '-R',], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE) Selena Gomez  < Let Somebo
dy Go >            7. \u4fa6\u63a2   -   \u6c88\u4ee5\u8bda, \u5f20\u94b0\u742a  < \u4fa6  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__\u83b9  < \u8d64\u9cb8 >
                   9. \u795e\u9b42\u98a0\u5012   -       errread, errwrite)
                                                             File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
                                                      raise child_exception
                                                                           OSError: [Errno 2] \u6ca1\u6709\u90a3\u4e2a\u6587\u4ef6\u6216\u76ee\u5f55_**


完整错误信息

**Comment by BlueEve04** [comment]
好了

又变成这样了

`
      \u266b  \u266a \u266b  \u266a    \u8d64\u9cb8   -   \u82cf\u8fd0\u83b9  < \u8d64\u9cb8 >Exception in thread Thread-17:
-16:                                                                        Traceback (most recent call last):l last):eback (most recent call last):
                   \u7f51\u6613\u4e91\u97f3\u4e50   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_innerap_innerline 801, in __bootstrap_inner
                          self.run()lf.run())                   self.run()
                                      File "/usr/lib/python2.7/threading.py", line 754, in run, in runhreading.py", line 754, in run SONG >
                  self.__target(*self.__args, **self.__kwargs)_kwargs)*self.__args, **self.__kwargs). \u7ea6\u5b9a   -   \u5bb9\u7956\u513f  < \u7ea6\u5b9a >               File "/home/pi/.local/lib/python2.7/site-packages/src/player.py", line 51, in runInThreadInThreadr.py", line 51, in runInThreadBKStore, \u5218\u601d\u9274  < \u7231. >                      self.popen_handler.stdin.write("L " + popenArgs + "\n") + "\n")write("L " + popenArgs + "\n")         6. Let Somebody Go   -   ColdplayTypeError: cannot concatenate 'str' and 'NoneType' objects   \u6c88\u4ee5\u8bda, \u5f20\u94b0\u742a  < \u4fa6\u63a2 >pe' objects
                   8. \u8d64\u9cb8   -   \u82cf\u8fd0\u83b9  < \u8d64\u9cb8 >
                -> 9. \u795e\u9b42\u98a0\u5012   -   \u9093\u5178  < \u795e\u9b42\u98a0\u5012 >






`

可以放的。。。。
但是。。

**Comment by BlueEve04** [comment]
谢谢帮助我的人！！
