### ISSUE TITLE
使用urwid实现更高级的终端界面

### ISSUE THREAD

**Issue by kikyous** [darknessomi/musicbox#95]
https://github.com/wardi/urwid

这是一个以前做的程序

![](https://camo.githubusercontent.com/57fb4c78f64bba2ff616ee27de980e2f3fbab370/68747470733a2f2f7261772e6769746875622e636f6d2f6b696b796f75732f7866646f776e2f626574612f73637265656e73686f742f7866646f776e2e706e67)

**Comment by Catofes** [comment]
要是terminal支持显示图片就好了 23333

**Comment by kikyous** [comment]
@Catofes 那我们造一个浏览器吧

**Comment by darknessomi** [comment]
其实已经有浏览器[轮子](https://github.com/stkevintan/nw_musicbox/)了

**Comment by Catofes** [comment]
本来我也是想写一个网页版 然后拖延症
