### ISSUE TITLE
可否加入收藏歌单的功能.

### ISSUE THREAD

**Issue by holmeszyx** [darknessomi/musicbox#96]
要是可以收藏一个歌单就好了.
像精选歌单里面别人的歌单,或者搜索的专辑, 歌手啊.

**Comment by Catofes** [comment]
Marked。 新的收藏储存结构已经有了，可以保存多个收藏等。敬请期待～

**Comment by yylzcom** [comment]
请问这个功能有了吗，我翻了一遍快捷键列表没有找到，如果有了麻烦告知（原谅我的高度近视）
